### ISSUE TITLE
Request to add support for recognizing powerpc (32bit)

### ISSUE THREAD

**Issue by ionenwks** [PyO3/maturin#1025]
Seen riscv/mips been added recently, could it be done for this too?

Not a ppc32 user myself (don't think I can offer much help/support) but there's been interest in Gentoo, and currently seems unrecognized by `src/target.rs`, aka:
```
failures:

---- editable_pyo3_ffi_pure stdout ----
The architecture powerpc is not supported
thread 'editable_pyo3_ffi_pure' panicked at 'The architecture powerpc is not supported', tests/common/mod.rs:74:13
```

Downstream bugs:
https://bugs.gentoo.org/861509
https://bugs.gentoo.org/861518

**Comment by ionenwks** [comment]
On a side-note, Gentoo recently started to support using rust on sparc -- there's no plan to use maturin there at the moment but it could be something in the future.

**Comment by messense** [comment]
Sure, we can add powerpc support, as for sparc do you mean sparc64 or 32-bit sparc?

**Comment by ionenwks** [comment]
> Sure, we can add powerpc support, as for sparc do you mean sparc64 or 32-bit sparc?

Thanks, and sparc64 -- sparc32 is excluded from rust support entirely in Gentoo.

**Comment by messense** [comment]
Ok, I gotta ask the same question, what does `sysconfig.get_platform()` returns on sparc64?

**Comment by ionenwks** [comment]
> Ok, I gotta ask the same question, what does `sysconfig.get_platform()` returns on sparc64?

linux-sparc64

**Comment by messense** [comment]
I'm [releasing v0.13.2-beta.1](https://github.com/PyO3/maturin/actions/runs/2751104660), please give it a try when it's out so we can fix any issues before next release.

**Comment by ionenwks** [comment]
Alright, thanks. I'll add the beta so our arch testers can run tests with at least ppc.

**Comment by ionenwks** [comment]
> Alright, thanks. I'll add the beta so our arch testers can run tests with at least ppc.

Looks like no issues from follow up on bugs, passes tests, and it can build watchfiles

https://bugs.gentoo.org/861509#c4
https://bugs.gentoo.org/861518#c2

**Comment by ionenwks** [comment]
> sparc -- there's no plan to use maturin there at the moment but it could be something in the future

Well, ended up being done after all. Just to report that it works fine on sparc64 too.

**Comment by messense** [comment]
0.13.2 is out.
