### ISSUE TITLE
`Maturin-0.13.1` modify the `version` in `pyproject.toml` that make it incompatible with `PEP-440` when using Local version identifier

### ISSUE THREAD

**Issue by FirelightFlagboy** [PyO3/maturin#1036]
### Bug Description

I'm using `maturin-0.13.1`.

I've a python project that is migrating to `maturin` to include some Rust in it.

The project is using a [local version identifier](https://peps.python.org/pep-0440/#local-version-identifiers) that formatted like follow: `+dev{git-short-commit-id}` (e.g: `+devabc123de` with `abc123de` as a short commit id) to build subsequent wheel.

When using `maturin` to build the wheel, it generate the metadata with an invalid version in it (that don't correspond to the version present in `pyproject.toml`)

`Maturin` will tranform a valid pep-440 version `0.0.0+abc123de` to `0.0.0_abc123de`

## What I would expect

I would expect that the version present in `pyproject.toml`  is the same as the version present in the metadata generated by `maturin`

### Your Python version (`python -V`)

3.10.5

### Your pip version (`pip -V`)

pip 22.1.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

# To reproduce the error with `pip wheel`

1. `maturin new local-version-id -b pyo3`
2. `cd local-version-id`
3. apply the following patch with `patch -i pyproject.toml.patch pyproject.toml` (`pyproject.toml.patch` file contains the patch below)
  ```diff
  diff --git a/pyproject.toml b/pyproject.toml
  index 44ae643..0c4d106 100644
  --- a/pyproject.toml
  +++ b/pyproject.toml
  @@ -3,6 +3,7 @@ requires = ["maturin>=0.13,<0.14"]
   build-backend = "maturin"
 
   [project]
  +version = "0.0.0+abc123de"
   name = "local-version-id"
   requires-python = ">=3.7"
   classifiers = [
  ```
4. `pip wheel . -w dist -f wheel --use-pep517`
```
Looking in links: wheel
Processing /home/andesite/Documents/local-version-id
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: local-version-id
  Building wheel for local-version-id (pyproject.toml) ... done
  Created wheel for local-version-id: filename=local_version_id-0.0.0_abc123de-cp310-cp310-linux_x86_64.whl size=975695 sha256=6ef30e204bc231b4c50396a009f5e3639493cf43df055d0cf66f703ff3470e7e
  Stored in directory: /home/[abridged]/.cache/pip/wheels/7d/8f/93/0f0f0567cee12c569b193f19405387ebf033ff55abc2b1ecef
  WARNING: Built wheel for local-version-id is invalid: Metadata 1.2 mandates PEP 440 version, but '0.0.0-abc123de' is not
Failed to build local-version-id
ERROR: Failed to build one or more wheels
```

# To see the Generated metadata by `maturin` 

1. Reproduce the steps `1` to `3` above (before `pip wheel ...`)
2. `maturin pep517 write-dist-info --metadata-directory metadata -i $(which python)` (I got the command from `pip wheel` when enabling verbose `-vvv`)
3. See the generated version in the metadata
  ```
  $ grep '^Version:' metadata/local_version*.dist-info/METADATA
  Version: 0.0.0_abc123de
  ```

**Comment by messense** [comment]
Thanks for the report, version handling is indeed unpolished at the moment.

**Comment by FirelightFlagboy** [comment]
I've tested `maturin-0.13.2-beta.2`, the fix indeed correct the error with the local version id :+1:
