### ISSUE TITLE
Default CI.yml results in duplicate workflow runs

### ISSUE THREAD

**Issue by smheidrich** [PyO3/maturin#1040]
### Bug Description

Having maturin put a [default CI.yml](https://github.com/PyO3/maturin/blob/2876dbecbf7df1eb8314570fa0605f57d4e7c737/src/templates/CI.yml.j2) into newly initialized projects' `.github/workflows` is a great idea, but because it specifies

```yaml
on:
  push:
  pull_request:
```

for the entire workflow, it causes duplicate runs for pull requests: once for the push and once for the PR.

Wouldn't it make sense to default to something like

```yaml
on:
  push:
    branches:
      - main
  pull_request:
```

like in [your own `test.yml`](https://github.com/PyO3/maturin/blob/2876dbecbf7df1eb8314570fa0605f57d4e7c737/.github/workflows/test.yml) instead?

If the concern was that not everyone's main branch would be called `main`, e.g. when initializing a project in an old repository that still uses `master`, I'd say that it's very unlikely considering the _vast_ majority of use cases for `maturin init` will be brand new projects, and the ones that aren't will probably have existing CI configs anyway. But if that's not good enough, there could be a check whether maturin is run inside an existing repository and if it has a `master` or `main` branch.

Thoughts?

### Your Python version (`python -V`)

irrelevant

### Your pip version (`pip -V`)

irrelevant

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Initialize a project using `maturin init` (or `maturin new`).
2. Check the generated files including `.github/workflows/CI.yml` into the project's Git repository, create a GitHub project for it and push it.
3. Create a merge request and observe that the workflow specified in `CI.yml` executes twice.

**Comment by messense** [comment]
Maybe we can use the following setup? I'm happy to accept a PR.

```yaml
on:
  push:
    branches:
      - main
      - master
  pull_request:
```
