### ISSUE TITLE
Add option to not upgrade dependencies in maturin develop

### ISSUE THREAD

**Issue by wjones127** [PyO3/maturin#1050]
I was recently surprised to find that `maturin develop` will silently upgrade all Python dependencies. I was doing this in CI test run unit tests on our minimum supported version of dependencies in delta-rs:

```bash
pip install pyarrow==4  # minimum supported
maturin develop  # silently upgrades to 9.0.0
python -m pytest  # tests against wrong version of PyArrow 
```

I'm not sure what causes this, but might be the use of `--force-reinstall`.

It would be nice if:

 1. `maturin develop` displayed a message about upgraded dependencies, either showing the std out from `pip` or just some generic message.
 2. There was a way to override this behavior. This could either be:
    1. A flag that somehow ensured that dependencies weren't unnecessarily upgraded. I'm not sure if this is possible.
    2. An argument to pass in additional arguments to the `pip install` command, so we could pass in pinned dependency versions.

For (2), you might wonder why we can't just install the old version *after* running `maturin develop`. In our case, the dependency no longer provided binaries the test environment (manylinux2010) in the latest version, so upgrading caused `maturin develop` to attempt to build it from source. We'll drop support for `manylinux2010` soon, but it would be nice if situations like this didn't come up.

**Comment by messense** [comment]
I think add `--no-deps` to `pip install --force-reinstall` should work? We already install dependencies before this.

Can you try add it here? If it works, feel free to send us a PR.

https://github.com/PyO3/maturin/blob/a4440dc19510a7c8fa76c81bf757f4447856fed8/src/develop.rs#L99-L105

**Comment by messense** [comment]
Please try [maturin v0.13.2-beta.4](https://github.com/PyO3/maturin/releases/tag/v0.13.2-beta.4).
