### ISSUE TITLE
Only working maturin develop. Anything else crashes

### ISSUE THREAD

**Issue by asaltanubes** [PyO3/maturin#1055]
### Bug Description

Following the steps of pyo3 guide i made a virtual enviroment installed maturin and ran maturin init. Then used maturin develop and everything went fine. Except when i tried to use maturin build or maturin publish or maturin sdist it crashes with this report
[report-49c989c6-02c5-4fbb-b387-4221039c2f88.zip](https://github.com/PyO3/maturin/files/9300118/report-49c989c6-02c5-4fbb-b387-4221039c2f88.zip)
s

### Your Python version (`python -V`)

Python 3.9.4

### Your pip version (`pip -V`)

pip 20.2.3

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

create a folder with a python virtual enviroment and pip install maturin.
maturin init
maturin build

**Comment by messense** [comment]
https://github.com/PyO3/maturin/blob/241a00ae658d830804ae02e04c9e0ce7263663a3/src/python_interpreter/mod.rs#L523

Your terminal outputs invalid utf-8 characters when running this script https://github.com/PyO3/maturin/blob/241a00ae658d830804ae02e04c9e0ce7263663a3/src/python_interpreter/get_interpreter_metadata.py

can you try running `python3 get_interpreter_metadata.py`?

**Comment by asaltanubes** [comment]
Yep. this is the output i got

> {"executable": "C:\\Users\\gusta\\Desktop\\rarar\\.env\\Scripts\\python.exe", "major": 3, "minor": 9, "abiflags": null, "interpreter": "cpython", "ext_suffix": ".cp39-win_amd64.pyd", "abi_tag": null, "platform": "win-amd64", "system": "windows", "pointer_width": 64}

**Comment by messense** [comment]
Please give v0.13.2-beta.5 a try, `pip install -U --pre maturin`.

**Comment by asaltanubes** [comment]
yep, that seems to work TY!!
