### ISSUE TITLE
Wheel build failing for `x86_64` and `i686` on linux

### ISSUE THREAD

**Issue by samuelcolvin** [PyO3/maturin#1057]
### Bug Description

Builds of pydantic-core have just started failing, see [this](https://github.com/pydantic/pydantic-core/runs/7787632705) build,

For `x86_64`, the log has the following:

```
📦 Including license file "LICENSE"
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo)
/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo)
/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo)
```

For `i686` I see:

```
📦 Including license file "LICENSE"
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: /root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo: /lib/libc.so.6: version `GLIBC_2.15' not found (required by /root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo)
/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo: /lib/libc.so.6: version `GLIBC_2.17' not found (required by /root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo)
Error: The process '/usr/bin/docker' failed with exit code 1
```

### Your Python version (`python -V`)

the job installs 3.10.6

### Your pip version (`pip -V`)

NA

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

See the build log.

**Comment by messense** [comment]
See my comment here: https://github.com/pydantic/pydantic-core/commit/ae3b7077eb67522712b205b52935460179763562#commitcomment-80926390

This is related to #857.

**Comment by samuelcolvin** [comment]
Thanks, sorry for the noise.

**Comment by messense** [comment]
BTW, switch to build on stable Rust can also resolve that issue. I plan to adjust maturin-action to account for this breaking change in nightly Rust for the `auto` option.

**Comment by samuelcolvin** [comment]
Okay, I think rust stable is a better idea, I'll try to submit a PR.

Currently the pydantic organisation has a backlog of builds, so I'm waiting for that to resolve itself :sweat:.
