### ISSUE TITLE
setuptools-rust like `NoBinding` support?

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1058]
https://setuptools-rust.readthedocs.io/en/latest/reference.html#setuptools_rust.Binding.NoBinding

I'm not totally sure about the use case of `NoBinding`, opening an issue for discussion.

**Comment by messense** [comment]
@davidhewitt I'm curious about your thoughts on this.

**Comment by davidhewitt** [comment]
In setuptools-rust it just means that no features get passed to the build. I guess if maturin has a similar combination of options already it might not need this?

**Comment by messense** [comment]
In maturin you need to choose a binding type right now, no option to disable it. For example you can not build a simple cdylib then bridge it with `ctypes`.

**Comment by messense** [comment]
https://cs.github.com/?scopeName=All+repos&scope=&q=Binding.NoBinding+language%3APython

A quick search shows that most of the `NoBinding` users are using `cffi` so it's covered by maturin's `cffi` bindings, [one of them](https://github.com/crypto-org-chain/chainlibpy/blob/master/build.py) is using `uniffi` which uses `ctypes` to load the shared library.

So I think we don't need to support it right now.
