### ISSUE TITLE
The dependency rpassword 7 means a nightly rustc

### ISSUE THREAD

**Issue by woutervb** [PyO3/maturin#1070]
### Bug Description

When trying to create a wheel on Ubuntu Jammy (22.04) & Ubuntu Focal (20.04), it fails with an error that rpassword can't be build `namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line`

```PIP_NO_CACHE_DIR=1 PIP_WHEEL_DIR=build env/bin/pip wheel /srv/sdists/maturin-0.13.2.tar.gz
  
  × Building wheel for maturin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/maturin
      copying maturin/import_hook.py -> build/lib.linux-x86_64-cpython-310/maturin
      copying maturin/__init__.py -> build/lib.linux-x86_64-cpython-310/maturin
      copying maturin/__main__.py -> build/lib.linux-x86_64-cpython-310/maturin
      running egg_info
      creating maturin.egg-info
      writing maturin.egg-info/PKG-INFO
      writing dependency_links to maturin.egg-info/dependency_links.txt
      writing requirements to maturin.egg-info/requires.txt
      writing top-level names to maturin.egg-info/top_level.txt
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      running build_ext
      running build_rust
      cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v
      error: failed to get `anyhow` as a dependency of package `maturin v0.13.2 (/tmp/pip-req-build-pp0gr68x)`
      
      Caused by:
        failed to load source for dependency `anyhow`
      
      Caused by:
        Unable to update registry `crates-io`
      
      Caused by:
        failed to update replaced source registry `crates-io`
      
      Caused by:
        failed to parse manifest at `/srv/rust_vendored/rpassword-7.0.0/Cargo.toml`
      
      Caused by:
        namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
      error: `cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v` failed with code 101
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for maturin
```

### Your Python version (`python -V`)

python 3.8 on Focal, 3.10 on Jammy

### Your pip version (`pip -V`)

pip 21.2.4

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

pip wheel maturin-0.13.2.tar.gz

**Comment by messense** [comment]
Your Rust version is too old. That feature was already stabilized in 1.60.0, see https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

**Comment by woutervb** [comment]
I know that the rustc 1.59 which is the version provided in an Ubuntu LTS release.

In #708 I saw that you sometimes do take actions to ensure availability on platforms is a specific version of rustc isn't available, Requiring a version that is available since April, just 4 months, seems a bit harsh.

**Comment by messense** [comment]
OK, so for normal users we recommend use our pre-built wheels or compile with stable Rust installed via rustup. 

If you are try to package maturin into Ubuntu/Debian, feel free to open a new issue to discuss it, we have a lot of dependencies, it may be easy to support Rust 1.59 right now, but in the long run we'd need to add a CI job to ensure its compatibility.

**Comment by messense** [comment]
Opened https://github.com/PyO3/maturin/pull/1071
