### ISSUE TITLE
Including .pyi files from rlib dependencies of extension modules?

### ISSUE THREAD

**Issue by jmrgibson** [PyO3/maturin#1106]
I have a _rust library_ (rlib) that provides an abstract pyo3 interface, and other extension modules/crates that implement the interface by depending on the the rust library. The rust library contains the python API, and therefore also contains the .pyi type hints. The extension modules just provide implementations, and don't expose any new python interfaces.

I'm wondering if it's possible to have maturin automatically collect `.pyi` files from rlib dependencies?

At the moment I'm copying the rlib `.pyi` file to each extension module before invoking maturin, which works OK, but does mean it's an extra step in the build process.

**Comment by messense** [comment]
I'm not sure what you're proposing is a general use case.

> The rust library contains the python API, and therefore also contains the .pyi type hints. The extension modules just provide implementations, and don't expose any new python interfaces.

Then why not just move `.pyi` file to the extension modules?
