### ISSUE TITLE
Look in wrong path to find python interpreter when using maturin develop

### ISSUE THREAD

**Issue by ArchGuyWu** [PyO3/maturin#1108]
### Bug Description

 maturin looks in **$VENV_ROOT** instead of **$VENV_ROOT**\bin to find python interpreter caused `maturin develop` to fail

### Your Python version (`python -V`)

Python 3.10.7

### Your pip version (`pip -V`)

pip 22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. create a virtual environment using `virtualenv $VENV_NAME` 
2. then run `maturin develop`, the command will fail due to maturin looks in **$VENV_ROOT** instead of **$VENV_ROOT**\bin to find python interpreter

**Comment by messense** [comment]
I can't reproduce this issue, did you activate your virtual environment before executing maturin? And maturin actually looks in `$VENV_ROOT\Script` to find python.exe.

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1556054/190541134-e2e771a9-e474-46dc-979d-f2ca9020bce9.png">

**Comment by ArchGuyWu** [comment]
Yes,I've activate it.
![Annotation 2022-09-16 101506](https://user-images.githubusercontent.com/52102426/190541937-b3fb3f5d-1f32-4c64-bb28-5320dcaa9f7d.png)

**Comment by ArchGuyWu** [comment]
And I'm using virtualenv,maybe you're using another tool?

**Comment by messense** [comment]
What version of maturin are you using? Your venv looks a little odd to me, usually on Windows, activation scripts are in `Scripts` folder not `bin`.

**Comment by messense** [comment]
I'm also using virtualenv, quoting https://virtualenv.pypa.io/en/latest/user_guide.html#activators

> For a list of shells we provide activators see [activators](https://virtualenv.pypa.io/en/latest/cli_interface.html#activators). The location of these is right alongside the python executables ( usually Scripts folder on Windows, bin on POSIX)

**Comment by ArchGuyWu** [comment]
maturin 0.13.2
The latest version in msys2 package repo

**Comment by messense** [comment]
> The latest version in msys2 package repo

So you are running in msys2/mingw64 shell instead of normal Windows shell? Then I guess that's the issue.

**Comment by ArchGuyWu** [comment]
No,I only install packages using msys2,and run them in nushell.

**Comment by messense** [comment]
Did you install Python and virtualenv via msys2? It might have odd behavior this way because it thinks it's running in POSIX? If so can you try install Python and virtualenv from official channels?

**Comment by messense** [comment]
The offending code is 

https://github.com/PyO3/maturin/blob/4e533f93cf603b805abd0e1ea2a233d7ab02891c/src/target.rs#L570-L575

Because your venv does not have a `Scripts` folder it fallback to conda environment. We can certainly add support for `bin` but I'd like to know more about why it happens first.

**Comment by ArchGuyWu** [comment]
I think why this happens because both archlinux and msys2 are using pacman as its package manager,and they share the same pack script.

**Comment by ArchGuyWu** [comment]
That causes the pack style different from the offical windows python's.

**Comment by messense** [comment]
@ArchGuyWu Can you try #1112?

**Comment by messense** [comment]
I think you can install it via `pip install -U https://github.com/messense/maturin/archive/refs/heads/venv-python.zip`

**Comment by ArchGuyWu** [comment]
Ok,I'll try it.

**Comment by ArchGuyWu** [comment]
@messense It works,thanks.
