### ISSUE TITLE
Local dependencies of local dependencies packaging broken in 0.13.3

### ISSUE THREAD

**Issue by Tpt** [PyO3/maturin#1113]
### Bug Description

In Maturin 0.13.3 when running `maturin stdist`, the handling of relative path of local dependencies of local dependencies changed, breaking [pyoxigraph](https://github.com/oxigraph/oxigraph/tree/main/python) build.

The current Oxigraph crate structure is:
* `/pyoxigraph` (with dependency on oxigraph with `path = "../oxigraph"`)
* `/oxigraph` (with dependency on oxrdf with `path = "oxrdf"`)
* `/oxigraph/oxrdf`

- With Maturin 0.13.2, `local_dependencies/oxigraph/Cargo.toml` contains `oxrdf = { path= "../oxrdf", version = "0.1.0" }`
- With Maturin 0.13.3, `local_dependencies/oxigraph/Cargo.toml` contains `oxrdf = { path= "oxrdf", version = "0.1.0" }`

Nothing else has changed in the build. This change in local path leads to a `cargo metadata` error on installation.

PS: thank you so much for Maturin and all the improvements that are done version after version. This tool development is amazing to follow.

### Your Python version (`python -V`)

Python 3.10.6

### Your pip version (`pip -V`)

pip 22.0.4

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

GitHub CI output: https://github.com/oxigraph/oxigraph/actions/runs/3075557229/jobs/4970230508

Or:
1. `git clone --recursive https://github.com/oxigraph/oxigraph`
2. `maturin sdist -m python/Cargo.toml`
3. `pip install target/wheels/*.tar.gz`

**Comment by messense** [comment]
Sorry for the breakage, can you give #1114 a try?

**Comment by messense** [comment]
I tried `maturin sdist` then unpack the sdist and run `maturin build` in it, it works fine.

**Comment by Tpt** [comment]
> Sorry for the breakage, can you give https://github.com/PyO3/maturin/pull/1114 a try?

Yes, it works well! Your speed is amazing! Thank you!
