### ISSUE TITLE
Python code not included in mixed Rust/Python project with different Rust lib name

### ISSUE THREAD

**Issue by tiptenbrink** [PyO3/maturin#1117]
### Bug Description

Hi! I've used this project a lot and it has worked great, but one thing always bugged me a bit. There's no good way to include your Rust code as a submodule of your Python code, *while* maintaining the generated Rust bindings in your IDE.

In development mode and using maturin develop, this does seem possible. But when building the wheel, the Python code is excluded altogether. So I have a layout as follows:

```
opaquepy
├── Cargo.toml
├── python
│   └── opaquepy
│       ├── __init__.py
│       └── lib.py
├── pyproject.toml
└── src
    └── lib.rs
```

with the associated required 
```
[tool.maturin]
python-source = "python"
```

However, the name of the pymodule in Rust is not opaquepy, but instead _opaquepy. As such, my Cargo.toml looks like:

```
[package]
name = "_opaquepy"
...

[package.metadata.maturin]
python-source = "python"

[lib]
name = "_opaquepy"
crate-type = ["cdylib"]
```

Now when using `maturin develop`, everything works perfectly fine, with nice IDE support and also able to see the Rust file definitions:

![correct1](https://user-images.githubusercontent.com/75669206/191590952-7fd9eaed-f169-4dca-ac5a-d69b597c3f17.png)
![correct2](https://user-images.githubusercontent.com/75669206/191590965-e404fa27-baa1-461e-a318-f92b5e60a2ac.png)

However, when then building the wheel, the whole python "opaquepy" does not get included, and only the _opqrust function definitions are available to use. 

Everything works if you just name your Rust module the same as your Python module, but this then makes the Rust function definitions unavailable when using the Python project in another project or during development, leading to bad IDE support, as can be seen below:

![bad1](https://user-images.githubusercontent.com/75669206/191591484-397a0cc1-7160-46bf-a67f-bd94d91d4ceb.png)

If there is a way to make the Rust function definitions available / have IDE support for them, while at the same time still being able to also include Python source code.

Basically, what I'm looking for is creating a Rust module that has a separate name from your Python module but can be included as a submodule of your main Python project. External users of the Python package should then still be able to see that Rust submodule with automated bindings, but also the Python project. I think that this is supposed to be possible based on the above, so that's why I'm filing this as a bug. Apologies if it's more like a suggestion.

### Your Python version (`python -V`)

3.10.6

### Your pip version (`pip -V`)

22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Build this project: https://github.com/tiptenbrink/opaquebind/tree/9e941012d08038ddd447229d69404e29d4374d9a/opaquepy
2. The wheel does not include the Python project, only the Rust bindings

**Comment by messense** [comment]
It's not well documented yet, but you can add the following config in `Cargo.toml` to make it work

```toml
[package.metadata.maturin]
name = "opaquepy._opaquepy"
```

**Comment by tiptenbrink** [comment]
@messense Thank you, I indeed did not know that was possible! Maybe that can be added to the docs? If desired I could make a PR for that.
