### ISSUE TITLE
workspace dependencies inheritance support

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1122]
```
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: error: current package believes it's in a workspace when it's not:
current:   /Users/messense/Projects/maturin/test-crates/workspace_with_path_dep/python/dist/workspace_with_path_dep-0.1.0/Cargo.toml
workspace: /Users/messense/Projects/maturin/test-crates/workspace_with_path_dep/Cargo.toml

this may be fixable by adding `python/dist/workspace_with_path_dep-0.1.0` to the `workspace.members` array of the manifest located at: /Users/messense/Projects/maturin/test-crates/workspace_with_path_dep/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
```

**Comment by jondo2010** [comment]
I'm guessing there's no "librarified" support in rustc for handling the Cargo.toml and resolving the workspace, which is why Maturin rolls its own handling?

**Comment by messense** [comment]
We use `cargo metadata` to resolve the workspace, maturin has no problem build wheels for projects using workspace inheritance, the hurdle is when building source distribution maturin only includes what's required to build the wheel (for good reason, for example, to reduce sdist size), which may not include the workspace manifest file `Cargo.toml` so workspace inherited dependencies can not be resolved when building from source distribution.
