### ISSUE TITLE
maturin build/develop fail to include .so file from Rust dependency in workspace

### ISSUE THREAD

**Issue by jdiggans-twist** [PyO3/maturin#1148]
### Bug Description

I have a crate (`crate1`) which as a dependency on an external crate (`catboost`). When compiled with maturin into a wheel, the wheel includes the required libcatboost.so.1 file (thanks to work done by @messense in https://github.com/PyO3/maturin/issues/1088 and https://github.com/PyO3/maturin/issues/1093).

I then:
1. Converted the code which relies on catboost into a crate feature
2. Moved crate1 to be a child in a new Rust workspace
3. Made the catboost feature optional in `crate1`, off by default
4. Created a second crate, `crate2`, which is mostly a thin wrapper around `crate1` with some additional logic. `crate2` has `crate1` as a dependency with the `catboost` feature turned on.

The workspace looks like:
```
workspace
 |
 | -- > crate1
 | -- > crate2
```

The Cargo.toml file for `crate1` defines the optional feature:
```
[features]
scoringmodel = ["dep:catboost"]

[dependencies]
catboost = { git = "https://github.com/catboost/catboost", optional = true }
```

The `Cargo.toml` file for `crate2` just specifies `crate1` as a dependency but turns on the feature flag for `catboost`:
```
[dependencies]
crate1 = {path ="../crate1", features = ["catboost"]}
```

**Expected:** the resulting `crate2` whl file should *include* the `libcatboost.so.1` library file required by the feature flag for crate1.

**Observed:** the resulting `crate2` whl file does not link to- or contain the .so file and so the package is missing the relevant symbols:
```
>>> import crate2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/jdiggans/git/my_crates/target/wheels/crate2/crate2.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace (_CalcModelPredictionWithHashedCatFeatures)
```

Note that in this workspace I am building the wheel files via:
```
maturin build --release -m crate1/Cargo.toml
maturin build --release -m crate2/Cargo.toml
```
This is obviously on MacOS - I'll try building this in a linux container to see if the problem persists or is platform dependent.

### Your Python version (`python -V`)

3.9.10

### Your pip version (`pip -V`)

22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. `maturin build --release -m crate2/Cargo.toml`
2. `unzip target/wheels/crate2-6.0.0-cp39-cp39-macosx_11_0_arm64.whl`
3. `otool -L  target/wheels/crate2/crate2.cpython-39-darwin.so | grep libcatboostmodel.so.1`

No output; I expected to see `libcatboostmodel.so.1` in the linked libraries

**Comment by messense** [comment]
#1133, maturin only (re-)implements auditwheel for Linux at the moment.
