### ISSUE TITLE
Crate using `pyo3` and `build.rs` without `crate-type = ["cdylib"]` fails to build without bin target

### ISSUE THREAD

**Issue by yodaldevoid** [PyO3/maturin#1149]
### Bug Description

A crate using `pyo3` and a `build.rs` without `crate-type = ["cdylib"]` in its Cargo.toml fails to build with `maturin` 0.13.5 and `rustc` 1.64.0.

I expected that the crate type would no longer need to be specified due to `--crate-type` being stabilized and #1060 being merged. Specifying the binding type as `pyo3` works fine.

### Your Python version (`python -V`)

Python 3.10.5

### Your pip version (`pip -V`)

pip 22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Run `maturin new -b pyo3 pyo3_test`
2. Remove `crate-type = ["cdylib"]` from Cargo.toml
3. Create `build.rs` file in root of project with the following contents:
```
fn main() {}
```
3. `maturin build`
```
🐍 Found ...\AppData\Local\Programs\Python\Python310\python.exe
💥 maturin failed
  Caused by: Cargo didn't build a binary
```

**Comment by messense** [comment]
Thanks for the report, please try the fix in `main`.

**Comment by yodaldevoid** [comment]
Thank you for the quick fix. This has indeed fixed the issue.
