### ISSUE TITLE
built wheel may miss the top_level.txt

### ISSUE THREAD

**Issue by pmp-p** [PyO3/maturin#1154]
### Bug Description

pyxel module is built with maturin https://github.com/kitao/pyxel/issues/417#issuecomment-1264059190 
but i noticed that for some reason the top_level.txt is missing in the wheels distinfo

### Your Python version (`python -V`)

not my build

### Your pip version (`pip -V`)

not my build

### What bindings you're using

i think it's pyo3

### Steps to Reproduce

i don't know but @km19809 or @messense can elaborate on that.

**Comment by messense** [comment]
The wheel format PEP did not mention `top_level.txt`? https://peps.python.org/pep-0491/

I think it's needed in the old `egg` format?

**Comment by messense** [comment]
Quoting https://setuptools.pypa.io/en/latest/deprecated/python_eggs.html#top-level-txt-conflict-management-metadata

> This data is used by pkg_resources at runtime to issue a warning if an egg is added to sys.path when its contained packages may have already been imported.
>
> (It was also once used to detect conflicts with non-egg packages at installation time, but in more recent versions, setuptools installs eggs in such a way that they always override non-egg packages, thus preventing a problem from arising.)

I don't think we need to generate this file for wheels in maturin, correct me if I'm wrong.

**Comment by pmp-p** [comment]
> "the PEP is deliberately written to allow existing installers to be compliant with the specification when using existing install scheme definitions,"

The fact that you don't need explicitly, does not mean that you should not implicitely. There are maybe synthesis omissions from pep-0491 because it's a transitionning process from multiple disparate PEP (376/566/427) 

setup.py bdist_wheel  will produce a valid top_level.txt record, and it could be  the only way to solve conflicts when not using pip which cannot be user "as-is" on wasm platform at runtime. and without interrogating a third party service.

**Comment by messense** [comment]
> There are maybe synthesis omissions from pep-0491 because it's a transitionning process from multiple disparate PEP (376/566/427)

None of them mentions `top_level.txt` last time I checked.

**Comment by messense** [comment]
I wonder what was the problem you encountered when `top_level.txt` is missing from `pyxel` wheels?

**Comment by pmp-p** [comment]
because on WebAssembly/python we discussed about how to make dynamic import in wasm, and we come to the conclusion ( like pyodide does)  that an index is needed, the easy way to get module names from existing third party wheels is to read top_level.txt from the zip ( and match the import statement that may require installation

**Comment by messense** [comment]
I think `pyodide` implemented a fallback strategy when `top_level.txt` is missing: https://github.com/pyodide/pyodide/blob/90e20badd76d8a8b911f77034512137cc2e7d585/pyodide-build/pyodide_build/common.py#L123-L133

I'm happy to add `top_level.txt` if a new PEP/standard specifies it.

**Comment by pradyunsg** [comment]
Not including a top_level.txt file is totally fine IMO.

IIUC, even pyodide's fallback logic isn't perfect though. It doesn't account for namespace packages and it won't work for a wheel that dumps everything into a `.data` directory.

I'm on mobile so no easy code blocks but see these tests for a rough idea of what the data directory looks like (you can omit the first file and it's still a valid wheel): https://github.com/pypa/installer/blob/70ae05bb25c66e621064f2c031a04ac1192be30b/tests/test_core.py#L612

There might actually be a a reasonable case for standardising top_level.txt (or... possibly, an alternative to it with better semantics).

Alternatively, we could just have a robust shared implementation of how to figure out the top level importable names by looking through a wheel. That sounds like a a fun one, so... consider me nerd-sniped by that.

**Comment by pradyunsg** [comment]
https://gist.github.com/pradyunsg/22ca089b48ca55d75ca843a5946b2691
