### ISSUE TITLE
Build failure on ppc32 linux since updated to indicatif-0.17.1 crate (>=maturin-0.13.3)

### ISSUE THREAD

**Issue by ionenwks** [PyO3/maturin#1162]
### Bug Description

I assume(?) this is more an issue with the crate than here, but I'm not super familiar with rust (either way felt should know), the old indicatif-0.17.0-rc.6 didn't use AtomicU64.

Don't have ppc hardware myself so haven't tried, but this is from downstream report: https://bugs.gentoo.org/874747 (full build.log available there, technically is ppc64 building with a ppc32 toolchain for testing).
```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> /var/tmp/portage/dev-util/maturin-0.13.5/work/cargo_home/gentoo/indicatif-0.17.1/src/state.rs:2:25
  |
2 | use std::sync::atomic::{AtomicU64, AtomicU8, Ordering};
  |                         ^^^^^^^^^
  |                         |
  |                         no `AtomicU64` in `sync::atomic`
  |                         help: a similar name exists in the module: `AtomicU8`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `indicatif` due to previous error
```

### Your Python version (`python -V`)

Python 3.10.6

### Your pip version (`pip -V`)

N/A

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. normal `cargo build` with ppc32 rust toolchain in theory

**Comment by messense** [comment]
https://github.com/console-rs/indicatif/issues/475

**Comment by ionenwks** [comment]
Thanks, missed that one.
