### ISSUE TITLE
`native-tls` breaks shared library imports

### ISSUE THREAD

**Issue by mladedav** [PyO3/maturin#1165]
### Bug Description

Using `maturin build` on this:
```
use pyo3::prelude::*;

#[pyfunction]
pub fn tls(
) {
    _ = native_tls::TlsConnector::new();
}

#[pymodule]
fn ddp_sdk(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_pyfunction!(tls))?;
    Ok(())
}
```

results in an elf file with this dynamic section:
```
$ readelf -d path/to/unzipped/library.so

Dynamic section at offset 0xac5000 contains 33 entries:
  Tag        Type                         Name/Value
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../ddp_sdk.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto-d578cd7f.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
<rest omitted for brevity>
```

Not the second shared library name.

### Your Python version (`python -V`)

Python 3.8.10

### Your pip version (`pip -V`)

pip 22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

my maturin version is 0.13.3

Create a project with these dependencies:
```
pyo3 = { version = "0.16.5", features = ["extension-module"] }
native-tls = "0.2.8"
```
Put this into the lib.rs file:
```
use pyo3::prelude::*;

#[pyfunction]
pub fn tls(
) {
    _ = native_tls::TlsConnector::new();
}

#[pymodule]
fn ddp_sdk(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_pyfunction!(tls))?;
    Ok(())
}
```
Run:
```
maturin build -o dist && unzip -o -d dist/unzip dist/*.whl && readelf -d dist/unzip/*/*.so
```
There should be a line containing import of a file named `.1` instead of something like `libssl-578d2f9a.so.1.1`. Also if you try to import the package into python it will fail with an error stating that the library `.1` could not be found.

**Comment by mladedav** [comment]
Some additional information
- `maturin develop` works for me (I haven't checked if it uses completely different mechanism than `maturin build && pip install` but I assume it does).
- I am using WSL. If there would be issues with reproducing the issue I will try to reproduce it elsewhere.

**Comment by messense** [comment]
I can't reproduce this in CentOS 7 manylinux2014 container

```
Dynamic section at offset 0xb88000 contains 34 entries:
  Tag        Type                         Name/Value
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../ddp_sdk.libs]
 0x0000000000000001 (NEEDED)             Shared library: [libssl-2a9eae6f.so.10]
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto-19957f5b.so.10]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

**Comment by messense** [comment]
Please provide more information, thanks!

* Operating System version in `WSL`
* `patchelf --version` output
* https://github.com/PyO3/maturin/blob/b966b0d7aed8e637a13f2414faab41e56a1c7bd7/src/auditwheel/repair.rs#L32 add a `println!("{:?}" ext_libs);` after line 32 and its output

**Comment by konstin** [comment]
>  add a println!("{:?}" ext_libs); after line 32 and its output

No related to the original problem (i'll open a separate issue if it becomes a longer discussion), but I've been think about adding off-by-default tracing support and adding verbose `debug!` for each step and `trace!` for e.g. each copied file, so you can do e.g. `RUST_LOG=maturin=debug maturin build`. I've started using tracing in monotrail and found it really helpful for debugging. What do you think?

**Comment by messense** [comment]
@konstin Yes, I'm in favor of adding tracing support.

**Comment by mladedav** [comment]
I have been building this in local environment, not the centos manylinux docker image. I end up with either manylinux_2_28 or manylinux_2_31 based on other dependencies, but I've had the issue with ssl in both versions.

I've created a repo with minimal example [here](https://github.com/mladedav/maturin-issue)

I was able to reproduce it in a pod in kubernetes, again based on ubuntu:
```
kubectl run -it --rm --image=rust tmp -- bash

apt update
apt install python3-pip
apt install patchelf
pip3 install maturin
git clone https://github.com/mladedav/maturin-issue.git
cd maturin-issue
maturin build -o dist
unzip -d dist/unzip dist/issue-0.1.0-cp39-cp39-manylinux_2_28_x86_64.whl
readelf -d dist/unzip/issue/issue.cpython-39-x86_64-linux-gnu.so
```

I have a bit of issues with getting maturin in the manylinux 2014 container but I'll try again later.

**Comment by mladedav** [comment]
You're right, I've found the patchelf command maturin uses (which seems right) and if I run it manually, the resulting so file is broken so this is definitely an issue with patchelf.

Thanks for your help (and trying out the latest patchelf), I think we can close this as there is nothing to be done by maturin. Unless you would want to add some checks that everything works as intended, i.e. testing with readelf that everything is as should be. If you don't think that's worth the effort, feel free to close this.

Thanks again.
