### ISSUE TITLE
Failed to build sdist when using python first `src` layout

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1186]
#1185 was merged too soon, opening an issue to track this.

```bash
$ maturin sdist -o dist
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /Users/messense/.pyenv/versions/3.10.6/bin/python3
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Failed to add 340 bytes to sdist as /Users/messense/Projects/maturin/test-crates/pyo3-mixed-src/rust/Cargo.toml
  Caused by: paths in archives must be relative when setting path for
```

It's actually a general issue when `Cargo.toml` isn't located at the top level directory since we use `cargo package --list --allow-dirty` to get the list of files that should be included in sdist.

**Comment by konstin** [comment]
> It's actually a general issue when Cargo.toml isn't located at the top level directory since we use cargo package --list --allow-dirty to get the list of files that should be included in sdist.

oh i've never thought about that :/

**Comment by messense** [comment]
That was partially resolved in https://github.com/PyO3/maturin/pull/1099 already, so just need a few tweaks to make `src` layout work.
