### ISSUE TITLE
Error when workspace versioning is used

### ISSUE THREAD

**Issue by max-sixty** [PyO3/maturin#1206]
### Bug Description

Firstly — thanks a lot for `maturin`! 

It's very possible this is my mistake, but using the new workspace versioning doesn't seem compatible with maturin:

In https://github.com/prql/prql/pull/1062/files#diff-886695c8188a06c1336d111826a603750ed76b1cf1ee12ba8017818dc91238efL5-R7, we started using workspace versioning.

Unfortunately this [fails the build with maturin](https://github.com/prql/prql/actions/runs/3301763514/jobs/5447661364) with:

```
  Caused by: Failed to parse Cargo.toml at prql-python/Cargo.toml
  Caused by: invalid type: map, expected a string for key `package.version`
```

The maturin command is at https://github.com/prql/prql/blob/051544e5eef9f547182af777b3c9493d3e2b35dc/.github/actions/build-wheel/action.yaml#L13:

```
maturin build  --release -o dist -m prql-python/Cargo.toml
```

Thanks for shedding any light on this!

### Your Python version (`python -V`)

3.9

### Your pip version (`pip -V`)

22.3

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

[as above]

**Comment by messense** [comment]
workspace inheritance support was added in [maturin v0.13.4](https://github.com/PyO3/maturin/releases/tag/v0.13.4), please upgrade maturin first.

**Comment by max-sixty** [comment]
> workspace inheritance support was added in [maturin v0.13.4](https://github.com/PyO3/maturin/releases/tag/v0.13.4), please upgrade maturin first.

Bah, sorry, I had locally but missed that. Thanks.
