### ISSUE TITLE
maturin Crash Report

### ISSUE THREAD

**Issue by mladedav** [PyO3/maturin#1215]
### Bug Description

I have called maturin develop on a project which worked yesterday. Today I got the following:
```
🐍 Found CPython 3.9 at C:\Users\me\AppData\Local\pypoetry\Cache\virtualenvs\project-7O8z1RVd-py3.9\Scripts\python.exe
Well, this is embarrassing.
...
```

The report:
```
name = 'maturin'
operating_system = 'windows'
crate_version = '0.13.2'
explanation = '''
Panic occurred in file 'src\build_context.rs' at line 683
'''
cause = 'called `Option::unwrap()` on a `None` value'
method = 'Panic'
backtrace = '''

   0: 0x7ff6b67e8fb9 - <unresolved>
   1: 0x7ff6b685a215 - <unresolved>
   2: 0x7ff6b685a0bc - <unresolved>
   3: 0x7ff6b5eb2d7b - <unresolved>
   4: 0x7ff6b5eb3a85 - <unresolved>
   5: 0x7ff6b5ea915e - <unresolved>
   6: 0x7ff6b5f1e428 - <unresolved>
   7: 0x7ff6b5dfa1e4 - <unresolved>
   8: 0x7ff6b5dffc70 - <unresolved>
   9: 0x7ff6b5e0c8b6 - <unresolved>
  10: 0x7ff6b5e0ca4c - <unresolved>
  11: 0x7ff6b67d2831 - <unresolved>
  12: 0x7ff6b5e0a947 - <unresolved>
  13: 0x7ff6b682bbc0 - <unresolved>
  14: 0x7ffaf6de7034 - BaseThreadInitThunk
  15: 0x7ffaf82026a1 - RtlUserThreadStart'''
```

### Your Python version (`python -V`)

Python 3.9.1

### Your pip version (`pip -V`)

pip 22.0.4

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

I can't really tell.

I am using Poetry (and maturin is installed there) and after sleeping it didn't work. I exited the virtual environment and entered it again (without installing or updating anything and now the develop command works again.

**Comment by messense** [comment]
Please upgrade to 0.13.6 first, you are using 0.13.2. Feel free to reopen if it still occurs on 0.13.6.
