### ISSUE TITLE
support alternative implementations of CPython API

### ISSUE THREAD

**Issue by belm0** [PyO3/maturin#1230]
My problem is that a wheel generated by, for example`pyston3.8 -m pip wheel orjson`, has the wrong `implementation` and `abi` tags.  (_Pyston_ is a CPython fork with compatible API, but incompatible ABI.)  Having the wrong tags, the wheel can't be put into a package repository and be discovered properly.   (To be clear, install via `pyston3.8 -m pip install orjson` does install a correctly working package.  The issue reported here is about incorrect tags on the generated wheel file.)

As far as tagging of wheel files with `implementation` and `abi`, the maturin tool seems to only have specific, hard-coded support for CPython and PyPy implementations.

For example, here is a correctly tagged wheel file when compiling numpy with pyston:
```
$ pyston3.8 -m pip wheel numpy
--> numpy-1.23.4-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl
```
and here is the incorrectly tagged wheel file produced for orjson by maturin:
```
$ pyston3.8 -m pip wheel orjson
--> orjson-3.6.7-cp38-cp38-linux_x86_64.whl
```

The maturin seems to fall back to the tags of CPython, rather than use the information available in the pip / bdist / build environment.  (Perhaps it's a bug that maturin doesn't explicitly fail the build, rather than produce a wheel with the wrong tags.)

I'm hoping that maturin can deal with arbitrary API-compatible CPython implementations, without having a hard-coded, centralized interpreter mapping.  Aren't the true strings for `implementation` and `abi` available from the environment that invoked maturin?

https://github.com/PyO3/maturin/blob/297db1f693cc9f54159d35eb7748ca7fea477b94/src/python_interpreter/mod.rs#L285-L295

**Comment by messense** [comment]
Thanks for the report! I've never used pyston myself and don't have a use case for it in the foreseeable future, thus I don't have a strong motivation to add support for alternative interpreters other than CPython and PyPy.

That said, I'm happy to review and accept a patch to add support for it. If you don't want or don't have the time to contribute a patch, I'm also happy to implement it myself under a contract.

**Comment by belm0** [comment]
I don't know the maturin implementation well, but why is `InterpreterKind` necessary?

Can't maturin get the `implementation` and `abi` tag strings directly from the environment, so that it doesn't need to hard-code support for every variant of CPython?

Pyston is only one of many CPython forks which maintain API compatibility.  Just as `pip` can compile package source distributions into a wheel, even if it doesn't know about the fork, I hope maturin is able too...

**Comment by messense** [comment]
It's necessary to support effortless cross compilation, for example you don't need to build an `aarch64` Python 3.10 to cross compile, `maturin build -i python3.10 --target aarch64-unknown-linux-gnu` just works as long as you have the cross compilers. Maturin can infer `InterpreterKind` from `-i python3.10`. Otherwise it can be really complex, see https://crossenv.readthedocs.io/en/latest/quickstart.html

**Comment by messense** [comment]
Does rename the wheel to the correct platform tag work?

**Comment by messense** [comment]
PS: https://discuss.python.org/t/pep425-python-tag-for-pyston/13039

**Comment by belm0** [comment]
Renaming the wheel isn't sufficient, as the tags are also held internally in the metadata and paths within the archive.

**Comment by belm0** [comment]
> It's necessary to support effortless cross compilation

It seems like in order to support cross-compilation, the native compilation case becomes overly limited.

Native compilation case is the most common, considering the cases where the user is simply calling `pip install` or `pip wheel` and the wheel is not available.

For the common case of being called by `pip`, the python interpreter is always available, and it a least offers the correct `abi` string.  Perhaps maturin should fall back to this simple scheme when not cross compiling.

However, Pyston `platform.python_implementation()` returns `CPython`. 
 It's appears to be intentional, to avoid breaking some Python runtime code.  So in the end, a tool like maturin must have some awareness of Pyston.

```
$ pyston3.8
>>> import sysconfig
>>> sysconfig.get_config_var('SOABI')
'pyston-23-x86_64-linux-gnu'
>>> abi_tag = sysconfig.get_config_var('SOABI').replace('-', '_')
>>> is_pyston = abi_tag.startswith('pyston_')
>>> abi_tag, is_pyston
('pyston_23_x86_64_linux_gnu', True)

**Comment by messense** [comment]
> Native compilation case is the most common, considering the cases where the user is simply calling `pip install` or `pip wheel` and the wheel is not available.

I don't think so? Most users should install from prebuilt wheels.

> So in the end, a tool like maturin must have some awareness of Pyston.

Exactly.

**Comment by messense** [comment]
> Perhaps maturin should fall back to this simple scheme when not cross compiling.

I do agree with this, just need to implement it.

**Comment by belm0** [comment]
> So in the end, a tool like maturin must have some awareness of Pyston.
>> Exactly.

I still don't think I understand it completely.  Because `pip` and `setuptools` are able to produce the correct wheel, without having any knowledge of Pyston.  (For example, the pyston numpy build I mentioned in the original post.)

**Comment by messense** [comment]
I mean Pyston is pretending to be CPython, so we have to add some code to detect that it's actually not CPython and fallback to use `sysconfig`.

**Comment by messense** [comment]
> ```
> $ pyston3.8
> >>> import sysconfig
> >>> sysconfig.get_config_var('SOABI')
> 'pyston-23-x86_64-linux-gnu'
> >>> abi_tag = sysconfig.get_config_var('SOABI').replace('-', '_')
> >>> is_pyston = abi_tag.startswith('pyston_')
> >>> abi_tag, is_pyston
> ('pyston_23_x86_64_linux_gnu', True)
> ```

Currently it already uses the correct `SOABI`, the only thing wrong is the [PEP 425](https://peps.python.org/pep-0425/) platform tag `cp38-cp38-linux_x86_64`.

```
root@ubuntu:~/code/orjson/dist# unzip -l orjson-3.8.1-cp38-cp38-linux_x86_64.whl
Archive:  orjson-3.8.1-cp38-cp38-linux_x86_64.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
    47434  2022-11-01 06:26   orjson-3.8.1.dist-info/METADATA
       98  2022-11-01 06:26   orjson-3.8.1.dist-info/WHEEL
    10847  2022-11-01 06:26   orjson-3.8.1.dist-info/license_files/LICENSE-APACHE
     1023  2022-11-01 06:26   orjson-3.8.1.dist-info/license_files/LICENSE-MIT
      107  2022-11-01 06:26   orjson/__init__.py
      705  2022-11-01 06:26   orjson/__init__.pyi
        0  2022-11-01 06:26   orjson/py.typed
 12807424  2022-11-01 06:26   orjson/orjson.pyston-23-x86_64-linux-gnu.so
      740  2022-11-01 06:26   orjson-3.8.1.dist-info/RECORD
---------                     -------
 12868378                     9 files
root@ubuntu:~/code/orjson/dist# /root/pyston_2.3.5/bin/pyston3 -c 'import sysconfig; print(sysconfig.get_config_var("EXT_SUFFIX"))'
.pyston-23-x86_64-linux-gnu.so
```

**Comment by messense** [comment]
> Renaming the wheel isn't sufficient, as the tags are also held internally in the metadata and paths within the archive.

I just tried rename it and it works for me

```bash
root@ubuntu:~/code/orjson/dist# /root/pyston_2.3.5/bin/pyston3 -m pip install orjson-3.8.1-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl
Processing ./orjson-3.8.1-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl
Installing collected packages: orjson
Successfully installed orjson-3.8.1
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.1.1; however, version 22.3 is available.
You should consider upgrading via the '/root/pyston_2.3.5/bin/pyston3 -m pip install --upgrade pip' command.
root@ubuntu:~/code/orjson/dist# /root/pyston_2.3.5/bin/pyston3
Python 3.8.12 (remotes/origin/release_2.3.5:4b858b5062, Sep 25 2022, 18:56:33)
[Pyston 2.3.5, GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import orjson
>>> orjson.dumps({})
b'{}'
>>>
```

BTW, `pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64` this tag has duplicate `linux`/`x86_64` strings, I hope they will choose a cleaner one in the future.

**Comment by belm0** [comment]
> I just tried rename it and it works for me

There's a misunderstanding.  As I mentioned in the original post, this wheel can be installed and it does work.

The problem is that it has the wrong tags.  So if you put the wheel in a private package repository, it can't be discovered by pip, because the tags are wrong.  Renaming the file doesn't help in this case.

**Comment by belm0** [comment]
```
$ cat orjson-3.6.7.dist-info/WHEEL
Wheel-Version: 1.0
Generator: maturin (0.12.20)
Root-Is-Purelib: false
Tag: cp38-cp38-linux_x86_64

$ cat orjson-3.6.7.dist-info/RECORD | grep WHEEL
orjson-3.6.7.dist-info/WHEEL,sha256=FRSXE-_sDVSR8Ava7QJRwXGnw6seUCsGvxChI4GJqPw,99
```

**Comment by belm0** [comment]
after manual edit of the WHEEL and RECORD files of the archive, I was able to install from a package repository

```
(venv) # pip install orjson==3.6.7
Looking in indexes: https://pypi.org/simple, https://...@packagecloud.io/.../pypi/simple
Collecting orjson==3.6.7
  Downloading https://packagecloud.io/.../pypi/packages/orjson-3.6.7-pyston38-pyston_23_x86_64_linux_gnu-linux_x86_64.whl (270 kB)
Installing collected packages: orjson
Successfully installed orjson-3.6.7
```

**Comment by messense** [comment]
I think I have a quick fix in https://github.com/PyO3/maturin/pull/1232
