### ISSUE TITLE
macOS-12 built wheel incompatible with macOS-11, but Still has macosx_11_0 tag

### ISSUE THREAD

**Issue by Congyuwang** [PyO3/maturin#1247]
macOS-12 packaging environment gives `macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl`, which turns out incompatible with macOS 11 because of `Symbol not found` in `/usr/lib/libc++.1.dylib`.

I think perhaps wheels built on macOS-12 should be tagged `macosx_12_0`, and therefore not to be downloaded by pypi to macOS-11.

**Comment by messense** [comment]
I assume you have C++ dependencies? Then you should set `MACOSX_DEPLOYMENT_TARGET`, rustc uses `11.0`.

**Comment by messense** [comment]
Generating tag based on the dylib build version is pending on https://github.com/m4b/goblin/pull/341
