### ISSUE TITLE
Permission denied error in add_external_libs when libary is not writable by owner

### ISSUE THREAD

**Issue by vlaci** [PyO3/maturin#1287]
### Bug Description

The issue is that `patchelf` fails when invoked on the copy of the to-be-included library as the original permissions are retained and nothing guaranties that they are owner writable which is the case for all libraries on NixOS

Example:

```console
$ patchelf --set-soname libhs-19c0d7fc.so.5 /tmp/.tmpcBPM8J/libhs-19c0d7fc.so.5
patchelf: open: Permission denied
$ stat -c "Access: %a, UID: %u, GID: %g" /tmp/.tmpcBPM8J/libhs-19c0d7fc.so.5
Access: 555, UID: 1000, GID: 100
$ stat -c "Access: %a, UID: %u, GID: %g" /nix/store/l793dc6r9xagw7cfxv2w3bgwy9cy67yi-hyperscan-5.4.0/lib/libhs.so.5.4.0
Access: 555, UID: 0, GID: 0
```

I understand, there is an ongoing work to get rid of `patchelf`. In the meantime it could be mitigated by writing to a separate file via the `--output` flag of patchelf or fixing the permissions beforehand.

### Your Python version (`python -V`)

Python 3.8.15

### Your pip version (`pip -V`)

pip 22.2.2

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I guess it is enough to set permissions to e..g `555` of a library dependency which gets picked up by auditwheel

**Comment by messense** [comment]
Thanks for the report! I don't use Nix so I can't fix this, pull requests are welcome if anyone wants to fix it.

> I understand, there is an ongoing work to get rid of `patchelf`.

That's not going to happen in near future because it's a rather hard task.
