### ISSUE TITLE
Maturin build fails with --sdist, succeeds without

### ISSUE THREAD

**Issue by Bluesy1** [PyO3/maturin#1290]
### Bug Description

I was updating my project from maturing 0.13.7 to 0.14.1, and as such, i was trying to update my code to take advantage of some new things I noticed in the docs for maturin. 
When i was updating my `pyproject.toml` for my mixed python+rust project, i added the following lines, and after that trying to build with the `--sdist` flag fails, saying maturin crashed.
```toml
[tool.maturin]
python-source = "python"
```
[Generated report file](https://gist.github.com/Bluesy1/aaad6e5a48f61ad443a2a02b10b26e2d#file-report-cfe5041b-d2c0-4e4e-91a4-f5480aa86858-toml)

### Your Python version (`python -V`)

Python 3.11.0

### Your pip version (`pip -V`)

pip 22.3.1 

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Take a working mixed python rust project and add the folowing lines: 
```toml
[tool.maturin]
python-source = "python"
```
2. Observe maturin crashes when trying to build with the `--sdist` flag
[Generated output from adding `RUST_LOG=maturin=debug` to the front of the call](https://gist.github.com/Bluesy1/aaad6e5a48f61ad443a2a02b10b26e2d#file-log-txt)

**Comment by messense** [comment]
So the crashed code is https://github.com/PyO3/maturin/blob/3cfd8869dfec0ea1b9c7420329afd12712b16bd5/src/source_distribution.rs#L557

Is your code public that I can reproduce this issue from it?

**Comment by Bluesy1** [comment]
Done, https://github.com/Bluesy1/CharB0T/tree/refractor/rust-maturin-0.14/charbot_rust

**Comment by Bluesy1** [comment]
Thanks for the quick look and fix on this!
