### ISSUE TITLE
Reduce compile time when build maturin from source distribution

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#1306]
In such situation when maturin is built from source for reasons like no prebuilt wheel available, pep517 build only needs the `maturin pep517` subcommand, we don't need to waste time building lots of dependencies for features like `upload` that won't be used.

~~We should be able to detect PEP 517 isolated build environment by Python interpreter path, it will contain `build-env`:~~

~~* https://github.com/pypa/build/blob/4475cf1bf2362cfba8dd8b10ac97b42d066db502/src/build/env.py#L99~~
~~* https://github.com/pypa/pip/blob/5f3f592c4581a059ff9de0fb8052ef5c6ef25fd4/src/pip/_internal/utils/temp_dir.py#L19~~

Slow to compile dependencies:

* https://github.com/toml-rs/toml/issues/327
* uniffi_bindgen v0.21.0 | 5.3s

**Comment by konstin** [comment]
With this, there could be a case where that wheel ends in the cache, and when the user runs `pip install maturin` they always get the minimal instead of the proper one.

What would work would be a separate maturin-core package as build backend like poetry-core, though i'm not sure if the benefits outweigh the complexity; platforms without prebuilt maturin are rare and there's the wheel cache so it only needs to be built once

**Comment by messense** [comment]
> With this, there could be a case where that wheel ends in the cache, and when the user runs `pip install maturin` they always get the minimal instead of the proper one.

Good point, but IMO in this case they are unlikely to run `pip install maturin` directly since development usually happens on platforms with prebuilt wheels.

> What would work would be a separate maturin-core package as build backend like poetry-core, , though i'm not sure if the benefits outweigh the complexity

I also thought about this and came to the same conclusion.

I think adding a env var like `MATURIN_SETUP_ARGS` to `setup.py` might be a acceptable middle ground, now user can explicitly ask for a smaller maturin build, since they ask for it they will be warned about the pip cache issue and it's their responsibility to manage cache.

**Comment by messense** [comment]
On second thought, what if we just make bootstrap from sdist use `--no-default-features` by default? We'll still provide environment variable to customize features of course.

Most people should use prebuilt binary from PyPI or distro packaging channel, so bootstrap from sdist is often limited to

1. Distro packaging when they want to package the PEP 517 build backend. We provide environment variable to allow feature customization.
2. Install packages that use maturin as build backend on platforms that have no prebuilt wheel support. Use `--no-default-features` will be fastest, IMO the pip cache issue is not a big issue because even with `--no-default-features` it will still provides basic `build`, `develop` and `sdist` commands which is usually good enough for locally development.

**Comment by konstin** [comment]
yeah that sounds reasonable
