### ISSUE TITLE
Use SOURCE_DATE_EPOCH environment variable to set mtime of files in wheel

### ISSUE THREAD

**Issue by zmanji** [PyO3/maturin#1320]
Currently running `maturin build` does not have reproducible wheel output even if the input files have not changed. This can be observed by doing the following:

1. Running `maturin build`
2. Record the md5sum of the output wheel
3. Running the same `maturin build` command again without changing any of the python or rust files
4. Observe the md5sum of the output wheel is different

I noticed in my case it's because the `mtime` timestamp of the files in the wheel have been updated.

It would be great if `maturin` respected the `SOURCE_DATE_EPOCH` environment variable like wheel already does:
https://github.com/pypa/wheel/blob/70d8f7f5189fac0dfbf21b83adbd2781d2537c17/src/wheel/wheelfile.py#L26-L31

If this environment variable is set, it would be used to set the mtime of the files in the wheel, making the output reproducible. 

Having reproducibility is really handy for me because a build system may skip tasks if the wheel is the same.

I think the change would be as simple as adjusting https://github.com/PyO3/maturin/blob/6e7b02ffb043bced722d5b163f16ae10accdac17/src/module_writer.rs#L237-L241 to explicitly set the mtime.

**Comment by messense** [comment]
Pull requests are welcome.
