### ISSUE TITLE
cannot produce cdylib for ... as the target `x86_64-unknown-linux-musl` does not support these crate types

### ISSUE THREAD

**Issue by AnatolyBuga** [PyO3/maturin#1374]
Merry Christmas! Not sure if this is actually a bug (I am quite a noob) but anyway:

### Bug Description

**#15 14.78 error: cannot produce cdylib for `pyultima v0.0.1 (/app/pyultima)` as the target `x86_64-unknown-linux-musl` does not support these crate types**

### Your maturin version (`maturin --version`)

0.14.7

### Your Python version (`python -V`)

3.11

### Your pip version (`pip -V`)

22.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

When building a docker container:
```
FROM clux/muslrust:stable AS chef
USER root
RUN cargo install cargo-chef
WORKDIR /app
FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


FROM chef AS server_builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
RUN cargo build --release --bin server --features FRTB_CRR2 --target x86_64-unknown-linux-musl
```

After adding a new **pyultima** (which obviously dpeends on pyo3 and is a binding to my main crate) crate to my workspaces :
```
[workspace]
members = [
    'driver',
    'base_engine',
    'frtb_engine',
    'pyultima'
]
```

I get this error while building the container:
```
#15 14.78 error: cannot produce cdylib for `pyultima v0.0.1 (/app/pyultima)` as the target `x86_64-unknown-linux-musl` does not support these crate types
#15 14.79 thread 'main' panicked at 'Exited with status code: 101', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.50/src/recipe.rs:176:27
#15 14.79 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by messense** [comment]
Sorry, I don't see how this is related to maturin give that no `maturin` commands appeared in your `Dockerfile`.

**Comment by messense** [comment]
That said, standard musl targets in Rust only supports `cdylib` when compiled with `RUSTFLAGS='-C target-feature=-crt-static'`, see also https://rust-lang.github.io/rfcs/1721-crt-static.html
