### ISSUE TITLE
`maturin init/new` should validate the package name

### ISSUE THREAD

**Issue by not-my-profile** [PyO3/maturin#1398]
Package names of Rust libraries and package names of Python libraries both need to fulfill certain criteria. `maturin init/new` apparently currently doesn't check for any of these criteria e.g. `maturin init "foo bar"` works fine even though neither Rust nor Python support package names with a space.

I think ideally maturin would check the supplied name against two regexes (one for Rust package names and one for Python package names) and report which check failed in case the supplied name doesn't match.

Note that I think PyPI disallows certain package names like names of modules in the standard library ... it would be nice if maturin could check for these as well but that might not be easily doable (see also https://github.com/pypi/warehouse/pull/8533).

**Comment by messense** [comment]
Agreed it's nice to have, pull requests are welcome.

**Comment by messense** [comment]
@mahtantaoui No need to ask permission to work on issues, feel free to send pull requests, thanks!

**Comment by sanmai-NL** [comment]
See also: https://github.com/rust-lang/cargo/pull/12766

**Comment by alonme** [comment]
> Can we validate the package name using a combination of an approach similar to the one in [Cargo](https://github.com/rust-lang/cargo/blob/master/src/cargo/util/restricted_names.rs) for Rust names and the [constraint](https://github.com/pypi/warehouse/blob/main/warehouse/packaging/models.py#L168-L171) in PYPI for Python?

[permalink](https://github.com/pypi/warehouse/blob/8f79d90a310f0243ab15f52c41de093708a61dfd/warehouse/packaging/models.py#L211C9-L214C10) to the pypi/warehouse name constraint
