### ISSUE TITLE
proposal: Use sccache to replace rust-cache

### ISSUE THREAD

**Issue by Xuanwo** [PyO3/maturin#1424]
[Sccache](https://github.com/mozilla/sccache) now has the native GHA Cache services support, which means it can access cache from/to the GHA cache services directly.

By adopting sccache we can make our build faster:

- sccache only read/write needed caches during compile.
- sccache can reuse cache even when `Cargo.lock` changed.
- sccache can share cache over different workflows.

Here is my test over `Test (ubuntu-laster, 3.11)` on my fork:

## Current main branch (with rust-cache):

https://github.com/PyO3/maturin/actions/runs/3984744042/jobs/6831307652

- Test build: `Finished test [unoptimized + debuginfo] target(s) in 3m 20s`
- Whole workflow

![image](https://user-images.githubusercontent.com/5351546/214107687-26b1315f-7109-4d80-98f3-f8487d2efc18.png)

## First time run with sccache

- Test build: `Finished test [unoptimized + debuginfo] target(s) in 3m 50s`

## Second time run with sccache

https://github.com/Xuanwo/maturin/actions/runs/3988689309/jobs/6840397892

- Test build: `Finished test [unoptimized + debuginfo] target(s) in 2m 14s`
- Whole workflow

![image](https://user-images.githubusercontent.com/5351546/214107908-1806b25f-8a5d-48a7-ad79-834827ebf14e.png)

**Comment by messense** [comment]
Thanks! I'd like to try it on bors runs in pull request, it'll spawn lots of concurrent workflow jobs, let's see how it performs.

**Comment by Xuanwo** [comment]
> I'd like to try it on bors runs in pull request, it'll spawn lots of concurrent workflow jobs, let's see how it performs.

Hi, I'm not familiar with bors, can you tell me how to get this work started?

**Comment by messense** [comment]
Just open a pull request.
