### ISSUE TITLE
 error: could not compile `bitflags`

### ISSUE THREAD

**Issue by ManPython** [PyO3/maturin#1473]
### Bug Description

As on console log.

### Your maturin version (`maturin --version`)

0.14.12

### Your Python version (`python -V`)

Python 3.11.1

### Your pip version (`pip -V`)

23

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I'm installing via pip on LNX, 

'''
Collecting maturin
  Downloading maturin-0.14.12.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 kB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: maturin
  Building wheel for maturin (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for maturin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [293 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.freebsd-13.0-RELEASE-p12-amd64-cpython-311
      creating build/lib.freebsd-13.0-RELEASE-p12-amd64-cpython-311/maturin
      copying maturin/__init__.py -> build/lib.freebsd-13.0-RELEASE-p12-amd64-cpython-311/maturin
      copying maturin/import_hook.py -> build/lib.freebsd-13.0-RELEASE-p12-amd64-cpython-311/maturin
      copying maturin/__main__.py -> build/lib.freebsd-13.0-RELEASE-p12-amd64-cpython-311/maturin
      running egg_info
      creating maturin.egg-info
      writing maturin.egg-info/PKG-INFO
      writing dependency_links to maturin.egg-info/dependency_links.txt
      writing requirements to maturin.egg-info/requires.txt
      writing top-level names to maturin.egg-info/top_level.txt
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest file 'maturin.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'maturin.egg-info/SOURCES.txt'
      running build_ext
      running build_rust
      cargo build --manifest-path Cargo.toml --message-format=json-render-diagnostics --release -v --locked
          Updating crates.io index
       Downloading crates ...
'''

The log that showing problems:

[lgo_maturin.txt](https://github.com/PyO3/maturin/files/10700184/lgo_maturin.txt)

**Comment by messense** [comment]
Sorry, what is `LNX`?

> Caused by:
>        Resource temporarily unavailable (os error 35)

Make sure you have enough memory and free disk space.

**Comment by ManPython** [comment]
I have 35GB free, as remote host sared. LNX = Linux like WIN = WIndows.
Thats is strange.. confirming free space, other package can be installed. 
How many this need?

**Comment by messense** [comment]
> How many this need?

I'm not sure, it's a known issue that cargo uses lots of disk space when building: https://github.com/rust-lang/cargo/issues/7150

Not much we can do here other than #1337.

**Comment by ManPython** [comment]
Hmm
https://doc.rust-lang.org/cargo/commands/cargo-fix.html
