### ISSUE TITLE
Including package data with wheel

### ISSUE THREAD

**Issue by bicarlsen** [PyO3/maturin#1548]
### Bug Description

I'm not sure if this is a bug or a misunderstanding on my part, so please forgive me if the latter.

I have package data located in the `my_package.data/data` folder of my project. When building my package the data is correctly placed in the `target/wheels/my_package.data/data` folder. However, when I do a `pip install path/to/my_package.whl` the data is not installed with package. i.e. Running a [`importlib.resources.files('my_package')`](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) does not yield the correct location of the wheel (namely `target/wheel`), and the provided location does not contain the package data.

The end goal is to be able to get the package data. A related discussion is found in #1543.

### Your maturin version (`maturin --version`)

0.14.16

### Your Python version (`python -V`)

3.11.2/3.10.10

### Your pip version (`pip -V`)

23.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. `maturin build`
2. `pip install path/to/target/wheels/my_package.whl`
3. Try to load package data using `importlib.resources.files`

**Comment by messense** [comment]
I think you have confused [setuptools data files](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) with [wheel data files](https://peps.python.org/pep-0427/#the-data-directory)?

If you want setuptools style data files, you need to put them in the python part of a mixed Python/Rust project.

**Comment by messense** [comment]
cc @konstin

**Comment by bicarlsen** [comment]
> I think you have confused [setuptools data files](https://setuptools.pypa.io/en/latest/userguide/datafiles.html) with [wheel data files](https://peps.python.org/pep-0427/#the-data-directory)?

Ah yes, that was indeed the case. Thank you.
