### ISSUE TITLE
Maturin cannot handle python interpreter install by visual studio correctly

### ISSUE THREAD

**Issue by atiAkizuki** [PyO3/maturin#1569]
### Bug Description

error occur when run `maturin.exe build -f -r`
erro message is
 `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 123, kind: InvalidFilename, message: "文件名、目录名或卷标语法不正确。" }', src\python_interpreter\mod.rs:148:26`

look at the [source code](https://github.com/PyO3/maturin/blob/main/src/python_interpreter/mod.rs#L132),I found it may not consider python install by visual studio

That command will find this python interpreter install by visual studio,but I use conda env

```
(py311) PS E:\huang\python\STDF-Viewer-main\deps\rust_stdf_helper> cmd /c py --list-paths
Installed Pythons found by py Launcher for Windows
 -3.7-64        "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe" *

(py311) PS E:\huang\python\STDF-Viewer-main\deps\rust_stdf_helper> which python
python is in C:\Users\Administrator\.conda\envs\py311
```

### Your maturin version (`maturin --version`)

0.14.17

### Your Python version (`python -V`)

3.11.2

### Your pip version (`pip -V`)

23.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1.when install visual studio,select install python interpreter 
2.build this [project](https://github.com/noonchen/STDF-Viewer/tree/main/deps/rust_stdf_helper)

**Comment by messense** [comment]
Can you build with `-i python`?

**Comment by messense** [comment]
Closing as inactive.
