### ISSUE TITLE
Provide a way to disable rewriting path Cargo dependencies into local_dependencies/ folder

### ISSUE THREAD

**Issue by alex** [PyO3/maturin#1586]
Right now if you have a `{ path = ... }` dependency in `Cargo.toml`, `maturin` will rewrite it to live in `local_dependencies/`. I would like a way to disable this, and instead just handle things at their existing locations.

@messense has suggested that this might also fix https://github.com/PyO3/maturin/issues/1442

In terms of how to implement it, I can imagine two approaches:

1. add a `rewrite-path-dependencies = [true/false]` option in `pyproject.toml`
2. If the dependency is already included via `include` in `pyproject.toml`, then leave it as-is.

**Comment by messense** [comment]
I was thinking about adding a new "sdist generator". 

The current one can be called `cargo`, and we can add a new one called `git` that generate sdist based on `git ls-files` with respect to `include`/`exclude` options of `[tool.maturin]`.

What do you think?

**Comment by messense** [comment]
WIP in https://github.com/PyO3/maturin/pull/1587.
