### ISSUE TITLE
maturin v0.15.0 fails to build wheels for new project

### ISSUE THREAD

**Issue by monosans** [PyO3/maturin#1597]
### Bug Description

I created a new project with maturin v0.15.0 and it is failing to build in GitHub Actions for linux aarch64, armv7, s390x, ppc64le. Everything was fine with maturin v0.14.
See <https://github.com/monosans/test-maturin/actions/runs/4906427070>.

### Your maturin version (`maturin --version`)

0.15.0

### What bindings you're using

pyo3

**Comment by messense** [comment]
Thanks for the report! Should be fixed in #1598, a tiny typo in #1558 caused this.
