### ISSUE TITLE
Pass through/replicate cargo's --vcs option

### ISSUE THREAD

**Issue by stephenskory** [PyO3/maturin#1626]
It would be super useful for those of us that don't use git to be able to choose our vcs, or not use one at all, with `maturin new`. Bonus points if it also followed the `cargo-new.vcs` configuration value as explained below.

--vcs _vcs_

Initialize a new VCS repository for the given version control system (git, hg, pijul, or fossil) or do not initialize any version control at all (none). If not specified, defaults to git or the configuration value cargo-new.vcs, or none if already inside a VCS repository.

https://doc.rust-lang.org/cargo/commands/cargo-init.html

Thanks!

**Comment by messense** [comment]
We don't actually use any VCS at all in `maturin new` at the moment and we don't invoke `cargo new`.

**Comment by stephenskory** [comment]
Thanks for the reply. However, I'm confused, what's all this git litter, then, if you don't use any VCS?

```sh
(base) [sskory@Stephens-MBP:/tmp]%maturin new testing
✔ 🤷 Which kind of bindings to use? · pyo3
  ✨ Done! New project created testing
(base) [sskory@Stephens-MBP:/tmp]%cd testing
(base) [sskory@Stephens-MBP:/tmp/testing]%ls -a
.              .github (!)        Cargo.toml     src
..             .gitignore (!)     pyproject.toml
```

**Comment by stephenskory** [comment]
Right, there's no git repository in there, but there's still git litter, e.g. coming from https://github.com/PyO3/maturin/blob/main/src/templates/.gitignore.j2 I guess I am asking if it's possible to turn that off? Or add a command flag to ex/include it if desired? Or ask during `new` the same way bindings are queried? Or add the equivalent `.ignore` files for other VCSes (better to be inclusive)? I know cleaning up the litter is just a `rm -rf .git*` away, but that's annoying _each and every time_.

**Comment by messense** [comment]
Sorry if it bothers you that much. That said if it really bothers you that much, feel free to send a PR to implement `--vcs`.

**Comment by messense** [comment]
Closing for now because nobody cared enough to send a PR.
