### ISSUE TITLE
panic on bindings mismatch to manifest-dir

### ISSUE THREAD

**Issue by joshua-auchincloss** [PyO3/maturin#1632]
### Bug Description

maturin panics and does not recognize conditions where:
- pyproject.toml is used
- bindings are set
- manifest-path is set
- bindings dir does not exist in manifest

### Your maturin version (`maturin --version`)

1.0.0

### Your Python version (`python -V`)

3.10.2

### Your pip version (`pip -V`)

21.2.4

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. create src structure project
```
-> src
---> rust_a
------> Cargo.toml
------> src
--->rust_b
------> Cargo.toml
------> src
-> py_lib
```
2. in pyproject.toml
```
[tool.maturin]
python-source = "py_lib"
bindings = "bin" # does not exist
manifest-path = "src/rust_a/Cargo.toml"
module-name = "rust_a"
strip = true
exclude = [

]
```
3. `maturin build`

**Comment by messense** [comment]
Sorry I don't quite understand what you mean by `bindings = "bin" # does not exist`, can you provide a git repository for repro?
