### ISSUE TITLE
`uniffi-bindgen` required to be installed for `maturin` to work

### ISSUE THREAD

**Issue by heinrich5991** [PyO3/maturin#1658]
`uniffi-bindgen` needs to be installed in some way in order for `maturin` to work with `uniffi` bindings.

It'd be nice if the correct version of `uniffi-bindgen` could be used automatically, e.g. by adding a workspace crate like described in https://github.com/mozilla/uniffi-rs/blob/62979fa0899b74f29db48d715da20ea514e400fe/docs/manual/src/tutorial/foreign_language_bindings.md#multi-crate-workspaces.

Would something like this be interesting for this project?

**Comment by messense** [comment]
At the moment I've published pre-built `uniffi-bindgen` to pypi to improve build speed: https://github.com/messense/crate-wheels/blob/main/.github/workflows/uniffi-bindgen.yml, we can certainly also support the official documented method.

**Comment by heinrich5991** [comment]
That makes sense. I'm facing the problem that I can't use this, as my project needs the current `uniffi-bindgen` master.

**Comment by messense** [comment]
Now that uniffi released 0.24, I think you can use it?

**Comment by heinrich5991** [comment]
Yes. This problem no longer affects me as much.

**Comment by messense** [comment]
Will be fixed in #1729.

**Comment by heinrich5991** [comment]
Nice!
