### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#167]
"pyo3-pack" has become a misleading name for this project, as it can now equally package rust-cpython and cffi projects. Prior to the 0.7 release, I want to rename the project into something that better represents the current features, or at least to a neutral name.

**Comment by robertodr** [comment]
What about "pyrs-pack"? An unrelated question: is there a roadmap to a stable v0.7.0?

**Comment by konstin** [comment]
The roadmap is a) renaming the project b) testing publishing through ci c) write up some a nice explanation of the renaming and what PEP 517 means d) Publish 0.7. So just pinning `pyo3-pack==0.7.0-beta.10` should do fine in the meantime.

**Comment by robertodr** [comment]
Thank you!

**Comment by LuisAlejandro** [comment]
Hi @konstin ! Did you manage to write the explanation about the name change? I'm curious!
