### ISSUE TITLE
sdist is missing tests

### ISSUE THREAD

**Issue by mtelka** [PyO3/maturin#1674]
### Bug Description

The sdist package as PyPI is missing tests, although `noxfile.py` file is in the sdist.  Please add tests to sdist to make downstream testing easier.  Thank you.

### Your maturin version (`maturin --version`)

1.1.0

### Your Python version (`python -V`)

N/A

### Your pip version (`pip -V`)

N/A

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Dowload sdist from PyPI and unpack it.

**Comment by mtelka** [comment]
I'm packaging `maturin` for OpenIndiana and testing is something that could find incompatibilities either in the operating system or in the Python project.  This is especially valuable for not so common platforms like OpenIndiana.

**Comment by messense** [comment]
Thanks, I understand the benefits. I'm just not sure whether adding tests to sdist would work since it needs to be run by `cargo test`.

And why not using the github release `.tar.gz` source, for example https://github.com/PyO3/maturin/archive/refs/tags/v1.1.0.tar.gz? It contains all of the code.

**Comment by mtelka** [comment]
Github tarball is possible too, but it creates a bit more maintenance work because there is no simple way how to find the tarball automatically.  The sdist url is directly referenced from PyPI so it could be easily found without manual intervention.

BTW, if tests should be run using `cargo test` why there is `noxfile.py` file?

**Comment by messense** [comment]
`noxfile.py` is only for automating some Emscripten stuff.

**Comment by mgorny** [comment]
> And why not using the github release `.tar.gz` source, for example https://github.com/PyO3/maturin/archive/refs/tags/v1.1.0.tar.gz? It contains all of the code.

Git doesn't guarantee that the generated archives will be stable. There have already been cases in the past when changes in git or one of its dependencies suddenly caused all archives to change and broke all downstream consumers via checksum mismatches.

**Comment by messense** [comment]
I'm going to close this because we don't have any tests written in Python to distribute, and I'm removing `noxfile.py` from sdist in #1679.
