### ISSUE TITLE
entry_point missing from maturin published packages

### ISSUE THREAD

**Issue by xli1996** [PyO3/maturin#1690]
While looking to use `ruff` for bazel built projects, I found https://github.com/bazelbuild/rules_python/issues/1000#issuecomment-1402235394, which the discussion suggests that entry_point is missing from target list maybe because of maturin use `scripts` rather than `console_scripts`.

I am not familiar with rust environment, so I wonder if that is intended or there might be work around so that bazel project can rely on `rules_python + the entry_point macro` from pip-parse.

**Comment by messense** [comment]
> maybe because of maturin use `scripts` rather than `console_scripts`

Exactly. We don't want to use `console_scripts` for binary to avoid the cost of starting up a python interpreter.

See also https://github.com/PyO3/maturin/issues/1182
