### ISSUE TITLE
ARM64 MacOS (aarch64) wheels include non-zero minor version, which doesn't match pypa publishing

### ISSUE THREAD

**Issue by pechersky** [PyO3/maturin#1705]
On a github runner of OS `macos-latest`, the XCode version is 13.1:
```
$ xcodebuild -showsdks
[...]
macOS SDKs:
	macOS 13.1                    	-sdk macosx13.1
```

Running a `maturin build` builds a wheel with `13_1` in the name:
```
#     XCODE_VER: macosx13.1
#    SDKROOT: /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk
#    MACOSX_DEPLOYMENT_TARGET: 13.1
$ maturin build --bindings pyo3 --release --target aarch64-apple-darwin --strip --interpreter 3.11 -m packages/api/Cargo.toml
[...]
📦 Built wheel for CPython 3.11 to /Users/runner/work/foo/foo/target/wheels/foo-1.2.3-cp311-cp311-macosx_13_1_arm64.whl
```

This all seems fine, except for the fact that pypa publishing expects the wheel to be named something like `foo_1.2.3-cp311-cp311-macosx13_0_arm64.whl`. That is, `11_0`, `12_0`, or `13_0`. No minor version. The offending line is from:
https://github.com/pypa/packaging/blame/3030822b0b06a43fbbb2710da7b0846d1bebd2ba/src/packaging/tags.py#L438

Because of this, on our deploy machine, we have to rename the wheels to make downstream applications find these properly (matching on platform tags) so they can be installed.

In the `maturin` codebase, I believe this line would have to change.
https://github.com/PyO3/maturin/blob/3c3555e090efc79d31fb0172cdd785a05462bcd1/src/build_context.rs#L548

**Comment by messense** [comment]
You can explicitly set the SDK you want via `MACOSX_DEPLOYMENT_TARGET` or [maturin options](https://www.maturin.rs/config.html#target-specific-maturin-options) to ensure that it's actually built with the right SDK version.

**Comment by pechersky** [comment]
Thanks, that's really helpful. I guess I hadn't understood previously that `MACOSX_DEPLOYMENT_TARGET` would have only affected the output wheel name -- I thought there it had to be exactly the version available from the SDK. Specifically, on my machine, where there is only 13.1 SDK, I thought setting `MACOSX_DEPLOYMENT_TARGET=13.0` would have resulted in a failed build because of an SDK incompatibility. Turns out that's not the case. If possible, I think clarification in the documentation could help.

**Comment by messense** [comment]
See the `Base SDK and Deployment Target Settings` section of https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html.
