### ISSUE TITLE
Support type stubs for submodules

### ISSUE THREAD

**Issue by Tpt** [PyO3/maturin#1713]
Hi! Thank you again for Maturin! It's an amazing tool.

Currently, maturin auto-includes in the release artifacts (source and wheels) the type stubs if they are contained in a file named `my_module.pyi`([code](https://github.com/PyO3/maturin/blob/2fef1f6ed9870e907830e38d37fe0247f9cb973a/src/module_writer.rs#L781)). However, this does not work when the native module exposes submodules like `my_module.my_submodule` because stubs for the submodule should be included in an other stub file and not in the root module stub file. This file should be named `my_submodule.pyi` in the release artifacts, the root module stub staying in the `__init__.pyi` file.

A possible solution might be to also auto-include all the sub files following the `my_module/*.pyi` pattern. This way a project with a root module `my_module` and a submodule `my_submodule` might write its stubs in `my_module/__init__.pyi` (or just in `my_module.pyi`) for the root module and in `my_module/my_submodule.pyi` for the submodules.

@messense Does it sounds a good approach to you? I would be happy to contribute a PR if you think it's a sensible approach.

**Comment by messense** [comment]
IMO when you expose submodules in native module, using mixed Rust/Python project layout might be better?

**Comment by Tpt** [comment]
Thank you so much! Indeed, using mixed Rust/Python project layout is much better.
