### ISSUE TITLE
Having newlines in the dependency list leads to invalid `sdist` directory.

### ISSUE THREAD

**Issue by ritchie46** [PyO3/maturin#1732]
### Bug Description

See more info upstream here:

https://github.com/pola-rs/polars/pull/10473

and here:

https://github.com/pola-rs/polars/issues/10366

### Your maturin version (`maturin --version`)

1.2.0

### Your Python version (`python -V`)

3.10

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

...

**Comment by messense** [comment]
I've reproduced the issue with `toml_edit` only, submitted https://github.com/toml-rs/toml/issues/594.

**Comment by ritchie46** [comment]
Impressive turn around time! 🙌
