### ISSUE TITLE
Username and password flags are ignored in non-interactive mode

### ISSUE THREAD

**Issue by Shadow53** [PyO3/maturin#1736]
### Bug Description

When using the `maturin` CLI in Gitlab CI to upload wheels to GitLab PyPI, we are using the following command:

```
maturin upload --repository-url "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi" --username gitlab-ci-token --password  "${CI_JOB_TOKEN}" $WHEELS
```

But we get the error

```
🎛️ Running in non-interactive mode on CI
💥 maturin failed
  Caused by: Credentials not found and non-interactive mode is enabled
```

As best as I can tell, this is caused by [this bit of code](https://github.com/PyO3/maturin/blob/a8be6e0b9a37cc25691d1fc68c47871e5bdb75ea/src/upload.rs#L237) that will exit with an error if in non-interactive mode, without first checking if username and password were provided via CLI flags or env vars.

I think this should check if both are set (e.g. `if let (Some(username), Some(password)) = (username, password) {}` _before_ checking if in non-interactive mode.

For now, we are working around this by providing the username/password on CLI and setting `$CI` to something other than `true` (to work around `maturin` [auto-enabling non-interactive mode](https://github.com/PyO3/maturin/blob/a8be6e0b9a37cc25691d1fc68c47871e5bdb75ea/src/upload.rs#L66)), as it looks like we cannot use token-based auth with GitLab (all of the docs use username/password).

### Your maturin version (`maturin --version`)

1.2.1

### Your Python version (`python -V`)

3.9.17

### Your pip version (`pip -V`)

23.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Create a project on GitLab that uses Maturin
2. In CI, use `maturin build` to build one or more wheels
3. Attempt to upload to GitLab's Package Registry using the command provided above

**Comment by messense** [comment]
Thanks for the report, pull requests are welcome to fix this. Otherwise I'll find time to fix it later.

**Comment by BatmanAoD** [comment]
Thank you for the quick fix!
