### ISSUE TITLE
Trying to publish sdist only

### ISSUE THREAD

**Issue by FrankC01** [PyO3/maturin#1745]
### Bug Description

Getting error when using: `maturin publish --interpreter -r https://test.pypi.org/legacy/`

```bash
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.10
🐍 Not using a specific python interpreter
📡 Using build options features from pyproject.toml
💻 Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default
   Compiling pysui-fastcrypto v0.1.7 (/Users/fastfrank/frankc01/pysui-fastcrypto)
    Finished release [optimized] target(s) in 0.61s
📦 Built wheel for abi3 Python ≥ 3.10 to /Users/fastfrank/frankc01/pysui-fastcrypto/target/wheels/pysui_fastcrypto-0.1.7-cp310-abi3-macosx_11_0_arm64.whl
📦 Built source distribution to /Users/fastfrank/frankc01/pysui-fastcrypto/target/wheels/pysui_fastcrypto-0.1.7.tar.gz
💥 maturin failed
  Caused by: Failed to get registry https://test.pypi.org/legacy/ in .pypirc. Note: Your index didn't start with http:// or https://, which is required for non-pypirc indices.
 ```
 
 However; my .pypirc has:
 ```bash
 cat ~/.pypirc
[distutils]
index-servers =
    pypi
    testpypi

[pypi]
username = __token__
password = [valid password]
repository = https://upload.pypi.org/legacy/

[testpypi]
username = __token__
password = [valid password]
repository = https://test.pypi.org/legacy/
```

### Your maturin version (`maturin --version`)

1.2.3

### Your Python version (`python -V`)

3.11.4

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. As noted in bug description above

**Comment by messense** [comment]
`-r` is repository name not url, you should be using `-r testpypi` or `--repository-url https://test.pypi.org/legacy/`.

**Comment by FrankC01** [comment]
@messense I got that from one of the closed issuers. However changing it as you said got through but now my problem is I only want to publish the `sdist` and not the wheel.

**Comment by messense** [comment]
You can run `maturin sdist` then `maturn upload`.
