### ISSUE TITLE
Fails with "unsupported Python interpreter"

### ISSUE THREAD

**Issue by sauyon** [PyO3/maturin#1746]
### Bug Description

I'm on Arch linux; I guess the SOABI detection is failing somehow?

```
> maturin develop
...
💥 maturin failed
  Caused by: Unsupported Python interpreter: /home/sauyon/devel/bentoml/.venv/bin/python
```

```
>>> import distutils.sysconfig
>>> print(distutils.sysconfig.get_config_var('SOABI'))
cpython-38-x86_64-linux-gnu
```

### Your maturin version (`maturin --version`)

1.2.3

### Your Python version (`python -V`)

3.8.18 / 3.11.3

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- N/A

### Steps to Reproduce

1. Install maturin
2. `maturin init`
3. `maturin develop`

**Comment by messense** [comment]
Please try again with `RUST_LOG=maturin=debug maturin develop`.

**Comment by sauyon** [comment]
```
❯ RUST_LOG=maturin=debug maturin develop
📦 Including license file "/home/sauyon/devel/bentoml-workspace/bentoml/LICENSE"
💥 maturin failed
  Caused by: Unsupported Python interpreter: /home/sauyon/devel/bentoml-workspace/bentoml/.venv/bin/python
```

Didn't seem to change anything, that's odd...

**Comment by messense** [comment]
Can you make a minimal repro using docker?

**Comment by sauyon** [comment]
I've discovered the issue: I have `ARCHFLAGS` set in my dotconfig, as it's shared between my Arch box and my old MacOS laptop, and I didn't think that needed to be set. This causes maturin to detect my target-triple as `x86_64-apple-darwin`.

This enabled cross-compilation mode in development, which then uses [find_interpreter_in_sysconfig](https://github.com/PyO3/maturin/blob/061c0338dddc8e20cedc92a39add434c74f0e762/src/build_options.rs#L1121) with the detected interpreter path `.../.venv/python`, which obviously does not match any of the patterns and results in the error.

I can also reproduce this with `maturin build --release --target x86_64-apple-darwin --zig -i /usr/bin/python3.11`; that seems like a bug?

**Comment by messense** [comment]
> I can also reproduce this with `maturin build --release --target x86_64-apple-darwin --zig -i /usr/bin/python3.11`; that seems like a bug?

No, it doesn't make sense to pass a host Python interpreter when cross compiling because cross compiling requires target Python interpreter. 

`maturin` supports generating target Python interpreter sysconfig for major platforms so you can just use `maturin build --release --target x86_64-apple-darwin --zig -i python3.11`, notice that we are passing `python3.11` instead of an absolute path to Python.

**Comment by sauyon** [comment]
It seems to me like the `ARCHFLAGS` parsing belongs inside of the `None` case of `from_target_triple`; is there a reason it's outside, completely overriding the platform detection?

> No, it doesn't make sense to pass a host Python interpreter when cross compiling because cross compiling requires target Python interpreter.

The reason I thought it was a bug is that I hadn't looked into cross-compiling at all, but the `--help` gives:

```
 The python versions to build wheels for, given as the executables of interpreters such as `python3.9` or `/usr/bin/python3.8`
```

I think probably the error message could be improved?

I'd be happy to contribute for both the above if you think they're reasonable.

**Comment by messense** [comment]
Feel free to send PRs, we can discuss details in PR.
