### ISSUE TITLE
maturin fails if sitecustomize / usercustomize print to stdout

### ISSUE THREAD

**Issue by mbway** [PyO3/maturin#1750]
### Bug Description

while writing https://github.com/PyO3/maturin/pull/1748 I added a tip to add the call to `import_hook.install()` to [sitecustomize](https://docs.python.org/3/library/site.html) in order to have the import hook automatically active all the time. While debugging I had `print('installing import hook')` in `sitecustomize.py` as well and this caused `maturin build` to fail with an error that was not very descriptive: `Invalid python interpreter version`.

The root cause is that in `PythonInterpreter::check_executable` the `GET_INTERPRETER_METADATA` script exits successfully but parsing it fails because it has unexpected output at the beginning. This makes it fallback to using the interpreter name to determine the version, then failing because the `python3` executable version cannot be split into major, minor in `find_interpreter_in_sysconfig` which errors with `Invalid python interpreter version`.

This could be a case of wontfix / don't do that, but even so perhaps the error could be more informative. Even with `RUST_LOG=maturin=debug maturin build -vv` there is no additional information. A potential fix is to use the `-S` CLI flag to python to avoid loading site customizations when running these configuration scripts (the resulting output is identical in my testing). Adding that flag to `check_executable` the build gets further and fails on `failed to run custom build command for pyo3-build-config v0.19.2` so pyo3 may need to implement this same fix

### Your maturin version (`maturin --version`)

maturin 1.2.3

### Your Python version (`python -V`)

Python 3.11.3

### Your pip version (`pip -V`)

pip 22.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. create a virtual environment with `python3 -m venv venv`
2. activate the virtual environment `. venv/bin/activate`
3. create a `sitecustomize.py` script in site-packages that writes to stdout: `cd venv/lib/python*/site-packages && echo 'print("some output")' > sitecustomize.py && cd -`
4. create a new maturin project `maturin new --bindings pyo3 --name foo foo`
5. attempt to build the project: `cd foo && maturin build`

**Comment by messense** [comment]
> A potential fix is to use the `-S` CLI flag to python to avoid loading site customizations when running these configuration scripts (the resulting output is identical in my testing).

Sounds good, pull requests are welcome.


> Adding that flag to `check_executable` the build gets further and fails on `failed to run custom build command for pyo3-build-config v0.19.2` so pyo3 may need to implement this same fix

Make sense, cc @davidhewitt

**Comment by davidhewitt** [comment]
Is there any scenario where `-S` would break some edge use cases? A slightly more cautious option is to fail, retry with `-S`, and if that succeeds, fail with an error message and a hint to run with `PYTHONNOUSERSITE=1` env var set. That way the user knowingly disables their site if it's a problem.

(We could also set the env var rather than `-S` when retrying.)

PR is very welcome.

**Comment by messense** [comment]
> Is there any scenario where `-S` would break some edge use cases?

For https://github.com/PyO3/maturin/blob/main/src/python_interpreter/get_interpreter_metadata.py, I don't think anything would break.
