### ISSUE TITLE
Tox with PEP 517

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#176]
Tox fails when using pyo3-pack through PEP 517 due to https://github.com/tox-dev/tox/issues/1344.

**Comment by KeironO** [comment]
Would it be possible to get an estimate of how long it'll take for this to be fixed? If it's not high on your priority list, is there any way in which I can make a workaround for this?

**Comment by thedrow** [comment]
Now I have a new problem...
This is my pyproject.toml:
```toml
[build-system]
requires = ["maturin"]
build-backend = "maturin"
```

This is my tox.ini:
```ini
# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py35, py36, py37, pypy3
isolated_build = True

[testenv]
deps =
    pytest>=5.0
    pytest-benchmark
    hypothesis
commands =
    pytest -vvvv
```

When I try to invoke tox I get:
```
.package recreate: /home/omer/Documents/Projects/fastuuid/.tox/.package
.package installdeps: maturin
ERROR: invocation failed (exit code 1), logfile: /home/omer/Documents/Projects/fastuuid/.tox/.package/log/.package-2.log
=================================================== log start ===================================================
Traceback (most recent call last):
  File "/home/omer/.local/share/virtualenvs/fastuuid/lib/python3.7/site-packages/tox/helper/build_requires.py", line 7, in <module>
    backend = __import__(backend_spec, fromlist=[None])
ModuleNotFoundError: No module named 'maturin'

==================================================== log end ====================================================
ERROR: FAIL could not package project - v = InvocationError("/home/omer/Documents/Projects/fastuuid/.tox/.package/bin/python /home/omer/.local/share/virtualenvs/fastuuid/lib/python3.7/site-packages/tox/helper/build_requires.py maturin ''", 1)
```

The package can be installed and I'm using it to build the shared library as expected.
Any idea?

**Comment by konstin** [comment]
@thedrow I forgot to also rename the pyo3_pack directory which I've fixed in 04206b9df40f0f50f3fc6852037752a4f67bf151. With that commit the old error message should return.

**Comment by thedrow** [comment]
Can you release a new version?

**Comment by konstin** [comment]
It's already released

**Comment by davidhewitt** [comment]
FYI as of tox `3.18.1` the issue should be resolved in tox. From local testing when writing maturing examples for pyo3 I think we need #336 to be merged, and then we should be good to update the readme!

**Comment by konstin** [comment]
I've tested an it works now, however testing locally is tedious due to https://github.com/tox-dev/tox/issues/1634. I'll update the examples

**Comment by konstin** [comment]
@davidhewitt Thank you very much for fixing the original bug in tox!
