### ISSUE TITLE
Hash table capacity overflow on x86_64 FreeBSD

### ISSUE THREAD

**Issue by netchild** [PyO3/maturin#1769]
### Bug Description

===>  Building for py39-rpds-py-0.9.2
* Getting build dependencies for wheel...
* Building wheel...
Running `maturin-3.9 pep517 build-wheel -i /usr/local/bin/python3.9 --compatibility off`
 
===================================================================
maturin has panicked. This is a bug in maturin. Please report this
at https://github.com/PyO3/maturin/issues/new/choose.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 environment
variable set and include the backtrace in your report.
 
Platform: freebsd x86_64
Version: 1.2.0
Args: maturin-3.9 pep517 build-wheel -i /usr/local/bin/python3.9 --compatibility off
 
thread 'main' panicked at 'Hash table capacity overflow', /wrkdirs/usr/ports/devel/py-maturin/work-py39/maturin-1.2.0/cargo-crates/hashbrown-0.12.3/src/raw/mod.rs:90:40
stack backtrace:
   0:      0xe94ce7b9b64 - <unknown>
   1:      0xe94ce51bcbf - <unknown>
   2:      0xe94ce79ff30 - <unknown>
   3:      0xe94ce7b996f - <unknown>
   4:      0xe94ce7a0815 - <unknown>
   5:      0xe94ce7a021b - <unknown>
Error: command ['maturin-3.9', 'pep517', 'build-wheel', '-i', '/usr/local/bin/python3.9', '--compatibility', 'off'] returned non-zero exit status 101
 
ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1

### Your maturin version (`maturin --version`)

1.2.0

### Your Python version (`python -V`)

3.9.17

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

This is the result of trying to build the package py-rpds-py (as a dependency of something else) with Python 3.9 on FreeBSD.

**Comment by messense** [comment]
Can you reproduce it by running a debug version of `maturin` so we can get a backtrace with line information? Clone the repository and run

```bash
cargo run build -m <path to rpds-py Cargo.toml>
```

**Comment by messense** [comment]
FYI I'm unable to reproduce it on aarch64 FreeBSD 13.2, and I don't have a x86_64 machine so I can't investigate further.

**Comment by netchild** [comment]
I have no experience with cargo or maturin. A simple git clone of the maturin repo and "cargo run build ...." is enough?

Would it be ok to build a debug version of maturin out of the 1.2.0 release? If yes, how would I do that (something to add to the cargo build args?)? That would be easy for me, I could modify the FreeBSD port metadata (either by adding env variables for the build, or args for cargo, or patching files before the build) to generate the debug build inside the package building infrastructure and use it in the same way which generates the issue. If I simply install the prerequisites of maturin and rdps-py I will not have the same operation environment as the package building does (it runs in a very pristine environment, newly created for each build, every normal system is "polluted" compared to that).

**Comment by messense** [comment]
> A simple git clone of the maturin repo and "cargo run build ...." is enough?

Yes, provided you have rust installed.


> Would it be ok to build a debug version of maturin out of the 1.2.0 release?

Sure, probably just need to add `debug=True` to https://github.com/PyO3/maturin/blob/c30d01ac9a9c60c970887748eac03f0d7c4bdb02/setup.py#L68

```python
RustBin("maturin", args=cargo_args, cargo_manifest_args=["--locked"], debug=True)
```

**Comment by netchild** [comment]
[py39-rpds-py-0.9.2.log](https://github.com/PyO3/maturin/files/12565429/py39-rpds-py-0.9.2.log)

This is the complete build log with the debug version of maturin. The backtrace is at the end.

**Comment by messense** [comment]
Thanks, the backtrace points the panic to deserialization of `pyproject.toml` with [toml_edit](https://crates.io/crates/toml_edit), which might indicates bug in `toml_edit` so it's not directly fixable in maturin.

Can you also try the main branch using `cargo run build -i /usr/local/bin/python3.9 -m <path to rpds-py Cargo.toml>` to see if it also occurs on main?

**Comment by netchild** [comment]
How do you create an official release from the git repo? I would like to generate a file like an official release to be able to use it inside the package building infrastructure. This way I can be sure I have the same execution environment.

**Comment by messense** [comment]
You can run `maturin sdist` (using maturin 1.2.x) on main branch to generate a source distribution for maturin itself.

**Comment by netchild** [comment]
Yes, the main branch as of today has the same problem. At the same time we noticed a bug in some string functions in FreeBSD (they got a SIMD optimisation recently). A fix affecting very long buffer sizes for memchr() to FreeBSD was committed yesterday. As toml is a string-heavy thing, it looks to me the likelyhood of this bug affecting toml is >0... at least it is worth a look to check if it is causing this.

I think we can close this issue, as it is in a depdendency of maturin.

**Comment by netchild** [comment]
I found the issue which caused this.
I do a cross-build of maturin for another system. The build system is an Intel Xeon. The target system is a slow AMD Athlon system. I compile for the target with cputype amdfam10 and with -fvectorize. maturin (with target amdfam10 and -fvectorize) is then run in the build on the Intel build system. If I exclude the cputype and the vecotirizing switch for the maturin build, the use of it on the build system works. I have not tested if only not using one of those is enough.

So this is a compiler options + CPU arch issue, not really a code issue.
