### ISSUE TITLE
Generated source distribution does not handle aliased dependencies correctly

### ISSUE THREAD

**Issue by 0xbe7a** [PyO3/maturin#1781]
### Bug Description

`maturin sdist` does not handle "aliased" dependencies of workspaces correctly:

I have a package `py_adder` which is the only member of a workspace (Link to a repository containing the full minimal reproducible example is at the end).
The workspaces `Cargo.toml` looks like this:

```
[workspace]
members = [
  "py-adder"
]

[workspace.dependencies.backend]
package = "adder_backend"
version = "0.1.0"
path = "adder_backend"
```

`adder_backend` is just a minimal library containing a single function `add`.

`adder_backend`s `Cargo.toml` looks like this:
```
[package]
name = "adder_backend"
version = "0.1.0"
edition = "2021"
```

My package `py-adder` uses this backend like this:

```
[dependencies]
backend = { workspace = true }
```

When running `maturin build` or `maturin develop` inside the `py-adder` folder everything works as expected and the functions can be used by python.

We can also build the source distribution by running `maturin sdist` inside the `py-adder` folder.

However, when trying to run `maturin build` inside the extracted source distribution folder we get:

```
error: no matching package named `backend` found
location searched: /private/tmp/source_code/adder-0.1.0/local_dependencies/backend
required by package `adder v0.1.0 (/private/tmp/source_code/adder-0.1.0)`
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error:
```

Which is expected, as the `Cargo.toml` inside folder `local_dependencies/backend` declares a package called `adder_backend` and we are looking for `backend`.

We recently hit this bug in polars https://github.com/pola-rs/polars/issues/11371.

I compiled a repository containing a minimal reproducible example: https://github.com/0xbe7a/maturin-dependeny-rename-mre

### Your maturin version (`maturin --version`)

maturin 1.2.3

### Your Python version (`python -V`)

Python 3.11.5

### Your pip version (`pip -V`)

pip 23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Clone https://github.com/0xbe7a/maturin-dependeny-rename-mre
2. `cd py-adder`
3. Run `maturin develop` and observe that everything works as expected
4. Run `maturin sdist`
5. Extract the source distribution into a new folder
6. Run `maturin build` inside the new folder containing the extracted source

**Comment by messense** [comment]
Thanks for the report, can you try matruin main branch to see whether #1741 has fixed it already?

**Comment by 0xbe7a** [comment]
```
➜  adder-0.1.0 tree
.
├── PKG-INFO
├── adder_backend
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── py-adder
│   ├── Cargo.lock
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
└── pyproject.toml

5 directories, 7 files
➜  adder-0.1.0 cat py-adder/Cargo.toml 
[package]
name = "adder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "adder"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
backend = { workspace = true }

[dependencies.pyo3]
version = "0.18.0"
features = ["abi3-py37"]
➜  adder-0.1.0 cat adder_backend/Cargo.toml 
[package]
name = "adder_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
➜  adder-0.1.0 maturin build
error: failed to parse manifest at `/private/tmp/source_code/adder-0.1.0/py-adder/Cargo.toml`

Caused by:
  error inheriting `backend` from workspace root manifest's `workspace.dependencies.backend`

Caused by:
  failed to find a workspace root
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error: 
➜  adder-0.1.0
```

**Comment by messense** [comment]
For your repor, if you remove `py-adder/Cargo.lock` it should work? I'm not sure why/how you created that file in the first place, the canonical lock file for the workspace should be the top level `Cargo.lock`.

**Comment by 0xbe7a** [comment]
In polars the equivalent of py-adder was not part of the workspace, however while minimizing the example i realized that this is not required to trigger the behaviour.

Here is the commit where i moved py-adder into the workspace https://github.com/0xbe7a/maturin-dependeny-rename-mre/commit/bcd5b48d7a42afd59dc6973b76576c628ba61d57

When i remove `py-adder`s invalid `Cargo.lock` the latest maturin from `main` works perfectly, 1.2.3 is still broken ! 😄
Would you mind releasing the new `sdist` implementation?

**Comment by messense** [comment]
> Would you mind releasing the new `sdist` implementation?

I'll probably release a new version next week.
