### ISSUE TITLE
Allow offline mode via environment variable

### ISSUE THREAD

**Issue by theCapypara** [PyO3/maturin#1784]
Hello! I'm trying to publish an app using Flatpak. Flatpak works with completely offline builds where all artifacts are pre-fetched and no internet connection is available in the build environment,

At the moment (as far as I can tell) `maturin` only supports offline mode via the `maturin` CLI. This is very tedious to setup in such a build environment, and there seems to be no way to pass this flag using normal pip or other packaging tool installations. As such I'm currently forced to write rather complicated workarounds to install maturin and run it for every module that requires it.

It would be great if offline mode could be enforced using an environment variable, ideally one shared with Setuptools Rust, see this issue:
https://github.com/PyO3/setuptools-rust/issues/363

**Comment by messense** [comment]
You can use `pip install --config-settings build-args='--offline'`.

**Comment by theCapypara** [comment]
Thanks, is this documented anywhere? I went through the documentation and found nothing of the sorts.

**Comment by messense** [comment]
No, pull requests are welcome to document it.

See also https://github.com/PyO3/maturin/pull/1619.

**Comment by theCapypara** [comment]
Thank you. For reference, the following command works in a Flatpak:
```
. /usr/lib/sdk/rust-stable/enable.sh && cp /app/whl_tmp/tomli-2.0.1-*.whl . && cp /app/whl_tmp/maturin-1.2.3-cp310-cp310-*.whl . && pip3 wheel --verbose --exists-action=i --no-index --find-links=\"file://${PWD}\" --config-settings build-args='--offline' \"./rpds_py\" -w /app/whl_tmp```

It must be noted that Maturin and tomli must be pre-built in a preceding module, because `maturin` itself currently needs to be patched due to https://github.com/PyO3/setuptools-rust/issues/363

**Comment by theCapypara** [comment]
@messense Could we reopen this issue? There is still one problem left with this approach:

With this solution I need to manually run maturin for each dependency in my dependency tree and use the `--ofline` flag. It's not possible to install maturin projects via pip in environments without internet connection.

This is very undesirable as this creates a big overhead in Flatpak manifests. It would be much better if Matturin would also honor the `CARGO_OFFLINE` environment variable, see the discussion here: https://github.com/PyO3/setuptools-rust/issues/363
