### ISSUE TITLE
`build` command ignores `build-system.requires` specifier

### ISSUE THREAD

**Issue by stinodego** [PyO3/maturin#1792]
### Bug Description

My `pyproject.toml` contains the following snippet:

```toml
[build-system]
requires = ["maturin==1.2.1"]
build-backend = "maturin"
```

I have the latest maturin installed (`1.2.3`). This does not match the build requirement. Yet the build still completes without any issue.
I have tried different combinations of version specifiers (minimum, maximum, exact versions), but I cannot get the build to fail.

I would expect an error to be thrown.

### Your maturin version (`maturin --version`)

1.2.3

### Your Python version (`python -V`)

3.11.2

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Set the `build-system.requires` entry to not match the installed version of maturin, then run `maturin build`.

**Comment by messense** [comment]
pip will take care of that in a pep517 build process. In the case of invoking maturin executable directly we don't check it.

**Comment by konstin** [comment]
I think we should show a warning, it's easy enough to implement

**Comment by messense** [comment]
Sure, pull requests are welcome.

**Comment by stinodego** [comment]
For some context, I am building wheels in my CI using the `maturin-action`. It uses the latest version of maturin by default, which is fine, but I was trying to constrain the version to some range by using the `pyproject.toml` setting.

I have other ways to achieve this, of course, but I thought I'd report this as unexpected behavior.

**Comment by messense** [comment]
maturin-action should install the constrained version by default: https://github.com/PyO3/maturin-action/pull/46

**Comment by stinodego** [comment]
In that case, I think there is a bug in `maturin-action`. It installed `1.2.3` even though I specified `build.system.requires = ["maturin==1.2.1"]`.

**Comment by messense** [comment]
Make sure you didn't override the version by passing maturin-version  to the action.

**Comment by stinodego** [comment]
I will make a reproduction and link the GitHub Action run, give me a second!

**Comment by stinodego** [comment]
See this PR, where I remove the version passed to `maturin-action` and pin the maturin version in `pyproject.toml`:
https://github.com/stinodego/polars/pull/84

Check the `release` workflow, which has a step "Build wheel". You can see under the "Install maturin" step that version `1.2.3` was installed:
https://github.com/stinodego/polars/actions/runs/6378845249/job/17310201145?pr=84

**Comment by messense** [comment]
Probably because it didn't compute the right `manifestDir`: https://github.com/PyO3/maturin-action/blob/c0df5c7c31c0de2ce619ec14f9a9cc0e8e0beaa1/src/index.ts#L195

I'll take a look later.

**Comment by messense** [comment]
Opened https://github.com/PyO3/maturin-action/issues/212 to better track this problem.
