### ISSUE TITLE
`MACOSX_DEPLOYMENT_TARGET` causing spurious rebuilds due to `objc-sys`

### ISSUE THREAD

**Issue by emilk** [PyO3/maturin#1804]
Running `maturin develop` [will set the](https://github.com/PyO3/maturin/blob/8d4b482fe1f434dc41f5ee4a49d7684e02a5c33b/src/compile.rs#L422-L446) `MACOSX_DEPLOYMENT_TARGET` environment variable. The `objc-sys` crate has [a `build.rs` file](https://github.com/madsmtm/objc2/blob/2ad20c34599b51fc7aff3f78d1c20b7b6752562e/crates/objc-sys/build.rs#L107-L109) that rebuilds if `MACOSX_DEPLOYMENT_TARGET` changes.

The problem comes from me then running a normal `cargo build`, which _doesn't_ set `MACOSX_DEPLOYMENT_TARGET`. Now `objc-sys` and all its dependencies (a lot of them, including `winit`) will rebuild. When I type `maturing develop` again, everything rebuilds yet again.

One solution is to set `MACOSX_DEPLOYMENT_TARGET=11.0` globally in my `~/.zshrc`, but I'd like for a more solid solution that works for any contributor to my repository.

I initially though that adding `MACOSX_DEPLOYMENT_TARGET="11.0"` under `[env]` in `.cargo/config.toml` would solve it, but those env-vars seems to only be visible to `build.rs` files inside my repository, and hence not by `objc-sys/build.rs`.

So now I'm wondering - can we have an option so that Maturin does NOT set `MACOSX_DEPLOYMENT_TARGET`, at least not when running `maturin develop`? What would be the effect of not setting it?

**Comment by messense** [comment]
It should be fine to not set `MACOSX_DEPLOYMENT_TARGET` for `maturin develop` but for distribution (`maturin build`) we need to set it otherwise the wheel built on newer macOS version may not work on older macOS versions.
