### ISSUE TITLE
Recommend install via `pipx`?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin#1857]
These days I find myself adding all CLI tools globally using `pipx` rather than in individual environments. Should we update the user guide to recommend installing using `pipx`?

**Comment by konstin** [comment]
Normally i'd say dev tool versions should be managed by project dependencies, but since we're lacking both a standardized tool to edit the dev dependencies and a standardized lockfile format i'm all for pipx over plain pip
