### ISSUE TITLE
Cargo xwin configutation to download sdks and headers for target arch only.

### ISSUE THREAD

**Issue by kivsiak** [PyO3/maturin#1864]
I  need to build x86_64 library. 

 > maturin build  --release --target x86_64-pc-windows-msvc  -i python3.10

All going fine. A got my wheel. But when i deploy it to CI i found my builds are extremely slow.  Investigating i found that xwin download and splat ALL possible variants of headers and sdk. While i need  only x86_64.

I found that XWIN_VARIANT, XWIN_ARCH, as other xwin env variables  does nothing.  
 
There should be way to narrow download arch according build target

**Comment by messense** [comment]
Pull requests are welcome.

**Comment by messense** [comment]
> I found that XWIN_VARIANT, XWIN_ARCH, as other xwin env variables does nothing.

These env vars works now thanks to https://github.com/PyO3/maturin/pull/1961
