### ISSUE TITLE
maturin build fails on CentOS 7

### ISSUE THREAD

**Issue by apepkuss** [PyO3/maturin#1884]
### Bug Description

I am using `PyO3` and `maturin` to prototype a project, in which I'd like to load a plugin, a `.so` file. When I use `maturin develop` or `maturin develop -r` to build and deploy the wheel, it works well and can print the count `1` and the name `wasi_nn` of the plugin library in the Python environment. When I use `maturin build`, however, it seems to not "find" the plugin library, printing the count `0`. I did the test in `CentOS Linux release 7.9.2009 (Core)`. Even though I did some investigations on it, I failed to find a way to solve it. Does anyone know what causes the issue and how to fix it? Thanks a lot!

### Your maturin version (`maturin --version`)

1.4.0

### Your Python version (`python -V`)

Python 3.10.13

### Your pip version (`pip -V`)

pip 23.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

The steps to reproduce the issue:

- Git clone test code

  Git clone test code and put it into a directory named, for example, `workspace`:
  ```bash
  cd workspace
  git clone https://github.com/apepkuss/load_plugin.git
  ```

  Docker pull `wasmedge/wasmedge:manylinux2014_x86_64`

  ```bash
  docker run --name="test-plugin" -it -v $HOME/workspace/:/root/workspace wasmedge/wasmedge:manylinux2014_x86_64
  ```

The steps below are run in the docker container:

- Download library file

  In the docker container, download and unzip the library file:

  ```bash
  cd load_plugin

  # download .so file
  curl -LO https://github.com/WasmEdge/WasmEdge/releases/download/0.13.5/WasmEdge-plugin-wasi_nn-ggml-0.13.5-manylinux2014_x86_64.tar.gz

  # unzip
  tar -xf WasmEdge-plugin-wasi_nn-ggml-0.13.5-manylinux2014_x86_64.tar.gz
  
  # set LD_LIBRARY_PATH
  export LD_LIBRARY_PATH=/root/workspace/test/load_plugin:$LD_LIBRARY_PATH
  ```
- Install WasmEdge Runtime
  ```bash
  curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.5
  ```
- Set up Python environment
  - Create a virtual environment
    ```bash
    cd load_plugin
    
    # create virtual env
    /opt/python/cp310-cp310/bin/python -m venv .env

    # activate env
    source .env/bin/activate
    ```

  - Install dependencies
    ```bash
    pip install maturin patchelf
    ```

- Build with `maturin develop`
 
  - Build 
    ```bash
    maturin develop -r
    ```

  - Test
    ```bash
    (.env) [root@277f2e649aad load_plugin]# python
    Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import load_plugin
    >>> load_plugin.run()
    Hello, world!
    Plugin count: 1
    Plugin names: ["wasi_nn"]
    ```

- Build with `maturin build` (Failed)
  
  - Uninstall the `load_plugin` package if there is one installed
    ```bash
    # uninstall `load_plugin` installed by `maturin develop`
    pip uninstall load_plugin
    ```

  - `maturin build` the `load_plugin` wheel:
    ```bash
    maturin build --compatibility manylinux2014 -i /root/workspace/test/load_plugin/.env/bin/python -r -o dist
    ```

  - Install the wheel
    ```bash
    pip install dist/load_plugin-0.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    ```

  - Test
    ```bash
    (.env) [root@277f2e649aad load_plugin]# python
    Python 3.10.13 (main, Dec  5 2023, 08:22:38) [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import load_plugin
    >>> load_plugin.run()
    Hello, world!
    Plugin count: 0
    Plugin names: []
    >>> 
    ```

**Comment by messense** [comment]
> * Build with `maturin build` (Failed)

I don't see any failure that's directly related to maturin since the wheel is correctly built, the plugin load failure seems like a user code or runtime environment issue.

Closing because nothing we can fix in maturin here.

**Comment by apepkuss** [comment]
@messense Thanks for your reply. As I mentioned above, when I use `maturin develop`, the wheel works and prints out

```bash
Hello, world!
Plugin count: 1
Plugin names: ["wasi_nn"]
```

However, when I use `maturin build` and install the wheels manually, it fails to print the same info as before:

```bash
Hello, world!
Plugin count: 0
Plugin names: []
```

No change happened between these two compilations. So I don't know why the wheels built with `develop` and `build` behave differently.

**Comment by messense** [comment]
I've investigated a bit, IMO the wasmedge C API didn't not expose any error status in `WasmEdge_PluginLoadFromPath` makes it hard to look further.

https://github.com/second-state/wasmedge_plugin_rust_sdk/blob/22fab4633bd8b0b653da98a00c5c267ba1924337/wasmedge_sys_ffi/src/ffi.rs#L1819

It definitely has hit some error condition but without proper error reporting, you're better investigate by yourself because I'm not using WasmEdge and I'm not interested in debugging by reading a lot of WasmEdge ffi code.

**Comment by apepkuss** [comment]
Thank you for the help. I'll check the issue further.
