### ISSUE TITLE
uniffi-bindgen verion 0.26 not supported

### ISSUE THREAD

**Issue by itrumper** [PyO3/maturin#1925]
### Bug Description

Verion 0.26 of the python package [uniffi-bindgen](https://pypi.org/project/uniffi-bindgen/#history) fails when using `maturin develop` on executing the line `Running cd "/Users/isaac/Documents/uniffi" && "uniffi-bindgen" "generate" "--no-format" "--language" "python" "--out-dir" "/Users/isaac/Documents/target/maturin/uniffi" "--library" "/Users/isaac/Documents/target/debug/libuniffi_test.dylib"`

The output from the logs is:
```bash
called `Result::unwrap()` on an `Err` value: Invalid string data

Caused by:
    invalid utf-8 sequence of 1 bytes from index 433

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: uniffi_meta::reader::MetadataReader::read_optional_long_string
   2: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: uniffi_meta::reader::MetadataReader::read_metadata
   5: uniffi_meta::Metadata::read
   6: uniffi_bindgen::macro_metadata::extract::ExtractedItems::extract_item
   7: uniffi_bindgen::macro_metadata::extract::extract_from_macho
   8: uniffi_bindgen::macro_metadata::extract::extract_from_bytes
   9: uniffi_bindgen::library_mode::generate_bindings
  10: uniffi::cli::run_main
  11: uniffi::uniffi_bindgen_main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal
  15: std::rt::lang_start
  16: _main
stack backtrace:
   0:        0x102c9bc90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h298c9ab285ff3934
   1:        0x102cb8d84 - core::fmt::write::h4e276abdb6d0c2a1
   2:        0x102c99948 - std::io::Write::write_fmt::hd421848f5f0bf9d0
   3:        0x102c9bacc - std::sys_common::backtrace::print::hd8bd9ecab1f94b94
   4:        0x102c9d080 - std::panicking::default_hook::{{closure}}::h520eeb743fc98fb4
   5:        0x102c9cdc8 - std::panicking::default_hook::ha6550ffe49b63df1
   6:        0x102c9d4a8 - std::panicking::rust_panic_with_hook::hddb0e884a202de7c
   7:        0x102c9d3a8 - std::panicking::begin_panic_handler::{{closure}}::hd2798398a2fd9077
   8:        0x102c9c0f8 - std::sys_common::backtrace::__rust_end_short_backtrace::h9201cc364dbb8a23
   9:        0x102c9d144 - _rust_begin_unwind
  10:        0x102ccdfb8 - core::panicking::panic_fmt::h4d5168028d4c43c7
  11:        0x102cce310 - core::result::unwrap_failed::hc60ef978ea39e1b4
  12:        0x102a7feec - uniffi::uniffi_bindgen_main::h17c62a64cad14515
  13:        0x102a6cfcc - std::sys_common::backtrace::__rust_begin_short_backtrace::h732e317edce12f32
  14:        0x102a6d01c - std::rt::lang_start::{{closure}}::hfd7e34874c82e7a3
  15:        0x102c93958 - std::rt::lang_start_internal::h5b246d44f1526226
  16:        0x102a6d000 - std::rt::lang_start::h7cca6e765f70e2de
  17:        0x102a6d06c - _main
```

### Your maturin version (`maturin --version`)

1.4.0

### Your Python version (`python -V`)

3.11.3

### Your pip version (`pip -V`)

23.1.2

### What bindings you're using

uniffi

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Create basic uniffi project and use the latest uniffi-bindgen package.

### Work Around

Uninstalling uniffi-bindgen via `pip uninstall uniffi-bindgen` and then specifying the version `pip install uniffi-bindgen==0.25.2` resolves the issue. Therefore, something in the latest release is not compatible with maturin.

**Comment by itrumper** [comment]
I also have been running into an issue using the work-around where `maturin build` cannot find the dylib (I'm on macOS) built by uniffi because the library built is called `libuniffi_uniffi_test`, which I can see when I unpack the wheel after running `pip install .` This doesn't match with the command above, which is pulling the correct dylib from the target directory, so I'm not sure what is going on here. I will try and create a MWE repo for this issue, but again, I'm having trouble because it seems that `maturin new -b uniffi` uses a UDL file, while I'm using their proc macros and v0.26 of the uniffi crate.

I have found another work-around for this issue, which is to first call `maturin develop`, which generates an additional module within my python directory with the incorrectly named dylib. I then re-name the dylib manually to what it is supposed to be (`libuniffi_test.dylib`), and then run `maturing build` and `pip install .`. This somehow collects the "correct" library.

I think this is also related to the fact that I get an `ImporError` when using `maturin develop`. Again, I apologize for the lack of a MWE, but as you can tell, there is a lot of complexity to this issue! I'll keep digging and report back.

**Comment by mbway** [comment]
I also ran into this incompatibility but on my machine (Arch Linux) the build suceeds but fails to load. For example installing `test-crates/uniffi-mixed` from the maturin repo and running `python test-crates/uniffi-mixed/check_installed/check_installed.py`

```
Traceback (most recent call last):
  File "maturin/test-crates/uniffi-mixed/check_installed/check_installed.py", line 3, in <module>
    import uniffi_mixed
  File "maturin/test-crates/uniffi-mixed/uniffi_mixed/__init__.py", line 1, in <module>
    from .uniffi_mixed import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "maturin/test-crates/uniffi-mixed/uniffi_mixed/uniffi_mixed/__init__.py", line 1, in <module>
    from .math import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^
  File "maturin/test-crates/uniffi-mixed/uniffi_mixed/uniffi_mixed/math.py", line 766, in <module>
    _uniffi_check_contract_api_version(_UniffiLib)
  File "maturin/test-crates/uniffi-mixed/uniffi_mixed/uniffi_mixed/math.py", line 476, in _uniffi_check_contract_api_version
    raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
uniffi_mixed.uniffi_mixed.math.InternalError: UniFFI contract version mismatch: try cleaning and rebuilding your project
```
The error is triggered by `bindings_contract_version = 25` and `scaffolding_contract_version = 24`

after installing `uniffi-bindgen==0.25.0` after rebuilding `check_installed.py` prints `SUCCESS`

**Comment by messense** [comment]
You need to make sure your uniff crate major.minor version is aligned with the python `uniffi-bindgen` package version.

**Comment by messense** [comment]
FYI, the python `uniffi-bindgen` package exists as an optimization to reduce compilation time for uniffi bindings, you can use the official recommended way of creating the `uniffi-bindgen` binary in your project to better satisfy the version requirement.

**Comment by itrumper** [comment]
Thank you for the additional info! Yes, on further inspection, my `uniffi` crate version was `0.25`, and it just so happened that I began using `maturin` a day after the `0.26` release happened 😆 .
