### ISSUE TITLE
Python can't find DLL when linking external C library (gtstreamer) on Windows

### ISSUE THREAD

**Issue by marcpabst** [PyO3/maturin#1937]
### Bug Description

Hey, I really like maturin/PyO3 and I've been using it for a project linking gstreamer. I'm now testing my package on Windows (was using MacOS before) and I'm running into a problem with Python unable to find DLLs.

A simple example repo can be found here: https://github.com/marcpabst/webcam-py

Importing the created python package (`maturin develop`) works fine on MacOS but fails on Windows with `ImportError: DLL load failed while importing webcam_py: The specified module could not be found.`. It works when I manually copy the gstreamer DLLs to tge `site-packages` folder, but that seems to break internal linking within gstreamer.

Any pointers?

### Your maturin version (`maturin --version`)

1.4.0

### Your Python version (`python -V`)

Python

### Your pip version (`pip -V`)

3.8.0

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

1. Run the provided repo with `maturin develop`
2. Try to `import webcam_py`
3. 3. Observe the `ImportError: DLL load failed while importing webcam_py: The specified module could not be found.`

**Comment by marcpabst** [comment]
Looks like Python is not automatically searching $PATH from v3.8 onwards, it works if you use `os.add_dll_directory()`. Should maturin/PyO3 handle this?

**Comment by messense** [comment]
How should `maturin` handle this? What's the right argument to pass to `os.add_dll_directory()`?

**Comment by marcpabst** [comment]
Good queston. `os.add_dll_directory()`  needs to be called with each directory to look for DLLs in for. Could we maybe have an option to just add everything in `PATH` to `os.add_dll_directory()` when importing? The alternative is some form of bundling, but that can cause license issues.

I'm still not sure why it just works on MacOS.

**Comment by messense** [comment]
IMHO, for security it should be left for the library/user to call `os.add_dll_directory()`, doing in in `maturin`/`pyo3` unconditionally seems worrisome.

**Comment by marcpabst** [comment]
What are the security implications? IMHO this is the standard for system-wide dynamic DLLs. I generally think it's highly unintuitive to require a library user to call `os.add_dll_directory()` before `import`ing things. You can't even have your library handle this (by letting the user specify a search path), because linked libraries will always be loaded upon `imports` (I think).

So there needs to be some sort of way to either tell `maturin` or `poy3` to add `PATH`, or to injects custom python code before the module DLL is loaded. I'm not ssuggesting this should happen unconditionally, but for some modules this will just be required.

**Comment by messense** [comment]
> What are the security implications you're worried about?

The doc says:

> DLL dependencies for extension modules and DLLs loaded with [ctypes](https://docs.python.org/3/library/ctypes.html#module-ctypes) on Windows are now resolved more **securely**.

If there isn't any security implications, you'd want python to handle it automatically, right?

Anyway, I suggest you use a mixed Python/Rust project layout and add `os.add_dll_directory()` call before importing the Rust extension module.

**Comment by marcpabst** [comment]
Thats probbaly the way to go, thanks! Maybe worth documenting as the standard error when trying to import on Windows.
