### ISSUE TITLE
maturin and uniffi doesn't appear to be using pyproject.toml

### ISSUE THREAD

**Issue by stusmall** [PyO3/maturin#1944]
### Bug Description

When trying to build a uniffi project with maturin it doesn't seem to be using the pyproject.toml.  I have a minimal project here to show this: https://github.com/stusmall/maturin-uniffi-errors

There are two make commands available, one of them builds a wheel but it ignores the dependencies in the pyproject.  The other fails to build because maturin can't find the pyproject.toml.  I suspect they both have the same root cause.

### Your maturin version (`maturin --version`)

1.4.0

### Your Python version (`python -V`)

3.11.7

### Your pip version (`pip -V`)

23.3.1

### What bindings you're using

uniffi

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

1. Check out the included repo
2. (optional) use `nix-shell` to pull all tools down
3. type `make build` to see it build the wheel.  Look a the contents of the wheel to see there is nothing referencing the needed dependencies
4. type `build-with-sdist` to see the build fail

**Comment by stusmall** [comment]
I did a little debugging in maturin yesterday.  This appears to be because it assumes the pyproject.toml to be in the same directory as Cargo.toml.  I tried to refactor this following [a pattern I used with another cffi based project where it would have a empty dummy crate that just forwarded definitions.](https://github.com/stusmall/bowbend/)  I didn't have any luck with this

**Comment by messense** [comment]
> This appears to be because it assumes the pyproject.toml to be in the same directory as Cargo.toml.

Actually it assumes Cargo.toml to be located in the same directory or subdirectory as pyproject.toml, but you can specify `manifest-path` in `[tool.maturin]` section of `pyproject.toml`, but now you have to run maturin in the pyproject.toml directory instead of passing `--manifest-path` in CLI.

**Comment by stusmall** [comment]
That fixed it!  Thank you!
