### ISSUE TITLE
`maturin sdist` includes extraneous files in source distribution tar.gz

### ISSUE THREAD

**Issue by ctb** [PyO3/maturin#1948]
### Bug Description

`maturin sdist` builds a source dist tar.gz that includes a number of extraneous files, including zip files, from the working directory.

Details in "steps to reproduce" (and also in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/226).

Interestingly, `cargo package` fails appropriately:
```
error: 1 files in the working directory contain changes that were not yet committed into git:

a-file.zip

to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag
```
despite this statement in the maturin README:

>If a pyproject.toml with a [build-system] entry is present, maturin can build a source distribution of your package when --sdist is specified. The source distribution will contain the same files as cargo package. To only build a source distribution, pass --interpreter without any values.

### Your maturin version (`maturin --version`)

maturin 1.4.0

### Your Python version (`python -V`)

Python 3.11.6

### Your pip version (`pip -V`)

pip 23.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

```
git clone https://github.com/sourmash-bio/sourmash_plugin_branchwater.git
cd sourmash_plugin_branchwater
touch a-file.zip
python -m maturin sdist 
tar tzvf target/wheels/sourmash_plugin_branchwater-0.9.0.tar.gz | grep a-file.zip
```

**Comment by messense** [comment]
This is expected because we pass `--allow-dirty` to `cargo package` when building sdist.
