### ISSUE TITLE
Add a way to include non-python/rust files in generated sdist/wheel despite .gitignore

### ISSUE THREAD

**Issue by LilyFoote** [PyO3/maturin#1950]
In our project we generate some javascript and css that we want to include in our sdist and wheel. When we first added this, this worked automatically because:

> In a mixed Rust/Python project, additional files in the Python source dir (but not in .gitignore) will be automatically included in the build outputs (source distribution and/or wheel).

However, since we generate these files, we want to include them in our `.gitignore` file so they don't get annoying during local development. But adding them to `.gitignore` means maturin no longer includes them. I looked at https://www.maturin.rs/project_layout#data, but this doesn't appear to allow us to place the files where we want them in our sdist or wheel.

**Comment by messense** [comment]
Have you tried `[tool.maturin.include]`? See https://www.maturin.rs/config#maturin-options

**Comment by LilyFoote** [comment]
Aha! I'd missed that - will give it a go!

**Comment by LilyFoote** [comment]
Yeah, I think that's fixed it!
