### ISSUE TITLE
option to use uv

### ISSUE THREAD

**Issue by mbway** [PyO3/maturin#1959]
It may be beneficial to offer [uv](https://github.com/astral-sh/uv) as a backend for `maturin develop` rather than hard-coding `pip` as the only available backend.

I was thinking about this while thinking of ways to speed up the import hook tests as a significant part of those tests is waiting for `maturin develop`. Compilation still probably takes the majority of the time but there may be a small benefit.

`uv pip` offers a pip-compatible interface for installing packages but may be faster than using pip. Since it's written in rust perhaps it could be bundled into maturin directly as a library?

**Comment by messense** [comment]
I'm in favor of add support for it, but I don't want to bundle/link it into maturin directly given that it's not stable yet (we don't want to release a new version of maturin everytime `uv` makes a new release) and will increase compile time and binary size for maturin.

Call `uv pip` in subprocess should be fine.

cc @konstin

**Comment by dmatos2012** [comment]
from the comments it seems clear how it should look like , so I would like to give this one a try if ok with everyone :)

**Comment by messense** [comment]
@dmatos2012 Thanks!

**Comment by nleroy917** [comment]
Just now occurring to me that this might not be released yet.

**Comment by bluenote10** [comment]
Nice to have this feature implemented! @nleroy917 Looks like it is released in maturin 1.6.0

Out of curiosity: Is there also a way to configure the usage of `uv` via the config, so that it is not necessary to pass `--uv` along with each command line invocation?
