### ISSUE TITLE
Feature request: option to build no wheels (sdist only)

### ISSUE THREAD

**Issue by clbarnes** [PyO3/maturin#197]
On CI, where only one python version is available per job, it might be preferable to have one job per wheel. In that case, you wouldn't also want to try (and fail) to deploy one sdist per job. You could read some environment variables and mangle your maturin arguments to do `--no-sdist` in specific situations, but it might be more ergonomic to run one job which is *just* an sdist, and one job for each wheel.

I suggest `-I` (upper-case i)/`--sdist-only`, as it's the opposite of adding an interpreter to build a wheel for with `-i`.

**Comment by konstin** [comment]
This was actually already supported as it was requested in #2, but apparently I forgot to mention it in the readme. The released way is `maturin sdist`, so you'll want to use that for now. I've also just added `maturin build --interpreter`/`maturin publish --interpreter`, which will be part of the next release and is documented in the readme.

**Comment by clbarnes** [comment]
Great, thanks! So in future, will `maturin publish <some option>` be able to publish a sdist directly to PyPI?

**Comment by konstin** [comment]
Yes, with 0.7.2, `maturin publish --interpreter` only uploads the sdist. You can test that by creating an account on test pypi and running  `maturin publish --interpreter -r https://test.pypi.org/legacy/`.

**Comment by winstxnhdw** [comment]
I don't think this is true anymore?
