### ISSUE TITLE
InvalidDistribution due ot `maturin 1.5`?

### ISSUE THREAD

**Issue by ritchie46** [PyO3/maturin#1983]
### Bug Description

I am not entirely sure the bug is due to `maturin`, but given that (I believe) nothing changed in our release process and that `maturin 1.5` is one day old, I give it a high probability.

The python release build fails with: https://github.com/pola-rs/polars/actions/runs/8174718472/job/22354392735

### Your maturin version (`maturin --version`)

1.5

### Your Python version (`python -V`)

-

### Your pip version (`pip -V`)

-

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

Publish a release to pypi

**Comment by konstin** [comment]
That looks like https://github.com/pypa/gh-action-pypi-publish/pull/219

**Comment by ritchie46** [comment]
Pinning to 1.4 didn't fix it. So can confirm it isn't maturin. Sorry for the noise.

@stinodego fyi
