### ISSUE TITLE
Generated wheel try to load wrong lib name (using uniffi generated bindings)

### ISSUE THREAD

**Issue by RCasatta** [PyO3/maturin#1987]
### Bug Description

Hello, I am trying maturin with a project using uniffi bindings. The repo with the branch I am testing is https://github.com/Blockstream/lwk/tree/wheel

The build succeed but I have two issues in using the generated wheel:

- when I try to import the lib it fails trying to load `liblwk_bindings.so` but the real file has uniffi in the middle: `libuniffilwk_bindings.so` (if I rename manually it works) (note also that if I build with rust the uniffi in the middle isn't there so I think is added by maturin)
- To use it I need this "double import" from `lwk_bindings import lwk_bindings`, the generated `__init__.py` has not the lines following the first suggested in the readme https://www.maturin.rs/project_layout#pure-rust-project (If i change it manually it works with just `import lwk_bindings`)

### Your maturin version (`maturin --version`)

1.5.0

### Your Python version (`python -V`)

3.10.12

### Your pip version (`pip -V`)

22.0.2

### What bindings you're using

uniffi

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

```
git clone https://github.com/blockstream/lwk
cd lwk/lwk_bindings
git checkout wheel
virtualenv venv && source venv/bin/activate && pip install maturin maturin[patchelf] uniffi-bindgen
maturin develop
python -c `import lwk_bindings`
```

**Comment by messense** [comment]
You need to set `cdylib_name` for python bindings in `uniffi.toml`

```toml
[bindings.python]
cdylib_name = "lwk_bindings"
```

See https://mozilla.github.io/uniffi-rs/python/configuration.html
