### ISSUE TITLE
maturin 1.5 as backend breaks poetry add

### ISSUE THREAD

**Issue by brettc** [PyO3/maturin#1988]
### Bug Description

poetry (and perhaps others not tested) cannot install a package that has maturin 1.5 as a backend.

So, with this in my `pyproject.toml`, I cannot install the package, as it selects maturin 1.5. Poetry reports:
`Unable to create package with no name`

```
[build-system]
requires = ["maturin>=1.2,<2.0"]
build-backend = "maturin"
```

If I change it this line, it works:
`requires = ["maturin>=1.2,<1.5"]`

### Your maturin version (`maturin --version`)

1.5

### Your Python version (`python -V`)

3.12.2

### Your pip version (`pip -V`)

23.3.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

Make sure you have the latest `poetry` and `rye` installed.
Do this in a shell:
```
# create a python and a python/maturin project
poetry new snake
rye init oxide --build-system maturin

# add the maturin project as a dependency
cd snake
poetry add ../oxide

# Fail
```

To fix it, change the line `["maturin>=1.2,<1.5"]`
Now the `poetry add` will work.

**Comment by messense** [comment]
Probably because Poetry doesn't support [metadata 2.3](https://packaging.python.org/en/latest/specifications/core-metadata/#metadata-version)?

**Comment by konstin** [comment]
Fixed upstream in https://github.com/python-poetry/poetry/pull/9130
