### ISSUE TITLE
[Feature request] Add llvm tools in maturin image

### ISSUE THREAD

**Issue by Owen-CH-Leung** [PyO3/maturin#2000]
I'm trying to use maturin to cross-compile my rust projects into python windows wheels and linux wheels. One of the project dependencies is `lz4-sys v1.9.4` and when trying to run `maturin build --profile dev --target x86_64-pc-windows-msvc --strip --sdist`, I encountered the following error:

```
running: "clang-cl" "-nologo" "-MD" "-Z7" "-Brepro" "-m64" "--target x86_64-pc-windows-msvc" xxxxx (skipping long list of commands)

--- stderr
error occurred: Failed to find tool. Is `clang-cl` installed?
error: failed to run custom build command for `lz4-sys v1.9.4`
``` 

It looks like that maturin is trying to use a tool called `clang-cl`, which is part of the Clang compiler suite & the LLVM project. So Can I ask if we can modify the docker image to include the llvm tools ? I believe sth like `yum install llvm` will work

**Comment by messense** [comment]
No, the maturin docker image is for native compilation only, cross compliation support is built into `maturin-action`.
