### ISSUE TITLE
AIX still not supported

### ISSUE THREAD

**Issue by flynn1973** [PyO3/maturin#2035]
### Bug Description

I changed target.rs according to https://github.com/PyO3/maturin/pull/2030/commits/5c5889956a15cd36bff82b1a81a079a24d6cf7ea and rebuild manturin, alas still...

````
root@nimvie: /srv/www/cargo_cache/registry/src/index.crates.io-d11c229612889eed/maturin-1.5.1/src # /opt/freeware/bin/pip3 install rpds-py
Collecting rpds-py
  Using cached rpds_py-0.18.0.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [7 lines of output]
  📦 Including license file "/tmp/pip-install-l7lqou8f/rpds-py_7658905d4d02490babc0af64a8c017db/LICENSE"
  🔗 Found pyo3 bindings
  💥 maturin failed
    Caused by: The operating system Aix is not supported
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-8chuq4z2', '--interpreter', '/opt/freeware/bin/python3.9']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-8chuq4z2 --interpreter /opt/freeware/bin/python3.9`
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

````

anything still missing probably?

### Your maturin version (`maturin --version`)

1.5.1

### Your Python version (`python -V`)

3.9.18

### Your pip version (`pip -V`)

22.2.2

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

not applicable

**Comment by messense** [comment]
Looks like you are using maturin from pypi, try disable pip build isolation with `--no-build-isolation` to use your locally patched version.

**Comment by messense** [comment]
Or just use `maturin build` using your patched version and run `pip install` on the built wheel afterwards.
