### ISSUE TITLE
Feature: Don't copy dependencies' DLLs by default

### ISSUE THREAD

**Issue by NfNitLoop** [PyO3/maturin#2038]
## Existing Functionality

If I'm understanding things correctly, Maturin has this current feature:

If a build results in code that dynamically links to a library (that's not libc?), Maturin:
* Copies those DLLs into the resulting python package.
* (on Linux) uses `patchelf` to fix DLL loading (to use those copied DLLs, I assume).

Example `maturin build` output:

```
🖨  Copied external shared libraries to package [your-package].libs directory:
    /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
    /usr/lib/aarch64-linux-gnu/libssl.so.1.1
```

## The Problem

This is really surprising behavior!

My builds had been working fine, until I added some dependency which (somewhere down the transitive dependency chain) introduces dynamic linkage. Then I got surprise errors about `patchelf`, which wasn't needed before.

Thankfully I took some time to investigate the sudden need for patchelf because **I don't want third-party dynamic libraries copied into my python package**.  It's only an accident of the dependencies I've added.

IANAL but can't there also be legal implications to distributing a DLL vs linking to it? 

## Requested Improvement

Maybe maturin shouldn't copy DLLs by default. Or, at a minimum, I'd love an option to explicitly disable copying them.

If some people want to allow *some* DLLs but avoid accidentally including others, maybe an "allow list" for DLLs to be copied would work better for them.

## Workaround

For now, I'm working to remove the DLL from my dependency tree. I'm recommending that my team **not** add the `patchelf` dependency to our build dependencies/environments, so that it can act as a stopper to keep us from getting into this situation again.

But relying on some dependency being missing is not the most stable way to accomplish this. 😅 

## Context

This is related to an issue I asked for help with [in Discord][1].

[1]: https://discord.com/channels/1209263839632424990/1228027124053442671

**Comment by messense** [comment]
> Maybe maturin shouldn't copy DLLs by default

I disagree, you'd ship broken wheels to users.


> Or, at a minimum, I'd love an option to explicitly disable copying them.

You can already do that by passing `--compatibility linux`

**Comment by NfNitLoop** [comment]
> I disagree, you'd ship broken wheels to users.

I'm not saying that it should *succeed* in that case. It should fail the build, with something like:

"X depends on shared library Y. To copy it into the python wheel, configure your build with [setting]."

**Comment by messense** [comment]
> "X depends on shared library Y. To copy it into the python wheel, configure your build with [setting]."

That's #2039, so closing this in favor of that.

**Comment by NfNitLoop** [comment]
No, #2039 is just to add logging, it says nothing about failing the build.

**Comment by messense** [comment]
It will fail if you don't have `patchelf` installed.

**Comment by NfNitLoop** [comment]
Yeah, that's not a very reliable system. What if patchelf was installed for something else? "Just uninstall patchelf to avoid accidentally copying things into your build results" is such a hack. 😞

**Comment by messense** [comment]
As I have said, you have `--compatibility linux` or `--skip-auditwheel` for explicit control.

**Comment by NfNitLoop** [comment]
Are there docs that I should have read that say "use these options to keep from copying shared libraries into your package"? Because I missed them. And I never would have guessed that from either of those options names. 😅

**Comment by messense** [comment]
There are some docs in https://www.maturin.rs/distribution#build-wheels but definitely can be improved (esp. for people not familiar with [auditwheel](https://github.com/pypa/auditwheel/)).

**Comment by NfNitLoop** [comment]
Aha!  Thanks for the pointer. I'm not familiar with auditwheel. 

> maturin contains a reimplementation of auditwheel automatically checks the generated library and gives the wheel the proper platform tag.
> 
> 1. If your system's glibc is too new, it will assign the linux tag.
> 2. If you link other shared libraries, maturin will try to bundle them within the wheel, note that this requires [patchelf](https://github.com/NixOS/patchelf), it can be installed along with maturin from PyPI: pip install maturin[patchelf].

However, I tried both of your suggestions: `--compatibility linux`  or `--skip-auditwheel`.  They both seem to have the same effect: 
* No DLLs are copied into the package. 
* But the build isn't failed.  (Unless patchelf [is missing][1].)

So now I'm accidentally distributing a wheel that might not work on users' systems.

What I really want is:
* I can specify a compatibility target. (ex: before running into this issue, our GitHub workflows were able to target manylinux_2_17.) 
* The build **does not** copy DLLs into my package to make it compatible.
* Instead fails if it is not compatible.  (ex: I get this behavior if I target an older manylinux compatibility, but I'm building on a system that's too new to guarantee compatibility.) 
* This doesn't rely on whether or not [some dependency][1] is present on my system.

[1]: https://github.com/PyO3/maturin/issues/2038#issuecomment-2050733483

**Comment by messense** [comment]
That sounds reasnable, I think we extend `--skip-auditwheel` to add some variants:

* `--skip-auditwheel`: no functional change, deprecate it in favor of `--auditwheel=skip`
* `--auditwheel=repair`: same as `--compability=XXX` w/o `--skip-auditwheel`
* `--auditwheel=skip`: new `--skip-auditwheel` equivlent option
* `--auditwheel=check`: fail the build if it requires copy DLLs

**Comment by messense** [comment]
@NfNitLoop What do you think of https://github.com/PyO3/maturin/issues/2038#issuecomment-2050791915

under this proposal, you will use `maturin build --compability manylinux_2_17 --auditwheel=check`.

**Comment by NfNitLoop** [comment]
Love it! That would be great!

BTW, I assume you might make `--auditwheel=repair` the default, for backward compatibility, and that's reasonable. But I would recommend (maybe in the next semver-major release) making "check" the default. I talked w/ a few other rust developers about this issue and they all seemed surprised to hear that copying shared libraries was the default. I think "the least surprising behavior" is a good default.

**Comment by NfNitLoop** [comment]
Can we re-open this issue, then?

**Comment by messense** [comment]
> I talked w/ a few other rust developers about this issue and they all seemed surprised to hear that copying shared libraries was the default. I think "the least surprising behavior" is a good default.

Though the current state is the least surprising behavior for Python users.

**Comment by messense** [comment]
Closing in favor of #2045
