### ISSUE TITLE
Extend `--skip-auditwheel` to support check mode

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#2045]
I think we can extend `--skip-auditwheel` to add some variants:

* `--skip-auditwheel`: no functional change, deprecate it in favor of `--auditwheel=skip`
* `--auditwheel=repair`: same as `--compability=XXX` w/o `--skip-auditwheel`
* `--auditwheel=skip`: new `--skip-auditwheel` equivlent option
* `--auditwheel=check`: fail the build if it requires copy DLLs or new GLIBC versions

_Originally posted by @messense in https://github.com/PyO3/maturin/issues/2038#issuecomment-2050791915_

**Comment by NfNitLoop** [comment]
👍 I think this is an important feature. As I mentioned in #2038:

> IANAL but can't there also be legal implications to distributing a DLL vs linking to it?

I also want to opt-in to copying extra DLLs into my package, vs. having it creep in automatically via some dependency.
