### ISSUE TITLE
CARGO=cross uses wrong --manifest-path

### ISSUE THREAD

**Issue by XeCycle** [PyO3/maturin#2089]
### Bug Description

```
 $ CARGO=cross maturin build -r
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
🐍 Not using a specific python interpreter
error: manifest path `/home/xecycle/<REDACTED>/Cargo.toml` does not exist
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO "cross" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/xecycle/<REDACTED>/Cargo.toml" "--release" "--lib"`
```

Inside cross container the project should be at `/project`, and thus manifest path should be `/project/Cargo.toml`.

### Your maturin version (`maturin --version`)

1.5.1

### Your Python version (`python -V`)

3.8.18

### Your pip version (`pip -V`)

24.0

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

Project directory layout is like
```
Cargo.lock
Cargo.toml
Cross.toml
pyproject.toml
python/<REDACTED>/__init__.py
src/lib.rs
```
and pyproject.toml contains
```
[tool.maturin]
python-source = "python"
module-name = "PACKAGE_NAME.RUST_MODULE_NAME"
```
Run `CARGO=cross maturin build -r`.

cross version is 0.2.5.

**Comment by messense** [comment]
`/project` was removed in future cross version, you are better off [configure the mount](https://github.com/cross-rs/wiki_assets/blob/265c29abca8b4224e0a4bf1578eb6c3e787f6e93/Configuration/Cross.toml#L36-L43) in `Cross.toml` to the same as host path.

See https://github.com/cross-rs/cross/issues/938

**Comment by XeCycle** [comment]
Thank you, didn't know that change in cross...
