### ISSUE TITLE
Mixed projects PYTHONPATH issue

### ISSUE THREAD

**Issue by ijl** [PyO3/maturin#210]
maturin builds a mixed Rust/Python project if `{name}/__init__.py` exists, so the `PYTHONPATH` for the project's name is this directory rather than the installed project. This causes `ImportError` in tests etc. during development. This affects all mixed projects, so perhaps the detection can instead use `_{name}/__init__.py` or `py{name}/__init__.py`? I see that the directory could also be an option in `Cargo.toml` but I think it would be better to fix by default.

**Comment by konstin** [comment]
I intended this as a feature: You can run `maturin develop` once and then edit and run your python code without installing it to site-packages every time, and you also get IDE support for the python side of your package.

I'm not sure if I just need to explain this better in the documentation or if there are project configurations where `_{name}` is more reasonable in general.

**Comment by ijl** [comment]
Ok, thanks for explaining.
