### ISSUE TITLE
Maturin infers target is apple darwin on linux

### ISSUE THREAD

**Issue by dan-j-cooper** [PyO3/maturin#2101]
### Bug Description

When using maturin develop or maturin build the build fails with: 
...
  = note: the `x86_64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-apple-darwin`
...
PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON=".../.venv/bin/python" PYTHON_SYS_EXECUTABLE=".../.venv/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--target" "x86_64-apple-darwin" "--message-format" "json-render-diagnostics" "--manifest-path" "/.../Cargo.toml" "--lib" "--crate-type" "cdylib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/rs_tools.abi3.so"`
on linux.
It appears that during into_build_context, the returned archflags are always interpreted as being for apple darwin even if the actual platform isn't. 

I made a very simple fix which I have no way of checking works on other platforms (obviously, if this is also a bug on windows it wont work)

531 | let mut universal2 = target_triple.as_deref() == Some("universal2-apple-darwin");
532 | if env::consts::OS != "linux" {

but it works on my machine and the build finishes for both develop and build.

I don't know enough about the code base to assume that this fix is valid in general or what assumptions I'm missing.

### Your maturin version (`maturin --version`)

1.6.0

### Your Python version (`python -V`)

3.11.9

### Your pip version (`pip -V`)

24

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

run maturin develop or maturin build on linux for my project, which is unfortunately closed source.

**Comment by messense** [comment]
What's the output of `import sysconfig; print(sysconfig.get_platform(), end='')` if you run it in python?

**Comment by messense** [comment]
> run maturin develop or maturin build on linux for my project, which is unfortunately closed source.

Can you make a minimal repro?

**Comment by dan-j-cooper** [comment]
> What's the output of `import sysconfig; print(sysconfig.get_platform(), end='')` if you run it in python?

linux-x86_64, 

> Can you make a minimal repro?

So, I tried running maturin new and running it in that and  it seems like I get the same issue, when I run maturin develop I get:

🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
💥 maturin failed
  Caused by: Python interpreter should be a kind of interpreter (e.g. 'python3.8' or 'pypy3.9') when cross-compiling, got path to interpreter: /home/test/Code/bugreport/bugreport/.venv/bin/python
  
  when using my patched version the build succeeds.

**Comment by messense** [comment]
Please provide full command when running `maturin` as well as pyo3 & maturin & cargo/rustc related env vars you have set.

**Comment by messense** [comment]
> I made a very simple fix which I have no way of checking works on other platforms (obviously, if this is also a bug on windows it wont work)
> 
> 531 | let mut universal2 = target_triple.as_deref() == Some("universal2-apple-darwin"); 532 | if env::consts::OS != "linux" {
> 
> but it works on my machine and the build finishes for both develop and build.

Did you set the `ARCHFLAGS` env var by accident?

**Comment by dan-j-cooper** [comment]
You're right! 

it appears the line: 
export ARCHFLAGS="-arch x86_64"
from the default oh-my-zsh config got uncommented at some point.

Thanks! I guess there should probably be some sanity check here rather than assuming that ARCHFLAGS hasn't been set erroneously.
