### ISSUE TITLE
Build crate where pyo3 is enabled by a feature

### ISSUE THREAD

**Issue by programmerjake** [PyO3/maturin#211]
I'm trying to add python bindings to an already-existing crate where I want python to be enabled with a feature that is not enabled by default. I created a minimal example of what I wanted to do:
https://github.com/programmerjake/rust-python-test/tree/7b7ac59c66df8c5b8939361f94f2bc92c53b3c4b

Building using cargo works just fine with:

```
$ cargo +nightly build --features python-extension
```

I tried to build it using maturin 0.7.2 running in the repo root directory but it didn't work:

```
$ maturin build
💥 maturin failed
  Caused by: Couldn't find any bindings; Please specify them with --bindings/-b
```

I also tried:

```
$ maturin build --bindings=pyo3
💥 maturin failed
  Caused by: The bindings crate pyo3 was not found in the dependencies list
```

```
$ maturin build --bindings=pyo3 --cargo-extra-args="--features python-extension"
💥 maturin failed
  Caused by: The bindings crate pyo3 was not found in the dependencies list
```

```
$ maturin build --cargo-extra-args="--features python-extension"
💥 maturin failed
  Caused by: Couldn't find any bindings; Please specify them with --bindings/-b
```

How do I fix it?

**Comment by konstin** [comment]
Thanks for the report. I forgot to include the cargo extra args when determining the bindings, which should be fixed now, so `maturin build --cargo-extra-args="--features python-extension"` should work.

**Comment by programmerjake** [comment]
Thanks for quickly fixing!!
