### ISSUE TITLE
Windows aarch64 build fails: "no cab files were referenced by the MSI"

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin#2110]
First found in `pydantic-core` CI:

https://github.com/pydantic/pydantic-core/actions/runs/9482594395/job/26127819276?pr=1327#step:7:688

It looks like `xwin` is downloading some build tools for the `aarch64` build, but failing to process those files. Ideas are welcome!

**Comment by messense** [comment]
See https://github.com/rust-cross/cargo-xwin/issues/108, let's move the discussion there.

**Comment by davidhewitt** [comment]
Thanks! 👍
