### ISSUE TITLE
Adapt rustc 1.79

### ISSUE THREAD

**Issue by ZianTT** [PyO3/maturin#2111]
### Bug Description

the built-in rustc 1.78 doesn't adapt some deps.

### Your maturin version (`maturin --version`)

1.6.0

### Your Python version (`python -V`)

3.12.3

### Your pip version (`pip -V`)

n/a

### What bindings you're using

None

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. build with some deps such as bitstream-io@2.4.1 which requires rustc 1.79

**Comment by messense** [comment]
Just use rustup to upgrade it before building.
