### ISSUE TITLE
publish 0.7.5 completely

### ISSUE THREAD

**Issue by programmerjake** [PyO3/maturin#212]
It appears as though version 0.7.5 didn't end up on pypi for non-windows platforms:
https://pypi.org/project/maturin/0.7.5/#files

I think there should also be a source package on pypi for those who are using non-x86 platforms, if that's doable (not sure if pypi shows that in the files tab).

Also, 0.7.5 didn't end up on crates.io at all.

**Comment by programmerjake** [comment]
It's causing my Docker build to fail:
https://github.com/programmerjake/rust-python-test/tree/c56c42a028a0c5b346ec5999529f951dbb27e721

build using:
```
docker build .
```
or
```
sudo docker build .
```

**Comment by programmerjake** [comment]
see also: https://travis-ci.org/PyO3/maturin/builds/588910876

**Comment by robertodr** [comment]
Yes, it would be helpful to have the latest version uploaded to crates.io

**Comment by konstin** [comment]
Should be fixed now; I accidentally broke cross compilation and thereby publishing when trying to fix #211.

> It's causing my Docker build to fail:

FWIW there's also `konstin2/maturin` which is based on the official manylinux image.
