### ISSUE TITLE
CentOS 7 Deprecation & Possibility to upgrade base image

### ISSUE THREAD

**Issue by Owen-CH-Leung** [PyO3/maturin#2149]
Maturin use `quay.io/pypa/manylinux2014_x86_64` as its base image, which is a CentOS 7 image according to the README of the manylinux repo.

https://github.com/PyO3/maturin/blob/main/Dockerfile#L2C6-L2C39
https://github.com/pypa/manylinux

However, CentOS7 has reached EOL this year on June 30. See this [link](https://www.redhat.com/en/topics/linux/centos-linux-eol#:~:text=Overview-,CentOS%20Linux%207%20reached%20end%20of%20life,)%20on%20June%2030%2C%202024.) for details: 

This has resulted in some mirrors defined under mirrorlist of `/etc/yum.repos.d` not available to yum. As an example, here's an output of running a `yum update`: 

```
~ docker run --entrypoint "/bin/bash" -it ghcr.io/pyo3/maturin

[root@a9c63abb5447 io]# yum update
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=aarch64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
Could not retrieve mirrorlist http://mirrorlist.centos.org?arch=aarch64&release=7&repo=sclo-rh error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=aarch64&repo=extras&infra=container error was

```

While most yum commands eventually are able to resolve the dependencies & install the required packages, I think this could be a supply chain risk to base the maturin image on an EOL image. I don't have any concrete ideas in mind to solve this, but maybe upgrading the base image to a more updated one could be a solution ? (e.g. maybe `quay.io/pypa/manylinux_2_28_x86_64` ? )

**Comment by messense** [comment]
Just need to release a new version to pull in https://github.com/pypa/manylinux/pull/1628, for the moment you can use the `main` tag instead.
