### ISSUE TITLE
Incompatible with conda or venv, with error "markers XXX don't match your environment"

### ISSUE THREAD

**Issue by tribbloid** [PyO3/maturin#2161]
### Bug Description

(main article: https://github.com/PyO3/maturin/discussions/2159)

I could now confirm that this is a maturin bug, as the error message is identical with conda or venv

### Your maturin version (`maturin --version`)

1.7.0

### Your Python version (`python -V`)

3.11.9

### Your pip version (`pip -V`)

24.0

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

git checkout https://github.com/egraphs-good/egglog-python

create a new conda-env/venv

compile with `maturin develop --all-features`

**Comment by messense** [comment]
It's just warnings from `pip install`, is there any actual issue caused by this warnings?

**Comment by tribbloid** [comment]
don't think so, pip under the same environment has no warning:

```
pip install numba
Collecting numba
  Downloading numba-0.60.0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.7 kB)
Collecting llvmlite<0.44,>=0.43.0dev0 (from numba)
  Downloading llvmlite-0.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: numpy<2.1,>=1.22 in /home/shared/conda/lib/python3.9/site-packages (from numba) (2.0.0)
Downloading numba-0.60.0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 3.3 MB/s eta 0:00:00
Downloading llvmlite-0.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
   ━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/43.9 MB 860.8 kB/s eta 0:00:39
...
```

**Comment by messense** [comment]
It seems that this code isn't working, pull requests are welcome to fix it

https://github.com/PyO3/maturin/blob/fd119cd30ed16ca734d763e3e8fd48caf7809afd/src/develop.rs#L151-L173

**Comment by Owen-CH-Leung** [comment]
@tribbloid I did some digging and I believe that it's not a bug from maturin. `maturin develop` does support installing optional dependency. I tried to clone your repo, create a venv and run ` maturin develop --all-features --extras=array,dev,test,docs`. All your optional dependencies in pyproject.toml are installed (and pytest are available for your use)

**Comment by tribbloid** [comment]
thanks a lot! verified and working. If this is the intended definition of --all-features then this issue can be closed
