### ISSUE TITLE
Cannot publish projects to PyPi

### ISSUE THREAD

**Issue by Bronzdragon** [PyO3/maturin#2172]
### Bug Description

Running `maturin publish` requests for a username and password, as normal. However, this method is not supported by PyPi any more.

The exact output I get is as follows:
```sh
$ maturin publish
🔗 Found pyo3 bindings
🐍 Found CPython 3.12 at /home/walter/Projects/perceptron/.env/bin/python
📡 Using build options features from pyproject.toml
   Compiling perceptron-rs v0.1.0 (/home/walter/Projects/perceptron)
    Finished `release` profile [optimized] target(s) in 0.38s
📦 Built wheel for CPython 3.12 to /home/walter/Projects/perceptron/target/wheels/perceptron_rs-0.1.0-cp312-cp312-manylinux_2_34_x86_64.whl
📦 Built source distribution to /home/walter/Projects/perceptron/target/wheels/perceptron_rs-0.1.0.tar.gz
Please enter your username:
bronzdragon
Please enter your password: [hidden]
🚀 Uploading 2 packages
⛔ 403 Username/Password authentication is no longer supported. Migrate to API Tokens or Trusted Publishers instead. See https://pypi.org/help/#apitoken and https://pypi.org/help/#trusted-publishers
💥 maturin failed
  Caused by: Username and/or password are possibly wrong
```

### Your maturin version (`maturin --version`)

maturin 1.7.0

### Your Python version (`python -V`)

Python 3.12.4

### Your pip version (`pip -V`)

maturin 1.7.0

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Have a valid Maturin project active.
2. Run `maturin publish`.
3. Maturin uses a no-longer supported authentication method, and fails.

**Comment by konstin** [comment]
This is a change in pypi, not in maturin. Please refer to pypi's documentation on using tokens.

**Comment by henselman-petrusek** [comment]
I recently encountered the same issue. When this occurs, you can enter `__token__` for username and a PyPI API token for the password.
