### ISSUE TITLE
`--uv` does not allow passing in `--break-system-packages` on system Python

### ISSUE THREAD

**Issue by nth10sd** [PyO3/maturin#2195]
### Bug Description

There are scenarios where `uv pip` needs to call `--break-system-packages` and it seems there is no way to pass that in to the `--uv` call.

### Your maturin version (`maturin --version`)

1.7.1

### Your Python version (`python -V`)

Python 3.10.14

### Your pip version (`pip -V`)

pip 24.2

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

`uv` detects that it is system Python and refuses to continue. In regular `uv pip` installations outside of `maturin`, `--break-system-packages` is passed in, however, it seems in `maturin` there is no way to set `--break-system-packages`.

**Comment by nth10sd** [comment]
Oh, I had been passing in `env VIRTUAL_ENV=$(python -c 'import sys; print(sys.base_prefix)')` to `maturin` to allow it to previously work with `pip`, I guess this workaround no longer works for `--uv`?

**Comment by messense** [comment]
We are unlikely to add `--break-system-packages` to `uv pip` command, however I think you can enable it by exporting `UV_BREAK_SYSTEM_PACKAGES=1`.

**Comment by nth10sd** [comment]
`UV_BREAK_SYSTEM_PACKAGES=1` does help me work around this issue. Thank you!
