### ISSUE TITLE
Http Error

### ISSUE THREAD

**Issue by David-OConnor** [PyO3/maturin#220]
When running the following command, on a project no no additional config:

```
maturin publish --manylinux off


🚀 Uploading 1 packages
💥 maturin failed
  Caused by: 💥 Failed to upload "pyflow-0.1.7-py2.py3-none-linux_x86_64.whl"
  Caused by: Http error
  Caused by: https://upload.pypi.org/legacy/: timed out
```

Do I need to perform any additional setup, like registering a `pypi` package before attempting? Note that the wheel builds and runs properly when directly installed with pip.

**Comment by programmerjake** [comment]
I would assume that is caused by pypi's servers not responding for some reason rather than a bug in maturin

**Comment by konstin** [comment]
I assume this happened because you tried to upload a huge file and is not something that maturin can do anything about. I've added the filesize to the error message in #224.

**Comment by David-OConnor** [comment]
Nope - I coincidentally had a `pyproject.toml` in the Rust directory; deleting that fixed the error.

**Comment by konstin** [comment]
Is the http error reproducible with the `pyproject.toml`?
