### ISSUE TITLE
Add -r flag explanation for release builds in Maturin quickstart guide

### ISSUE THREAD

**Issue by Smart-SangGe** [PyO3/maturin#2210]
Description: The tutorial doesn't mention the -r flag, which enables building with an optimized target (release mode). This omission caused me to spend several hours trying to optimize my code manually. Eventually, I discovered the -r flag, which significantly improved the performance of my bindings, making them run much faster.

Suggestion: Please update the tutorial to include the -r flag and explain its impact on performance, so that others can avoid unnecessary troubleshooting and immediately take advantage of the optimization.

**Comment by messense** [comment]
Pull requests are welcome.

Note that `maturin build` is basically `cargo build` with some extensions so we usually don't write out everything that `cargo build` supports.
