### ISSUE TITLE
Regression relating to repository url in maturin upload when upgrading to 1.7.2

### ISSUE THREAD

**Issue by seddonym** [PyO3/maturin#2228]
### Bug Description

We use maturin upload via the [Maturin action](https://github.com/PyO3/maturin-action) Github action.

[Our latest release failed](https://github.com/kraken-tech/python-rustfluent/actions/runs/11029344761/job/30632470084), apparently due to a malformed repository url:

```
💥 maturin failed
  Caused by: 💥 Failed to upload "rustfluent-0.1.0a3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl" (384.1 KB)
  Caused by: Failed to upload the wheel with status 400: <html>
 <head>
  <title>[40](https://github.com/kraken-tech/python-rustfluent/actions/runs/11029344761/job/30632470084#step:3:43)0 Bad Request</title>
 </head>
 <body>
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
POST body may not contain duplicate keys (URL: &#x27;https://upload.pypi.org/legacy&#x27;)  
```

Downgrading to maturin 1.7.1 fixed the issue.

I'm guessing this is related to [this change](https://github.com/PyO3/maturin/pull/2206/) to the repository URLs, introduced in Maturin 1.7.2.

### Your maturin version (`maturin --version`)

1.7.2

### Your Python version (`python -V`)

Unknown

### Your pip version (`pip -V`)

Unknown

### What bindings you're using

pyo3

### Does `cargo build` work?

n/a

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I'm not sure, but you can see the full error happening in this github action run: https://github.com/kraken-tech/python-rustfluent/actions/runs/11029344761/job/30632470084

**Comment by messense** [comment]
Maybe it's that change, will try to reproduce this issue later.

See also https://github.com/pypi/warehouse/issues/16756

**Comment by seddonym** [comment]
Thanks for the lightning-fast fix! Our releases are now working again, using maturin 1.7.3. 👏🏻
