### ISSUE TITLE
allow separate control of the extension module name

### ISSUE THREAD

**Issue by altendky** [PyO3/maturin#2238]
Often, extension modules are given a leading `_` to mark them as private and encourage use of the public wrapper pure python file/package/module.  For example, you are expected to use the `sqlite3` package which in turn imports the private `_sqlite3` extension package.

```console
$ python -c 'import sqlite3, _sqlite3; print(sqlite3); print(_sqlite3)'
<module 'sqlite3' from '/home/altendky/.pyenv/versions/3.12.4/lib/python3.12/sqlite3/__init__.py'>
<module '_sqlite3' from '/home/altendky/.pyenv/versions/3.12.4/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so'>
```

I looked around and tried changing several names in various configs but did not find any separate control of the import package name vs. the extension module name.

Without having dug into the source, it seems like this _might_ be as simple as a config entry to override the extension module name and code to apply that name to the extension module file writing when it is specified.

Let me know how you feel about this feature.  If it sounds good, I could dig into the source and attempt a PR.

**Comment by messense** [comment]
See https://www.maturin.rs/project_layout#import-rust-as-a-submodule-of-your-project

I don't think we should support the use case like `sqlite3` v.s. `_sqlite3`, it may make sense for standard library to do that, but for third party packages, putting the dylib inside the main package as submodule makes more sense.
