### ISSUE TITLE
actions/runner-images deprecating macos-12

### ISSUE THREAD

**Issue by 2bndy5** [PyO3/maturin#2249]
### Bug Description

I just came across this warning in my CI workflow's summary (originating from job that builds x86_64 target on macos-12):

> A brownout will take place on November 4, 14:00 UTC - November 5, 00:00 UTC to raise awareness of the upcoming macOS-12 environment removal. For more details, see https://github.com/actions/runner-images/issues/10721

So, I was wondering if it is ok to migrate to macos-14 instead? I don't own a Mac to test/build locally.

### Your maturin version (`maturin --version`)

v1.7.4

### Your Python version (`python -V`)

3.12.6

### Your pip version (`pip -V`)

whatever is setup in runner's tool cache (using `python-version: 3.x`)

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Run `maturin generate-ci` on existing project or `maturin new <pkg-name>`
2. Push generated workflow to GitHub remote
3. Review workflow run's summary. Notice the "Annotations" section below the workflow's diagram.

**Comment by 2bndy5** [comment]
If this is not considered a bug and should instead be a discussion, please transfer the issue accordingly.

**Comment by messense** [comment]
https://github.com/PyO3/maturin/pull/2246

**Comment by 2bndy5** [comment]
Oh I didn't see that PR. For the record, I did do a 'macos' search on open/closed issues/discussions. I didn't think to check PRs though. Glad to see you folks are already tracking it. I guess I'll leave this open since it will auto-close when #2246 is merged.
