### ISSUE TITLE
Add Python 3.13 support

### ISSUE THREAD

**Issue by yookoala** [PyO3/maturin#2279]
Python 3.13 has been [released](https://www.python.org/downloads/release/python-3130/) in 7th Oct 2024. It is already scheduled to be shipped by some upcoming distro (e.g. Fedora 41). And since #3821, it is unable to be installed in Python 3.13. Please help to test and implement Python 3.13 support.

**Comment by yookoala** [comment]
Related issue: https://github.com/ModelTC/lightllm/issues/575

**Comment by konstin** [comment]
Hi, the linked issue is due to pyo3, not maturin.
