### ISSUE TITLE
Maturin pulls two versions of zip

### ISSUE THREAD

**Issue by rust1248** [PyO3/maturin#2291]
### Bug Description

Currently, maturin relies on `"zip = 0.6.1"` in its `Cargo.toml`, and on `python-pkginfo`, that pulls `"zip = 1.1.4"`.

Could you update the required version in maturin so that it pulls `"zip = 1"` instead?

### Your maturin version (`maturin --version`)

1.7.4

### Your Python version (`python -V`)

Python 3.10.0

### Your pip version (`pip -V`)

pip 24.2

### What bindings you're using

None

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

````bash
cargo new --lib testing
cd testing/
cargo add maturin
cargo tree | grep zip
```

**Comment by messense** [comment]
We only have one version of `zip` in `Cargo.lock`: https://github.com/PyO3/maturin/blob/ae059a3dca24ceb9b18f4bcdf627187e79fec00c/Cargo.lock#L3065-L3067, we don't want to upgrade it at the moment.

For using maturin as a Rust library/crate, dependency locking can be done by using `cargo update --precise`, please lookup cargo docs for help.
