### ISSUE TITLE
--zig option support for 'maturin develop'?

### ISSUE THREAD

**Issue by ileixe** [PyO3/maturin#2303]
Same as name. Can we support --zig field for maturin develop CLI?

``` sh
$ maturin develop --locked -r --zig 
error: unexpected argument '--zig' found

  tip: to pass '--zig' as a value, use '-- --zig'
```

or any workaround?

**Comment by messense** [comment]
Sorry but I don't see the point of providing zig support in `maturin develop`, it does not need cross compilation, it's for local development only.

**Comment by ileixe** [comment]
We've used use zig build even for local development to isolate libraries, but I understand it's very long tail requirement. Thanks for answer.
