### ISSUE TITLE
Wheel file generated with maturin 1.7.6 doesn't check with twine 5.1.1

### ISSUE THREAD

**Issue by konn** [PyO3/maturin#2335]
### Bug Description

With maturin 1.7.6, the wheel file generated by `pip wheel` won't be validated with `twine check` with twine >= 5.1.1.
The root cause seems that maturin 1.7.6 switched to metadata version to `2.4`, which is not yet supported by twine 5.1.1 - so this might have to be addressed on twine side and it seems that there is [the PR for this](https://github.com/pypa/twine/pull/1180).

So,the reason I opened this issue is not to request fix this issue on maturin side- rather, I intend this issue to be a note for anyone else who encountered this situation. If this is inappropriate, please feel free to close this.

### Your maturin version (`maturin --version`)

1.7.6

### Your Python version (`python -V`)

3.9.20

### Your pip version (`pip -V`)

pip 23.0.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Build PyO3 project with maturin 1.7.6
2. Bundle it with `pip wheel`
3. Feed it to `twine@5.1.1 check`, then it complains as follows:

```
Checking dist/my-package-cp39-cp39-macosx_11_0_arm64.whl: ERROR    InvalidDistribution: Metadata is missing required fields: Name, Version.
         Make sure the distribution includes the files where those fields are specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2, 2.0,
         2.1, 2.2, 2.3.
```

**Comment by messense** [comment]
Yeah I don't think we'll fix it on `maturin` side, but I've pinned it to incease visibility.

**Comment by messense** [comment]
https://github.com/pypa/twine/pull/1180 was merged.
