### ISSUE TITLE
CI fails: "error: the configured PyPy interpreter version (3.7) is lower than PyO3's minimum supported version (3.9)"

### ISSUE THREAD

**Issue by DanielT** [PyO3/maturin#2349]
### Bug Description

I'm using the CI workflow that was generated by maturin 1.7.6 for my project [autosar-data-py](https://github.com/DanielT/autosar-data-py).
I just updated my code to use pyo3-0.23.2, and wanted to publish a new version to pypi.

The CI workflow succeeded on the Macos and Windows platforms, but failed on Linux - Building for CPython >= 3.7 worked correctly on all platforms, since only Linux builds wheels for PyPy.

You should be able to see the log of the failed run here: [musllinux (ubuntu-22.04, aarch64)](https://github.com/DanielT/autosar-data-py/actions/runs/12101022214/job/33740357348#logs)

Ideally I would like to exclude the "bad" PyPy versions without changing the minimum CPython version.

### Your maturin version (`maturin --version`)

1.7.6

### Your Python version (`python -V`)

3.12.7

### Your pip version (`pip -V`)

unknown - this is a github workflow runner

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

I don't know how to manually build wheels for PyPy, but I could probably restart the github CI workflow.

**Comment by DanielT** [comment]
Hi, thanks for fixing this so quickly.

Do I need to wait for you to make a new release of maturin, or is this supposed to start working immediately?
I saw that you have a github workflow to automatically build a new docker image, but when I just restarted my CI job, it failed again.

**Comment by messense** [comment]
You need to wait for a new `maturin` release.

**Comment by PaarthShah** [comment]
https://github.com/matrix-nio/vodozemac-python/pull/14 is blocked on a new `maturin` release as well
