### ISSUE TITLE
Error when parsing patchelf --version

### ISSUE THREAD

**Issue by Timmmm** [PyO3/maturin#2382]
### Bug Description

I get this error:

```
 maturin failed
  Caused by: Failed to parse patchelf version
  Caused by: unexpected end of input while parsing minor version number
```

It is caused because my `patchelf` does not use a semver version:

```
❯ patchelf --version
patchelf 0.12
```

This is on RHEL 8.

[The code](https://github.com/PyO3/maturin/blob/83ebc23e33e28639b71b4d4ddb29e642fa4c0ad1/src/auditwheel/patchelf.rs#L20) uses `parse::<semver::Version>` to parse it, from the [semver crate](https://github.com/dtolnay/semver).

That `parse` function [requires a patch component](https://docs.rs/semver/latest/semver/struct.Version.html#method.parse).

Those docs suggest using `VersionReq` instead but that doesn't seem right. I would maybe just do something like `if only_one_dot(version) { version += ".0" }`. Or just split on dots.

I guess the other option is to give a better error message since apparently Patchelf 0.14 is required and maybe they switched to proper semver by that point.

### Your maturin version (`maturin --version`)

1.5.1

### Your Python version (`python -V`)

3.12.5

### Your pip version (`pip -V`)

23.2.1

### What bindings you're using

bin

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. Install patchelf 0.12.
2. Built a maturin project that requires patchelf.

**Comment by messense** [comment]
Thanks for the report!
