### ISSUE TITLE
Can `maturin` only build packages for installed Python versions?

### ISSUE THREAD

**Issue by andrwcnln** [PyO3/maturin#2386]
The README and the doc both say:

`For pyo3, maturin can only build packages for installed python versions.` 

Is this true? If I understand things correctly, running `maturin build -i pypy3.9` will build a wheel for PyPy 3.9, even if I don't have it installed, by using the bundled sysconfigs.

e.g

![image](https://github.com/user-attachments/assets/a8b33d1b-4dd1-4492-aa7a-e472abc439ab)

**Comment by messense** [comment]
Thanks, that's clearly outdated.
