### ISSUE TITLE
Native mscv compiler vs Xwin auto dectection is false-positive

### ISSUE THREAD

**Issue by girstenbrei** [PyO3/maturin#2394]
### Bug Description

Greets!
First of all, thank you for the great project. Huge work, I really appreciate it.

I'm cross compiling on Linux to windows via the [manylinux2014](https://github.com/pypa/manylinux) images. I use cargo-xwin to do this.

Up until maturin 1.7.7 this basically works out  of the box, really nice. Starting with 1.7.8, and I suspect #2353 , I need to force usage of xwin with `MATURIN_USE_XWIN=1`.

If not set, the error produced is the following:

```
error: linker `link.exe` not found
  |
  = note: No such file or directory (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that Visual Studio 2017 or later, or Build Tools for Visual Studio were installed with the Visual C++ option.

note: VS Code is a different product, and is not sufficient.
```

A minimum reproduceable Dockerfile:

```
FROM quay.io/pypa/manylinux2014_x86_64

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/installer.sh \
 && bash /tmp/installer.sh -y

ENV PATH="/root/.cargo/bin:/usr/lib64/llvm7.0/bin:$PATH"

# Install rust things
RUN rustup target add x86_64-pc-windows-msvc
RUN yum install -y \
    llvm7.0 \
    openssl-devel
RUN cargo install \
    cargo-binstall \
    cargo-make
RUN cargo binstall -y cargo-xwin

# Install python things
RUN pipx install maturin==1.7.8 pip twine
RUN pip install ziglang

# Setup example
RUN mkdir -p /example
WORKDIR /example
RUN maturin init -b pyo3
```

Unfortunately I don't really know how to fix this, sorry.

### Your maturin version (`maturin --version`)

1.7.8

### Your Python version (`python -V`)

Python 3.12

### Your pip version (`pip -V`)

24.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Build the sample Dockerfile
2. Run `maturin build --target x86_64-pc-windows-msvc --interpreter python3.12` as is
3. Set `export MATURIN_USE_XWIN=1`
4. Run `maturin build --target x86_64-pc-windows-msvc --interpreter python3.12` again

**Comment by messense** [comment]
This was fixed in https://github.com/PyO3/maturin/commit/628eb72631f15db1030a104a5363db7578a3776a

**Comment by messense** [comment]
Feel free to test it out using the `ghcr.io/pyo3/maturin:main` image.
