### ISSUE TITLE
cffi shared library filenames are not prefixed by "lib" on linux and darwin

### ISSUE THREAD

**Issue by doug-q** [PyO3/maturin#2396]
### Bug Description

For example see https://cffi.readthedocs.io/en/stable/embedding.html#id12.

Omitting this prefix makes it very challenging to link with these libraries whenever they have a SONAME, which will have the lib prefix. (When do they have a SONAME? it's not clear to me, except  that it's clearly "sometimes").

See https://github.com/PyO3/maturin/pull/1918

### Your maturin version (`maturin --version`)

latest

### Your Python version (`python -V`)

any

### Your pip version (`pip -V`)

any

### What bindings you're using

cffi

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. configure a cffi maturin project
2. maturin develop
3. `$ tree .`

**Comment by messense** [comment]
Labeling this as a feature request to support cffi embedding instead of bug.
