### ISSUE TITLE
bug: erroneously passing `--files` to `uv pip show`

### ISSUE THREAD

**Issue by rorybyrne** [PyO3/maturin#2403]
### Problem

Running `uv run maturin develop --uv` results in the following error:

```
💥 maturin failed
  Caused by: failed to list package files
```

By running `maturin develop` with `-vv` I see the following log line:

`2024-12-21T16:30:11.596155Z DEBUG install_wheel:fix_direct_url: maturin::develop: running "uv" "pip" "show" "--files" "anot" wheel_filename=/var/folders/kn/vh5d742n745f7hhx33qrxvlh0000gn/T/.tmpvuEbEi/anot-0.1.0-cp313-cp313-macosx_11_0_arm64.whl`

This command (`uv pip show --files anot`) is invalid: `uv pip show` does not accept the flag `--files` (although `pip show` does accept `-f/--files`).

### Context

```
✦ ❯ uv run maturin --version
maturin 1.7.8
```

```
✦ ❯ uv --version
uv 0.4.24 (Homebrew 2024-10-17)
```

### Relevant code

(probably)
https://github.com/PyO3/maturin/blob/f12504a226cb50cd19ee1bd1864a3bd8c1f5de62/src/develop.rs#L318

**Comment by rorybyrne** [comment]
Oh, I see my `uv` is out of date. I upgraded it and now it works.

**Comment by mbway** [comment]
sorry about that. In the next release the error message will be clearer: https://github.com/PyO3/maturin/pull/2389

**Comment by rorybyrne** [comment]
Wonderful, thank you.
