### ISSUE TITLE
Cargo path with pyproject.toml

### ISSUE THREAD

**Issue by choco** [PyO3/maturin#241]
Hello,
my project has a structure similar to this
```
- crate_name
 |- src
 |- Cargo.toml
 |- python
   |- build.sh
   |- pyproject.toml
   |- tests
```

The `build.sh` just executes `maturin`
```
maturin build --release --manifest-path ../Cargo.toml
```

But I'd like to use `pyproject.toml` for this.
Unfortunately I'm unable to set the `manifest-path` option from there. Is this something possible? I tried something like this but it doesn't work.

```
[build-system]
requires = ["maturin"]
build-backend = "maturin"

[tool.maturin]
cargo-extra-args = "--manifest-path ../Cargo.toml"
```

**Comment by konstin** [comment]
Could you move the `pyproject.toml` a directory up and run `maturin` in `crate_name` instead of `python`?

**Comment by choco** [comment]
That's the issue, I actually don't want to move it up there :( and would like to keep things separated.

**Comment by konstin** [comment]
For the two cases where you actually need a pyproject.toml (installing from an sdist and installing from git or a directory), the pyproject.toml needs to be in the project root anyway, so I only want to support that case.

**Comment by choco** [comment]
Seems fair, thanks for your help and the quick support :)

**Comment by anthrotype** [comment]
I wish to package a third-party crate that I clone as git submodule and thus I can't/don't want to modify. So I'd like to have my pyproject.toml file in a different directory from the upstream Cargo.toml, and specify a `manifest_path` in my pyproject.toml `[tool.maturin]` section.

**Comment by messense** [comment]
@anthrotype Opened https://github.com/PyO3/maturin/pull/781

**Comment by anthrotype** [comment]
@messense thank you!
