### ISSUE TITLE
Handle restructured text (rst) readme files

### ISSUE THREAD

**Issue by clbarnes** [PyO3/maturin#247]
A lot of python packages use sphinx for documentation, and many of those incorporate the README into the docs page; so many packagers of python projects prefer RST format for the readme.  Indeed, the default readme content type for PyPI is RST. Maturin is currently angled more towards rust packages, and so expects a markdown readme, even though it publishes packages to pypi. As such, the long descriptions on pypi are messed up.

Is there any way around this?

**Comment by funkyfuture** [comment]
Markdown is hard-coded as content-type [here](https://github.com/PyO3/maturin/blob/master/src/metadata.rs#L79-L84). regarding an implementation i wonder whether that field should be mandatory when a description is given, or whether maturin should try to sniff it. i also have doubts whether GFM (or any other) should be the default dialect.

**Comment by clbarnes** [comment]
It would be most familiar if it behaved the same as setuptools (assume rst) but realistically the current behaviour should probably remain the default. Markdown flavour could easily be configurable, again defaulting to current behaviour.

**Comment by clbarnes** [comment]
Closed by #360
