### ISSUE TITLE
upload command

### ISSUE THREAD

**Issue by ijl** [PyO3/maturin#253]
I think it would help to have an upload command that is separate from publish.

This supports the workflow that during CI you build the project (with flags and environmental variables), install it, test it, and then if this is a tagged commit upload the wheel and possibly sdist to PyPI. You need to be sure that the artifact uploaded is the one with the exact flags/options and was tested. `maturin upload <filename>.` would work well.

I think `maturin upload` without an explicit filename is probably not the best default. sdists are created by default so without the user working around it multiple CI jobs would cause an error from PyPI and fail the build. I think that should remain an error by default because PyPI artifacts are immutable and the user shouldn't have the impression something was overwritten. But also e.g. `twine upload` has a `--skip-existing` option. And that could still be useful in maturin to support rerunning CI on a tagged commit to rerun a subset of jobs that failed.

**Comment by konstin** [comment]
I think for those kind of workflows its currently better to use `maturin build` with twine. I've added a note about twine in the readme.
