### ISSUE TITLE
ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by TheBats** [PyO3/maturin#256]
I have an only Rust project named DecDbApi. It contains the following files:

- src directory containing lib.r
```
use pyo3::prelude::*;
use pyo3::wrap_pyfunction;
use std::fs::File;
use std::io::prelude::*;
use std::fs::OpenOptions;
use std::path::Path;

#[pyfunction]
/// Returns the file
fn return_file(a: String) -> PyResult<String> {
   let mut f = File::open(a)?;
   let mut contents = String::new();
   f.read_to_string(&mut contents)?;
   Ok((contents))
}

/// This module is a python module implemented in Rust.
#[pymodule]
fn DecDbAPI(py: Python, m: &PyModule) -> PyResult<()> {
    m.add_wrapped(wrap_pyfunction!(return_file))?;
    Ok(())
}
```
- DecDbApi directory with `__init__ .py`
`from .DecDbApi import return_file`

- Cargo.lock
- Cargo.toml
```
[package]
name = "DecDbApi"
version = "0.1.0"
edition = "2018"

[lib]
name = "DecDbApi"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
features = ["extension-module"]
```

The project builds when I run `maturin build` and installing the wheel using `pip install <wheel name>`, running `pip list` displays the module. Now when I actually want to import it I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python37\lib\site-packages\DecDbApi\__init__.py", line 1, in <module>
   from .DecDbApi import return_file
ImportError: dynamic module does not define module export function (PyInit_DecDbApi)  
```

Changing `__init__.py` to `from .DecDbAPI import return_file`
gives me:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python37\lib\site-packages\DecDbApi\__init__.py", line 1, in <module>
    from .DecDbAPI import return_file
ModuleNotFoundError: No module named 'DecDbApi.DecDbAPI'
```

What should I write in the ` __init__.py` file?

**Comment by TheBats** [comment]
Actually I found the problem, #[pymodule] needs to have the name of the project. In my case DecDbApi

**Comment by messense** [comment]
https://github.com/PyO3/maturin/pull/531 added warning for missing `PyInit_<module_name>` symbol export.

**Comment by achapkowski** [comment]
@TheBats what does the final rs file look like?  
I'm having the same issue.

**Comment by serg06** [comment]
@achapkowski

Replace this:

```rs
#[pymodule]
```

With this:

```rs
#[pymodule]
#[pyo3(name = "some_name")]
```

**Comment by Cheukting** [comment]
I also encounter this problem, I think users expect if not specified, the module name will be the name of the fn or mod, since it is what happened to #[pyfunction]

**Comment by Cheukting** [comment]
Never mind, it is behaving as expected in the current version: PyO3 0.27.2 and maturin 1.11.5
