### ISSUE TITLE
Install data

### ISSUE THREAD

**Issue by shenek** [PyO3/maturin#258]
Hello,

 is it possible to install data into python package?

Using `setuptools` it would've look like something this:
``` pyhton
setup(
    ...
    package_data={"module_name": ["data/*.html"]}
    ...
)
```

**Comment by messense** [comment]
I think with mixed Python/Rust project, if data files are not in `.gitignore` it's already included in the built package? For pure Rust project I'm not sure if it's worth it to implement this, might be better to just convert to a mixed Python/Rust project.
