### ISSUE TITLE
Docker manylinux build error

### ISSUE THREAD

**Issue by wellcaffeinated** [PyO3/maturin#272]
I tried to run the docker command provided in the readme, and it looks like a "latest" tag doesn't exist for the docker image. But that's easy enough to work around. When I do run the command using the "master" tag, i get the following error:

```bash
$ docker run --rm -v $(pwd):/io konstin2/maturin:master build
💥 maturin failed
  Caused by: Cargo metadata failed
  Caused by: Error during execution of `cargo metadata`: error: failed to load source for a dependency on `spdcalc`

Caused by:
  Unable to update /

Caused by:
  failed to read `/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Is this a problem with the docker image?

**Comment by konstin** [comment]
I assume you have a path dependency `spdcalc` that is not mounted into the docker container. The docker image and documentation has also improved at lot in the last year, so please open a new issue if the problem persists
