### ISSUE TITLE
api-key in .travis.yaml is insecure

### ISSUE THREAD

**Issue by droundy** [PyO3/maturin#276]
I believe that this means anyone who wants to can upload binaries to github.  You'd better cancel this OAUTH key and create a new one, but keep it secret this time.

**Comment by programmerjake** [comment]
I could be wrong, but I think those keys are encrypted with travis CI's private key such that only travis CI can decrypt it. I would assume they have checks that prevent you from decrypting them if you're not the repo owner.

**Comment by droundy** [comment]
Could be.  But the travis-ci docs I came across indicated not to include the key in your repository.

**Comment by droundy** [comment]
With your additional information, I came across docs suggesting that you are correct.
