### ISSUE TITLE
build in /tmp by default (how to build somewhere else?)

### ISSUE THREAD

**Issue by fgadaleta** [PyO3/maturin#282]
Is it possible to pass arguments to maturin and build in target directory (otherwise compilation is going to take ages every time)

I currently call maturin like below

```
[build-system]
requires = ["maturin"]
build-backend = "maturin"
```

**Comment by konstin** [comment]
What command exactly are you executing?

**Comment by fgadaleta** [comment]
`pip install .`

(it's a python binding proj.) The rust backend gets built under /tmp during my pip install

**Comment by konstin** [comment]
Unfortunately pip circumvents all caching cargo does, so this will always rebuild everything (See also [this proposal](https://discuss.python.org/t/proposal-adding-a-persistent-cache-directory-to-pep-517-hooks/2303)). You can use `maturin develop` or `maturin build` which do the same as `pip install` except they let cargo use its build cache and build in debug mode by default, which is significantly faster.

**Comment by fgadaleta** [comment]
interesting. thanks.
how would i add develop to my toml file?

**Comment by konstin** [comment]
This doesn't really have anything to do with the toml file. The pyproject.toml entry is only for supporting PEP 517, which is a standard that e.g. pip and tox can use. However PEP 517 lacks some important features (mainly caching and configuration). For development I'd recommend calling maturin directly and ignoring the pyproject.toml.
