### ISSUE TITLE
Expected `python` to be a python interpreter inside a virtualenv

### ISSUE THREAD

**Issue by evandrocoan** [PyO3/maturin#283]
I am setting up a GitHub Actions for [this project](https://github.com/ankitects) however maturin is not failing with the exception:
```
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python.exe
💥 maturin failed
  Caused by: Expected `python` to be a python interpreter inside a virtualenv ಠ_ಠ
```

This is happening because:
1. From a `cmd.exe` Windows shell, the user call `make run`
1. `make` using an Unix Environment, [setup](https://github.com/ankitects/anki/blob/75b7ebb1565672fca3e4d5b4b61822fc8d5581c4/Makefile#L49-L54) a python environment
1. `maturin` check the `VIRTUAL_ENV` variable
   1. If the contents of the variable are `f:\anki\pyenv`, then, everything works 100%
   1. If the contents of the variable are `/cygdrive/f/anki/pyenv`, maturin breaks with: ``Expected `python` to be a python interpreter inside a virtualenv ಠ_ಠ``

This is quite hard to fix because by default, this is the `activate` script `venv` creates:
```sh
File: anki/pyenv/Scripts/activate
40: VIRTUAL_ENV="f:\anki\pyenv"
41: export VIRTUAL_ENV
42: 
43: _OLD_VIRTUAL_PATH="$PATH"
44: PATH="$VIRTUAL_ENV/Scripts:$PATH"
45: export PATH
```

Which is enough to `maturin` work, however, the script is wrong because set sets the Unix PATH variable to `PATH="f:\anki\pyenv:/bin:/usr/bin/:..."` breaking Unix things. The correct is to set the PATH variable to `PATH="/cygdrive/f/anki/pyenv:/bin:/usr/bin/:..."`.

The only way I could find out to fix both `maturin` and unix, is by running `sed`:
```sh
VIRTUAL_ENV="$(pwd)"
VIRTUAL_ENV="$(cygpath -m "$${VIRTUAL_ENV}")"
sed -i -- "s@VIRTUAL_ENV=\".*\"@VIRTUAL_ENV=\"$(pwd)/pyenv\"@g" pyenv/Scripts/activate
sed -i -- "s@export PATH@export PATH; VIRTUAL_ENV=\"${VIRTUAL_ENV}/pyenv\";@g" pyenv/Scripts/activate
```

Making the original script `pyenv/Scripts/activate` become:
```sh
File: anki/pyenv/Scripts/activate
40: VIRTUAL_ENV="/cygdrive/f/anki/pyenv"
41: export VIRTUAL_ENV
42: 
43: _OLD_VIRTUAL_PATH="$PATH"
44: PATH="$VIRTUAL_ENV/Scripts:$PATH"
45: export PATH; VIRTUAL_ENV="F:/anki/pyenv";
```

Now, the PATH variable is correctly set to `PATH="/cygdrive/f/anki/pyenv:/bin:/usr/bin/:..."` and `maturin` can find a Windows path like on `VIRTUAL_ENV="F:/anki/pyenv"`. 

Can `maturin` accept Unix paths like on the `VIRTUAL_ENV` variable to avoid such hacks with the `pyenv/Scripts/activate` script file?

**Comment by konstin** [comment]
This case seems like a rather exotic case. Could you you just pass the location of the python interpreter with `-i`?

**Comment by evandrocoan** [comment]
I tried adding this `-i` things, but `maturin` keeps complaining:
```
FTL_TEMPLATE_DIRS="../qt/ftl" FTL_LOCALE_DIRS="../qt/ftl/repo/desktop" \
        CARGO_TARGET_DIR="target" maturin develop --release --strip -i "F:\anki\pyenv\Scripts\python.exe"
error: Found argument '-i' which wasn't expected, or isn't valid in this context

USAGE:
    maturin.exe develop --release --strip

For more information try --help
```

**Comment by konstin** [comment]
I think that this also one of the cases where it would be better not to use develop and use `maturin build` and `pip install` instead.
