### ISSUE TITLE
UnicodeDecodeError during pip install on ppc64le

### ISSUE THREAD

**Issue by mzpqnxow** [PyO3/maturin#286]
Hello, I'm using an IBM Power Linux machine (ppc64le architecture) and I have found that I am unable to install maturin. This is the issue I have. The system is configured for utf-8 if that helps

I believe the edge-case being exposed here is that there is no binary wheel available for ppc64le architecture which causes some build operations to take place and trigger this issue, but that's speculation for the moment:

```
19:20:13 $ pip3 install maturin
/usr/local/lib/python3.5/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Defaulting to user installation because normal site-packages is not writeable
Collecting maturin
  Downloading maturin-0.7.9.tar.gz (80 kB)
     |################################| 80 kB 580 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8obf2ton
       cwd: /tmp/pip-install-08w_m2sw/maturin
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-4myegval/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-4myegval/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-4myegval/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 75, in <module>
      long_description = fp.read()
    File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4548: ordinal not in range(128)
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8obf2ton Check the logs for full command output.
```

I've tried this with much newer version of `pip3`, I've tried using `python3 -mpip` and I've had no luck with any of them.

I have no issues installing it on other environments

Thoughts on how to properly fix it? I'm happy to PR it if it's just a matter of adjusting encoding settings in the build process and will take a look now at the repo to see if I can save you some time. Until then, this is a blocker on a project for me :<

**Comment by konstin** [comment]
> I believe the edge-case being exposed here is that there is no binary wheel available for ppc64le architecture which causes some build operations to take place and trigger this issue, but that's speculation for the moment:

Yes, that correct; maturin has a setup.py as fallback for architectures where there are no binary wheels, on which it first builds maturin itself.

Which pip version do you use and have you tried upgrading pip? If it's the most recent version, I'd consider this a bug in pip.

**Comment by mzpqnxow** [comment]
@konstin It is in fact the *very* latest version of pip, 20.0.2. For this reason I wouldn't be surprised if it is in fact a bug in pip, considering that it is so bleeding edge.

I can try downgrading pip and see if it is reproducible

Building native code (and even Cython/native code) extensions on ppc64le is always so much fun! I have the privilege and the honor of finding all these bugs and edge-cases :>

**Comment by konstin** [comment]
Could you check if https://github.com/PyO3/maturin/pull/295 fixes that?

**Comment by mzpqnxow** [comment]
@konstin this seems to have fixed the issue .. now I just need to go and track https://github.com/briansmith/ring/issues/104 since I am dying while building ring :)
