### ISSUE TITLE
Unable to build using latest stable cargo/rustc

### ISSUE THREAD

**Issue by mzpqnxow** [PyO3/maturin#287]
I am using:

```
$ rustc -V && cargo -V
rustc 1.38.0 (625451e37 2019-09-23)
cargo 1.38.0 (23ef9a4ef 2019-08-20)
```
When I build this repository from source, I get the following:

```
$ cargo build
...
   Compiling walkdir v2.3.1
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:130:18
    |
130 |             len: bytes.len(),
    |                  ^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
$ 
````

Do I need to downgrade cargo? Or is there a bug to be fixed here? I am not a rust developer so I can't offer much in the way of suggestions, I'm assuming you will know.

This is on a standard x86_64 Lunux (Debian 10) system

**Comment by konstin** [comment]
This is an issue with the bytes crate, not with maturin. 

> Do I need to downgrade cargo?

No, upgrade; Your rust version is too old.
