### ISSUE TITLE
maturin build fails with local dependency

### ISSUE THREAD

**Issue by ethanhs** [PyO3/maturin#299]
I'm not sure if this is just a duplicate of #238 (it seems more severe?), but here is the problem:

I have a local dependency, and unless I pass `--no-sdists`, `maturin build` fails with the inscrutable error log:

```
warning: manifest has no description, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
    Updating crates.io index
error: no matching package named `squaremat` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `scrs v0.7.0 (/home/ethan/search_compiler/native)`
```

Thanks for the great tool :)

**Comment by konstin** [comment]
I think this is an instance of https://github.com/rust-lang/cargo/issues/8151, fixed in https://github.com/rust-lang/cargo/pull/8175.

**Comment by ethanhs** [comment]
Ohh that's quite possible. I searched for something like that but couldn't find anything. I'll try to update my Rust toolchain and check to see if that fixes things.
