### ISSUE TITLE
make it harder to do the wrong thing with manylinux?

### ISSUE THREAD

**Issue by oconnor663** [PyO3/maturin#303]
As part of solving https://github.com/oconnor663/blake3-py/issues/5, I learned that I was using Maturin incorrectly. Previously I thought that `maturin build` automatically took care of all the manylinux details, but now I understand that you need to run the build in a special Docker container to get this right. I think the docs could be clarified around this point (like rewording the remarks about the `--manylinux` flag, and maybe adding some bold/red text highlighting that the Docker command is **really important**), but I also want to suggest an underlying issue: It's easier to do the wrong thing than to do the right thing.

What I mean by this, is that the first thing any new user is going to try (because it's documented prominently) is just `maturin build --release`. Then what happens is they test the result of that build, and they find that it works. It looks like everything's good, and there's no indication that they've produced a broken artifact that's not going to work on other people's systems. The ease of running `maturin build` directly is a footgun on Linux, tempting people to do the wrong thing.

I'm not super familiar with Maturin or manylinux myself, and this project was my first time using both, so I can't tell whether the following is a dumb idea or not, but here's a suggestion: Have `maturin build` (or maybe just `maturin build --release`) return an error by default on Linux. It could say something Clippy style, like "hey, I noticed you're trying to build a Python wheel for Linux, did you know that this will fail on older systems if you don't run the following Docker command instead? Alternatively, if you know what you're doing, please use the `--i-know-what-im-doing` flag." That would make it much less likely that other new users make the same mistake I made.

**Comment by konstin** [comment]
Ideally, maturin would detect which glibc version you linked, and when it is a too recent version for the chosen manylinux target, report an error directing you to the manylinux docker image. However unfortunately I haven't yet figured out how to determine the glibc from rust (and I don't understand how auditwheel is parsing the binaries either). For I now I've added a more prominent note to the readme, but I agree that this is currently a real footgun.

**Comment by Roger** [comment]
> However unfortunately I haven't yet figured out how to determine the glibc from rust

What about:
```rust
use std::ffi::CStr;
use std::os::raw::c_char;

extern {
    fn gnu_get_libc_version() -> *const c_char;
}

fn main() {
    let version = unsafe { 
        gnu_get_libc_version();
        CStr::from_ptr(gnu_get_libc_version()).to_string_lossy().into_owned()
    };
    
    println!("version: {}", version);
}
```

**Comment by oconnor663** [comment]
I think you need to be careful not to do something that's going to crash in a non-glibc environment. The standard library [uses `weak!` linking for this](https://github.com/rust-lang/rust/blob/1.44.1/src/libstd/sys/unix/os.rs#L616-L635), which I'll admit I don't understand very well.

**Comment by konstin** [comment]
@Roger Unfortunately that does not work as maturin is statically linked with musl

**Comment by messense** [comment]
> However unfortunately I haven't yet figured out how to determine the glibc from rust

I've successfully extracted glibc version from dylib using the `goblin` crate. Will try to put together a PR later.

**Comment by messense** [comment]
Opened https://github.com/PyO3/maturin/pull/436
