### ISSUE TITLE
maturin failed   Caused by: The process cannot access the file because it is being used by another process. (os error 32)

### ISSUE THREAD

**Issue by evandrocoan** [PyO3/maturin#306]
```
maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at python.exe
   Compiling pyo3 v0.8.5
   Compiling anki v2.1.26 (F:\anki\rslib)
   Compiling ankirspy v2.1.26 (F:\anki\rspy)
    Finished dev [unoptimized + debuginfo] target(s) in 55.29s
💥 maturin failed
  Caused by: The process cannot access the file because it is being used by another process. (os error 32)
```

What file? Can `maturin` tell me that?

**Comment by konstin** [comment]
The error message should be fixed in 4a6b789. Could you try latest master?

**Comment by evandrocoan** [comment]
I do not know how to reproduce it as I do not know about which file he is complaining about. Also, accordingly to Appveyour, this code is not building: https://ci.appveyor.com/project/konstin/maturin/builds/32633464/job/fk0rhgp37hbyicul#L280

**Comment by konstin** [comment]
Yep, I accidentally pushed the wrong thing and added a fixup commit later. With the current master it should (hopefully) tell you which file is blocked by another process.
