### ISSUE TITLE
Specify python version to use

### ISSUE THREAD

**Issue by Stupremee** [PyO3/maturin#307]
Hey,
I'm currently using maturin to build and publish my Rust + Python project.
I use GitHub actions to publish the project and my worklow matrix contains three different
Python versions to use. (I want support for py 3.6 - 3.8).
I'm using the `--interpreter $(which python)` flag to only build for the current python version.
On MacOs and Linux it works fine, but on windows it fails with this error:
```
Caused by: Python interpreter `/c/hostedtoolcache/windows/Python/3.6.8/x64/python` doesn't exist
```

### Solution
One very nice way to solve this problem would be to add a `--interpreter-version` flag where you can specify the python version in a format like `3.7` and maturin only uses this interpreter for the operation.

**Comment by konstin** [comment]
On windows, it's `where`, not `which`. However on github actions you can just use `--interpreter python` (or maybe `--interpreter python.exe` on windows) because `python` should point to the currently active python version.
