### ISSUE TITLE
Building Rust binaries

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin#311]
Please provide the following information: 
 * Your python version (`python -V`): `3.8.1`
 * Your pip version (`pip -V`): `20.1.1` (latest version)
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): `pyo3 0.10.1`
 * Does `cargo build` work? `yes`
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? `yes`

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

I'm attempting to build a binary crate (no lib!) as a Python package. The desire is to have an executable which is installable through `pip`. I want to use `pip` not `cargo` because it integrates strongly with the python ecosystem, and also then I can distribute prebuilt binaries without users needing to get a Rust toolchain.

Is this use case supported by maturin? Naively trying to make a binary crate and running `maturin develop` fails:

```
maturin develop
🔗 Found pyo3 bindings
⚠  Warning: You're building a library without activating pyo3's `extension-module` feature. See https://pyo3.rs/v0.10.1/
building-and-distribution.html#linking
🐍 Found CPython 3.8 at python.exe
error: no library targets found in package `pyactix`
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml -
-lib --
```

Perhaps a workaround instead of supporting binaries like this is for me to create a `lib`, and then add a Python script to call into it which could be installed similar to `setuptools`'s [scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-scripts-keyword-argument)

I'd be willing to contribute code to support either of these two approaches, if this is something you think is possible. I'm not familar with the maturin codebase so might need a bit of pointing in the right direction.

**Comment by konstin** [comment]
You can select the bindings you want with `-b`/`--bindings`, in this case `-b bin`. 

Building binaries that use pyo3, i.e. which need the `PYTHON_SYS_EXECUTABLE` env and should be packaged as a binary, is currently not implemented.

**Comment by davidhewitt** [comment]
>Building binaries that use pyo3, i.e. which need the PYTHON_SYS_EXECUTABLE env and should be packaged as a binary, is currently not implemented.

Understood. Do you think it would be much work to do this? I'd be willing to contribute this to maturin if it's a manageable task.

**Comment by konstin** [comment]
> Do you think it would be much work to do this? I'd be willing to contribute this to maturin if it's a manageable task.

No, it should boil down to extending [BridgeModel](https://github.com/PyO3/maturin/blob/bc5e051f1409d58ee4ec27b9454dbc01893d65ca/src/build_context.rs#L19-L29) to support bin with and without bindings crate, run pyo3/rust-cpython detection even with bin and finally set `PYTHON_SYS_EXECUTABLE` for the build task.
