### ISSUE TITLE
Invalid arguments for maturin are generated in `build_sdist`

### ISSUE THREAD

**Issue by Stranger6667** [PyO3/maturin#321]
Hi!

I am trying to setup CI for my project using `maturin` and `tox` (which I patch locally to avoid the [bug](https://github.com/tox-dev/tox/issues/1344) mentioned in the maturin's README). Even though there are multiple issues I encountered through the process I am trying to break them down one by one.

After removing `fromlist=[None]` in `__import__` here and here I run `tox -e py37`:

```
error: Found argument '--bindings' which wasn't expected, or isn't valid in this context
```

- Python 3.7.7
- Pip 20.1.1
- PyO3 0.10.1
- `cargo build` works
- PR that reproduces the issue - https://github.com/Stranger6667/jsonschema-rs/pull/54

But it can be reproduced in a simpler way (without passing additional config, like it is in `tox`, since it is ignored in `build_sdist`):

```
python -c 'import maturin; maturin.build_sdist(".tox/dist")'
```

The full output of the command above:

```
Running `maturin pep517 write-sdist --sdist-directory .tox/dist --bindings=cffi --manylinux=off`
error: Found argument '--bindings' which wasn't expected, or isn't valid in this context

USAGE:
    maturin pep517 write-sdist [OPTIONS] --sdist-directory <sdist-directory>

For more information try --help
Command '['maturin', 'pep517', 'write-sdist', '--sdist-directory', '.tox/dist', '--bindings=cffi', '--manylinux=off']' returned non-zero exit status 1
```

My `pyproject.toml`:

```
[build-system]
requires = ["maturin"]
build-backend = "maturin"

[tool.maturin]
bindings = "cffi"
manylinux = "off"
```

As far as I see, `maturin pep517 write-sdist` accepts only `--sdist-directory` and `--manifest-path` options, but the list of options inside `build_sdist` is extended with options that are not compatible with that command. Maybe we can add some separate allowed options list to filter them ... Let me know what do you think :)

**Comment by konstin** [comment]
Hopefully fixed 5f23ae0ee09bee3e1a4465eba361e85c026ac207
