### ISSUE TITLE
setup.py metadata not used?

### ISSUE THREAD

**Issue by hugoledoux** [PyO3/maturin#327]
If I build my wheels with maturin (`maturin build -i python`) are the metadata about my package in `setup.py` supposed to make it to the `METADATA` file? Right now, it seems only very few of the ones in `Cargo.toml` are used.

Do I need to do something special?

**Comment by konstin** [comment]
No, maturin (and also all other PEP 517 tools such as poetry) don't use setup.py but have their own way to manage metadata. In case of maturin this is the Cargo.toml `[package]`, `[lib]` and `[package.metadata.maturin]` metadata as explained in the readme.
