### ISSUE TITLE
"Python interpreter `python` doesn't exist" when python3 works

### ISSUE THREAD

**Issue by programmerjake** [PyO3/maturin#333]
Please provide the following information: 
 * Your python version (`python -V`):
3.7.3
 * Your pip version (`pip -V`):
20.1.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`):
pyo3 0.11.1

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:
```bash
git clone https://github.com/programmerjake/maturin-bug-reproduce
cd maturin-bug-reproduce
docker build --rm .
```

important output:
https://github.com/programmerjake/maturin-bug-reproduce/blob/b5d3be2636cb22468c91acc3dbc9f8166cff6abb/build-log.txt#L219-L225

**Comment by programmerjake** [comment]
Also encountered (sorry, sorta mangled from copying through email):
```
      Caused by: The given list of python interpreters is invalid
      Caused by: python is not a valid python interpreter
      Caused by: Failed to get information from the python interpreter at py
hon
      Caused by: Only python >= 3.5 is supported, while your using python 2.
    Checking for Rust toolchain....
```
which I think is the same bug since I also encountered it when python2.7 is installed in the above Docker script.

**Comment by hombit** [comment]
It is possibly related to #277

**Comment by CNPolaris** [comment]
`maturin build -i python` this command can deal with this problem
