### ISSUE TITLE
Installation in freebsd

### ISSUE THREAD

**Issue by josejachuf** [PyO3/maturin#363]
The error is the same as the one reported in https://github.com/PyO3/maturin/issues/345 but the context is different so I open this issue

In this case I try to install maturin in freebsd, specifically in a freebsd jail, but for the case it does not matter

Freebsd 12.1
python 3.8.6
pip 20.2.4
rustc 1.48.0-nightly
cargo 1.48.0-nightly

maturin is dependency of another package that I want to install: **orjson**

`
pip install maturin`

I paste the full output here:
https://paste.ofcode.org/3bXwgveLzQanDsj354WvAQx

I don't know what other information I can provide

**Comment by josejachuf** [comment]
I removed the rust from the packages system and installed them according to [1]

Now i have:
rustc 1.49.0-nightly (31530e5d1 2020-10-20)
cargo 1.49.0-nightly (79b397d72 2020-10-15)

But I keep getting the same error.

[1] https://freebsd.sh/rust/

**Comment by nijave** [comment]
There seems to be an issue with FreeBSD `ld`. I was able to compile it by installing `gcc9` and using `ld` at `/usr/local/bin/ld`

**Comment by josejachuf** [comment]
Hi @nijave, thanks for your reply

I don't know how you did it. I reproduce the steps of how I did it (in new jail):

```
pkg info
pkg-1.15.10                    Package manager

pkg install -y rust-nightly gcc9 python38
```

> ll /usr/local/bin/
> total 93144
> -rwxr-xr-x  1 root  wheel       101 Oct  3 05:22 2to3-3.8*
> -r-xr-xr-x  1 root  wheel   5405696 Oct  2 22:45 addr2line*
> -r-xr-xr-x  2 root  wheel   5438464 Oct  2 22:45 ar*
> -r-xr-xr-x  2 root  wheel   6196224 Oct  2 22:45 as*
> -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 c++9*
> -r-xr-xr-x  1 root  wheel   5405696 Oct  2 22:45 c++filt*
> -rwxr-xr-x  1 root  wheel  10718944 Oct 18 06:02 cargo*
> -rwxr-xr-x  1 root  wheel    372896 Oct 18 06:02 cargo-clippy*
> -rwxr-xr-x  1 root  wheel   1291656 Oct 18 06:02 cargo-fmt*
> -rwxr-xr-x  1 root  wheel   6716912 Oct 18 06:02 clippy-driver*
> -rwxr-xr-x  1 root  wheel   1146464 Oct  3 03:17 cpp9*
> -rwxr-xr-x  1 root  wheel    166976 Oct 16 22:12 curl*
> -r-xr-xr-x  1 root  wheel      7330 Oct 16 22:12 curl-config*
> -r-xr-xr-x  1 root  wheel   2387256 Oct  2 22:45 dwp*
> -r-xr-xr-x  1 root  wheel     48016 Oct  2 22:45 elfedit*
> -rwxr-xr-x  1 root  wheel     44016 Oct  2 22:22 envsubst*
> -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 g++9*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-ar9*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-nm9*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-ranlib9*
> -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 gcc9*
> -rwxr-xr-x  1 root  wheel    557864 Oct  3 03:17 gcov-dump9*
> -rwxr-xr-x  1 root  wheel    579816 Oct  3 03:17 gcov-tool9*
> -rwxr-xr-x  1 root  wheel    693760 Oct  3 03:17 gcov9*
> -rwxr-xr-x  1 root  wheel     48112 Oct  2 22:22 gettext*
> -r-xr-xr-x  1 root  wheel      5188 Oct  2 22:22 gettext.sh*
> -rwxr-xr-x  2 root  wheel   1150560 Oct  3 03:17 gfortran9*
> -r-xr-xr-x  1 root  wheel   5467136 Oct  2 22:45 gprof*
> -rwxr-xr-x  1 root  wheel        99 Oct  3 05:22 idle3.8*
> -rwxr-xr-x  1 root  wheel     19424 Sep 16 22:10 indexinfo*
> -r-xr-xr-x  4 root  wheel  11672576 Oct  2 22:45 ld*
> -r-xr-xr-x  4 root  wheel  11672576 Oct  2 22:45 ld.bfd*
> -r-xr-xr-x  2 root  wheel   4472288 Oct  2 22:45 ld.gold*
> -rwxr-xr-x  1 root  wheel     48112 Oct  2 22:22 ngettext*
> -r-xr-xr-x  2 root  wheel   5417984 Oct  2 22:45 nm*
> -r-xr-xr-x  2 root  wheel   5553152 Oct  2 22:45 objcopy*
> -r-xr-xr-x  2 root  wheel  18783304 Oct  2 22:45 objdump*
> -r-xr-xr-x  1 root  wheel      2367 Sep 16 22:13 pcre-config*
> -rwxr-xr-x  1 root  wheel     44048 Sep 16 22:13 pcregrep*
> -rwxr-xr-x  1 root  wheel    117808 Sep 16 22:13 pcretest*
> -rwxr-xr-x  1 root  wheel        84 Oct  3 05:22 pydoc3.8*
> -r-xr-xr-x  1 root  wheel     15208 Oct  3 05:22 python3.8*
> -r-xr-xr-x  1 root  wheel      3142 Oct  3 05:22 python3.8-config*
> -r-xr-xr-x  2 root  wheel   5438464 Oct  2 22:45 ranlib*
> -r-xr-xr-x  2 root  wheel    736328 Oct  2 22:45 readelf*
> -rwxr-xr-x  1 root  wheel  24207776 Oct 18 06:02 rls*
> -rwxr-xr-x  1 root  wheel       789 Oct 18 06:02 rust-gdb*
> -rwxr-xr-x  1 root  wheel      1944 Oct 18 06:02 rust-gdbgui*
> -rwxr-xr-x  1 root  wheel      1072 Oct 18 06:02 rust-lldb*
> -rwxr-xr-x  1 root  wheel     15648 Oct 18 06:02 rustc*
> -rwxr-xr-x  1 root  wheel   5656760 Oct 18 06:02 rustdoc*
> -rwxr-xr-x  1 root  wheel   7486520 Oct 18 06:02 rustfmt*
> -r-xr-xr-x  1 root  wheel   5409792 Oct  2 22:45 size*
> -r-xr-xr-x  1 root  wheel   5409792 Oct  2 22:45 strings*
> -r-xr-xr-x  2 root  wheel   5553152 Oct  2 22:45 strip*
> -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-c++9*
> -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-g++9*
> -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-9.3.0*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-ar9*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-nm9*
> -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-ranlib9*
> -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc9*
> -rwxr-xr-x  2 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-gfortran9*


Now created my virtualenv

```
mkdir /entorno
cd /entorno/
python3.8 -m venv venv38
source venv38/bin/activate.csh
pip install pip -U
pip install maturin
```

and ends with the aforementioned error

**Comment by nijave** [comment]
> Hi @nijave, thanks for your reply
> 
> I don't know how you did it. I reproduce the steps of how I did it (in new jail):
> 
> ```
> pkg info
> pkg-1.15.10                    Package manager
> 
> pkg install -y rust-nightly gcc9 python38
> ```
> 
> `ll /usr/local/bin/`
> 
> > total 93144
> > -rwxr-xr-x  1 root  wheel       101 Oct  3 05:22 2to3-3.8*
> > -r-xr-xr-x  1 root  wheel   5405696 Oct  2 22:45 addr2line*
> > -r-xr-xr-x  2 root  wheel   5438464 Oct  2 22:45 ar*
> > -r-xr-xr-x  2 root  wheel   6196224 Oct  2 22:45 as*
> > -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 c++9*
> > -r-xr-xr-x  1 root  wheel   5405696 Oct  2 22:45 c++filt*
> > -rwxr-xr-x  1 root  wheel  10718944 Oct 18 06:02 cargo*
> > -rwxr-xr-x  1 root  wheel    372896 Oct 18 06:02 cargo-clippy*
> > -rwxr-xr-x  1 root  wheel   1291656 Oct 18 06:02 cargo-fmt*
> > -rwxr-xr-x  1 root  wheel   6716912 Oct 18 06:02 clippy-driver*
> > -rwxr-xr-x  1 root  wheel   1146464 Oct  3 03:17 cpp9*
> > -rwxr-xr-x  1 root  wheel    166976 Oct 16 22:12 curl*
> > -r-xr-xr-x  1 root  wheel      7330 Oct 16 22:12 curl-config*
> > -r-xr-xr-x  1 root  wheel   2387256 Oct  2 22:45 dwp*
> > -r-xr-xr-x  1 root  wheel     48016 Oct  2 22:45 elfedit*
> > -rwxr-xr-x  1 root  wheel     44016 Oct  2 22:22 envsubst*
> > -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 g++9*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-ar9*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-nm9*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 gcc-ranlib9*
> > -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 gcc9*
> > -rwxr-xr-x  1 root  wheel    557864 Oct  3 03:17 gcov-dump9*
> > -rwxr-xr-x  1 root  wheel    579816 Oct  3 03:17 gcov-tool9*
> > -rwxr-xr-x  1 root  wheel    693760 Oct  3 03:17 gcov9*
> > -rwxr-xr-x  1 root  wheel     48112 Oct  2 22:22 gettext*
> > -r-xr-xr-x  1 root  wheel      5188 Oct  2 22:22 gettext.sh*
> > -rwxr-xr-x  2 root  wheel   1150560 Oct  3 03:17 gfortran9*
> > -r-xr-xr-x  1 root  wheel   5467136 Oct  2 22:45 gprof*
> > -rwxr-xr-x  1 root  wheel        99 Oct  3 05:22 idle3.8*
> > -rwxr-xr-x  1 root  wheel     19424 Sep 16 22:10 indexinfo*
> > -r-xr-xr-x  4 root  wheel  11672576 Oct  2 22:45 ld*
> > -r-xr-xr-x  4 root  wheel  11672576 Oct  2 22:45 ld.bfd*
> > -r-xr-xr-x  2 root  wheel   4472288 Oct  2 22:45 ld.gold*
> > -rwxr-xr-x  1 root  wheel     48112 Oct  2 22:22 ngettext*
> > -r-xr-xr-x  2 root  wheel   5417984 Oct  2 22:45 nm*
> > -r-xr-xr-x  2 root  wheel   5553152 Oct  2 22:45 objcopy*
> > -r-xr-xr-x  2 root  wheel  18783304 Oct  2 22:45 objdump*
> > -r-xr-xr-x  1 root  wheel      2367 Sep 16 22:13 pcre-config*
> > -rwxr-xr-x  1 root  wheel     44048 Sep 16 22:13 pcregrep*
> > -rwxr-xr-x  1 root  wheel    117808 Sep 16 22:13 pcretest*
> > -rwxr-xr-x  1 root  wheel        84 Oct  3 05:22 pydoc3.8*
> > -r-xr-xr-x  1 root  wheel     15208 Oct  3 05:22 python3.8*
> > -r-xr-xr-x  1 root  wheel      3142 Oct  3 05:22 python3.8-config*
> > -r-xr-xr-x  2 root  wheel   5438464 Oct  2 22:45 ranlib*
> > -r-xr-xr-x  2 root  wheel    736328 Oct  2 22:45 readelf*
> > -rwxr-xr-x  1 root  wheel  24207776 Oct 18 06:02 rls*
> > -rwxr-xr-x  1 root  wheel       789 Oct 18 06:02 rust-gdb*
> > -rwxr-xr-x  1 root  wheel      1944 Oct 18 06:02 rust-gdbgui*
> > -rwxr-xr-x  1 root  wheel      1072 Oct 18 06:02 rust-lldb*
> > -rwxr-xr-x  1 root  wheel     15648 Oct 18 06:02 rustc*
> > -rwxr-xr-x  1 root  wheel   5656760 Oct 18 06:02 rustdoc*
> > -rwxr-xr-x  1 root  wheel   7486520 Oct 18 06:02 rustfmt*
> > -r-xr-xr-x  1 root  wheel   5409792 Oct  2 22:45 size*
> > -r-xr-xr-x  1 root  wheel   5409792 Oct  2 22:45 strings*
> > -r-xr-xr-x  2 root  wheel   5553152 Oct  2 22:45 strip*
> > -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-c++9*
> > -rwxr-xr-x  4 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-g++9*
> > -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-9.3.0*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-ar9*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-nm9*
> > -rwxr-xr-x  2 root  wheel     27880 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc-ranlib9*
> > -rwxr-xr-x  3 root  wheel   1146464 Oct  3 03:17 x86_64-portbld-freebsd12.1-gcc9*
> > -rwxr-xr-x  2 root  wheel   1150560 Oct  3 03:17 x86_64-portbld-freebsd12.1-gfortran9*
> 
> Now created my virtualenv
> 
> ```
> mkdir /entorno
> cd /entorno/
> python3.8 -m venv venv38
> source venv38/bin/activate.csh
> pip install pip -U
> pip install maturin
> ```
> 
> and ends with the aforementioned error

I don't know enough about rust & c to know the correct way, but moving the original /usr/bin/ld and linking to /usr/local/bin/ld made the build work :shrug: 
```
   cd /usr/bin
   mv ld ld.bak
   ln -s /usr/local/bin/ld /usr/bin/ld
```

**Comment by josejachuf** [comment]
@nijave Excellent, this works fine. Thanks very much

Jose

**Comment by nijave** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250783

Not sure if they will backport since this seemed to effect all llvm back to 8
