### ISSUE TITLE
Add `--dry-run` option to maturin-publish command

### ISSUE THREAD

**Issue by MarTango** [PyO3/maturin#377]
Similar to poetry's `publish` command, I think it would be cool if a `--dry-run` option was added which performed all steps except actually uploading build artifacts.

**Comment by ChillFish8** [comment]
Correct me if im wrong but isnt that the whole purpose of `maturing develop [options]`

**Comment by MarTango** [comment]
I'd say that the closest command to this would be `maturin build`. `publish` takes the wheels and uploads to a python package repository. I created this issue because I was trying to figure out how to publish to a private package repository and didn't want to actually push anything.

In the end the issue I was coming across was due to the server not supporting the format that maturin publishes in, so a `--dry-run` option wouldn't have actually been helpful.

I'll leave this issue and a developer who's worked on the `publish` command can determine whether this would be a useful feature or not.

**Comment by konstin** [comment]
I fear there isn't much maturin can do here. publish essentially calls build, gets the credentials and then makes one http request per file to upload. The upload api doesn't have a feature to tell the server to validate the upload without actually publishing it.

**Comment by programmerjake** [comment]
Somewhat related: https://github.com/pypa/warehouse/issues/726
