### ISSUE TITLE
Uninstall previous version of module before rebuilding and installing with maturin develop

### ISSUE THREAD

**Issue by ChillFish8** [PyO3/maturin#381]
Recently i've noticed a couple issues with linting when developing with pure Rust modules (No Extra python bits included), this error ocours when you re-build the module to test with `maturin develop`. I am assuming this only updated the package rather than completely removing it and re-adding it, because the linters are able to detect new methods, remove old methods etc... when the module is first removed then built.

I accept this is probably not a massive issue if you're doing a mix of Python and Rust extensions however the linting can make it alot easier and quicker in places :)

- Tested with PyCharm Professional 2020
- Un-Tested with VSC's Linter (If someone could recreate the above would be much appreciated)

**Comment by konstin** [comment]
I believe the problem is that pycharm doesn't watch and reindex binary files the same way it does with python files. You could look if there's an issue for that on the pycharm issue tracker and vote on that and maybe link the thread here, so I can also vote on it ;)
