### ISSUE TITLE
abi3 binding wheel can only be installed for a specific version of python

### ISSUE THREAD

**Issue by houqp** [PyO3/maturin#382]
Please provide the following information: 
 * Your python version (`python -V`): Tested with python 3.7 and 3.9
 * Your pip version (`pip -V`): pip 20.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? Unix

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

* use latest master branch to build pyo3 wheel
* produced wheel `target/wheels/libname-0.1.0-cp39-abi3-macosx_10_7_x86_64.whl`, which works with python 3.9
* try to install wheel with python 3.7: `ERROR: libname-0.1.0-cp39-abi3-macosx_10_7_x86_64.whl is not a supported wheel on this platform.`
* rename wheel to `libname-0.1.0-cp37-abi3-macosx_10_7_x86_64.whl` fixes installation issue with python 3.7

Dynamic module contained within the wheel is named without python version: `libname/libname.abi3.so`. So I am guessing it's safe for us to upload the same wheel with different names for each version of python 3 to pypi?

**Comment by konstin** [comment]
This depends on https://github.com/PyO3/pyo3/issues/1195 and https://github.com/PyO3/pyo3/pull/1263 being figured out.

**Comment by konstin** [comment]
Fixed in 0.9.0 :tada:
