### ISSUE TITLE
could not find native static library `python3.6m`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by Genarito** [PyO3/maturin#385]
I'm using your manylinux image with a plus command (marked below with a comment):

```dockerfile
FROM quay.io/pypa/manylinux2010_x86_64

ENV PATH /root/.cargo/bin:$PATH
# Add all supported python versions
ENV PATH /opt/python/cp36-cp36m/bin/:/opt/python/cp37-cp37m/bin/:/opt/python/cp38-cp38/bin/:/opt/python/cp39-cp39/bin/:$PATH
# Otherwise `cargo new` errors
ENV USER root

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && python3 -m pip install --no-cache-dir cffi \
    && mkdir /io

ADD . /maturin/

RUN cargo rustc --bin maturin --manifest-path /maturin/Cargo.toml -- -C link-arg=-s \
    && mv /maturin/target/debug/maturin /usr/bin/maturin \
    && rm -rf /maturin

WORKDIR /io

RUN yum install -y gsl-devel  # THIS is the added line

ENTRYPOINT ["/usr/bin/maturin"]
```

As I need GSL installed to compile my program. **If I run maturin develop in my machine It works (with `maturin build --cargo-extra-args="--no-default-features"`)**. But when I try running my custom image with the following command:

`docker run --rm -v $(pwd):/io custom-image build --cargo-extra-args="--no-default-features"` 

I get:

> error: could not find native static library `python3.6m`, perhaps an -L flag is missing?

I've tried with:

`docker run --rm -v $(pwd):/io custom-image build --cargo-extra-args="--no-default-features -- -L /opt/python/cp36-cp36m/bin"`

But it didn't work. I'm missing something or it's a kind of bug in docker image configuration? Any kind of help would be really appreciated

**Comment by Genarito** [comment]
Even removing *m* versions of Python it gets the same error for Python3.8 :(

**Comment by konstin** [comment]
Could it be that `--no-default-features` deactivated the `extension-module` feature?

**Comment by Genarito** [comment]
I don't remember specifically how I fixed that. But what I did was:

- Checked that I was using last version of your Docker image
- Realised that there were other kind of issues with the previous point ([link](https://github.com/PyO3/maturin/issues/411))
- Started using `--no-default-features`

Now It works perfectly, I forgot to close this issue when I fixed it and I regret that :(

**Comment by edwinkys** [comment]
I encountered this issue when putting PyO3 behind an optional feature, `py` and run the build script below on Linux distributions:

```bash
maturin build --features py
```

This issue seems to be caused when `pyo3/extension-module` feature is disabled. I solved this problem by including the feature to `pyproject.toml` file like below:

```toml
[tool.maturin]
features = ["pyo3/extension-module", "py"]
```

I just want to put this out there in case somebody encounter similar issue.
