### ISSUE TITLE
Why Maturin works in local but not installing wheel created in Docker image?

### ISSUE THREAD

**Issue by Genarito** [PyO3/maturin#387]
I've a project ([repo](https://github.com/jware-solutions/ggca)) which I want to use in Python and Rust as libraries. All the code written in Rust and I want to use it from Python, if I build wiith `cargo build`, rename the .so to my project's name ([as official docs indicates](https://pyo3.rs/v0.12.4/index.html#using-rust-from-python)) and open a Python interpreter I can import and **works perfectly**.

If I build inside a virtualenv with Maturin: 

1. Build: `maturin build --manylinux=2014-unchecked`
1. And then installs using wheel: `pip install ggca-0.1.7-cp38-cp38-manylinux2014_x86_64.whl` **It works perfectly**

Now, when I use your Docker image this way: `docker run --rm -v $(pwd):/io custom-image maturin build --skip-auditwheel --manylinux=2014`

Where _custom-image_ is your image with GSL installed to compile my Rust code (It can be built from th Dockerfile in my repo).

It threw some errors about missing .so files which I solved using `auditwheel repair` as I pointed out in [this issue](https://github.com/PyO3/maturin/issues/281) but I'm getting errors about _undefined symbol_:

> ImportError: ..../venv/lib/python3.8/site-packages/ggca.cpython-38-x86_64-linux-gnu.so: undefined symbol: gsl_stats_spearman

Why it's throwing this as both initiial solutions works? What I'm missing? Any light on the subject would be really appreciated, sorry about my english

**Comment by konstin** [comment]
I'm afriad there's nothing maturin can do here. Linking is determined by the gsl crate and auditwheel, so I think this a bug either in gsl-sys or auditwheel (or a bad interaction of the two).
