### ISSUE TITLE
Maturin develop sometimes generates corrupted Python source files

### ISSUE THREAD

**Issue by cswinter** [PyO3/maturin#388]
Please provide the following information: 
 * Your python version (`python -V`): `Python 3.7.2`
 * Your pip version (`pip -V`): `pip 19.2.2`
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): `pyo3 v0.12.4`
 * Does `cargo build` work? Yes

I don't currently have a minimal repro since this only happens sporadically, but it seems that `maturin develop` doesn't always correctly copy Python sources for mixed projects.
Specifically, I have mixed rust/python a maturin project with a file `__init__.py` in the Python subfolder with the following contents:

```
 201   │
 202   │     def __len__(self):
 203   │         path, root = self._resolve()
 204 _ │         return root._obj.len(path)
<EOF>
```

The corresponding file in the pip package installed by `maturin develop` has the following contents:

```
 201   │
 202   │     def __len__(self):
 203   │         path, root = self._resolve()
 204   │         return root._obj.len(path)
 205   │ path)
<EOF>
```

Running `maturin develop` does not change the contents of the file in the pip package.
Manually deleting the file in the pip package and then running `maturin develop` does correctly regenerate the file.

**Comment by cswinter** [comment]
This seems to happen after edits that make the python file shorter. It looks like content of the published file is overwritten by the new content, but the file is not truncated so some trailing content from the previous version remains.

**Comment by konstin** [comment]
This should be fixed by https://github.com/PyO3/maturin/pull/384
