### ISSUE TITLE
Mixed project: Support giving the Rust module a name that is distinct from the Python module 

### ISSUE THREAD

**Issue by gustavgransbo** [PyO3/maturin#391]
Hi, thanks for a very useful package!

I'd like to create a mixed project where the Rust module has a different name from the Python module. For example, I'd like to be ably to specify `lib.name = "_foo"`, but have it be included in a python module called `foo`.

Currently, a mixed project such as  [test-crates/pyo3-mixed](https://github.com/PyO3/maturin/tree/master/test-crates/pyo3-mixed) will support `import pyo3_mixed.pyo3_mixed` for direct access to the Rust module. In my package I'd like to discourage this behavior by giving the native module a private name (e.g. `_foo`).

**Comment by matthieugouel** [comment]
I'm new using maturin and I've been looking for a way to do this without success. 
For instance I would like to have my python project named as `myproject` and the rust produced module named as `core`. 
Then, the functions in core module could be called directly or called in other python functions of the package.

**Comment by messense** [comment]
This is already doable by settings the `[package.metadata.maturin.name]` to `myproject.soname`(multiple dots allowed), see the [pyo3-mixed-submodule](https://github.com/PyO3/maturin/tree/main/test-crates/pyo3-mixed-submodule) for example.

Feel free to reopen or open a new issue if it doesn't work for you.
