### ISSUE TITLE
Rebuild maturin docker image to support new yum mirrors

### ISSUE THREAD

**Issue by alesanfra** [PyO3/maturin#397]
As of Dec 1st, 2020 CentOS 6 reached EOL and it is no longer available from the usual mirrors, so any attempt to install additional packages from yum will result in an error.
This prevents to use the official maturin image to build any project which requires additional yum packages.
The issue was already fixed in the upstream manylinux2010_x86_64 image by switching to https://vault.centos.org mirrors (here's the commit: https://github.com/pypa/manylinux/commit/912b0de218ef606f8262a504ae16fc2340cf4bb9), so one possible solution is to rebuild the maturin image from the latest manylinux2010 one.

**Comment by konstin** [comment]
Could you check with the new 0.9.0 image?

**Comment by alesanfra** [comment]
It works, thanks a lot!
