### ISSUE TITLE
PyO3 "abi3" feature flag has no effect, but "abi3-py3y" flags work as expected

### ISSUE THREAD

**Issue by ravenexp** [PyO3/maturin#400]
Please provide the following information: 
 * Your python version (`python -V`): 3.9
 * Your pip version (`pip -V`): 20.2.4
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version? No
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): `pyo3`
 * Does `cargo build` work? Yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? No

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

Building an extension module with "abi3" feature flag results in a wheel named `foo-0.1.0-cp39-cp39-manylinux2010_x86_64.whl`.

Output:

```
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at python3.9
📦 Built wheel for CPython 3.9 to foo-0.1.0-cp39-cp39-manylinux2010_x86_64.whl
```

Building the same module with "abi3-py36" feature flag results in a wheel named `foo-0.1.0-cp36-abi3-manylinux2010_x86_64.whl`.

Output:

```
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.6
🐍 Not using a specific python interpreter (With abi3, an interpreter is only required on windows)
📦 Built wheel for abi3 Python ≥ 3.6 to foo-0.1.0-cp36-abi3-manylinux2010_x86_64.whl
```

**Comment by kngwyu** [comment]
What is the version of maturin?

**Comment by ravenexp** [comment]
maturin 0.9.0 on linux

**Comment by konstin** [comment]
The background to the problem is that pyo3 allows setting the `abi3` without any minimum version, where it just takes the current python interpreter as minimum version. This doesn't really work with maturin, so I've now solved this by requiring to set a minimum version feature when using `abi3` (which imho is good anyway because it makes the implicit minimum version explicit)
