### ISSUE TITLE
"classifer" should be "classifiers"

### ISSUE THREAD

**Issue by CarlKCarlK** [PyO3/maturin#407]
[Thanks for creating PyO3 and maturin!]

When I set
```
[package.metadata.maturin]
classifier=[
...
```
nothing appears in [Test.PyPi](https://test.pypi.org/project/bed_reader/0.1.5/). It should look like the lower left side of [this](https://pypi.org/project/bed-reader/0.1.2/). I noticed that maturin is also missing classifers on its [PyPi page](https://pypi.org/project/maturin/0.9.0/).

My guess is that the PyPi expects the keyword "classifers" (plural), not the singular "classifer" that maturin seems to be providing.

On a related note, there are other PyPi tags that I would like to use, but are missing from maturin. For example, "url" and "project_urls". It would be great if maturin could allow any tags through.

Thanks,
Carl

**Comment by kngwyu** [comment]
Thanks!
I think 'classifier' is specified in [Metadata 2.1](https://packaging.python.org/specifications/core-metadata/#classifier-multiple-use) and correct. So I guess there's some problem in interaction with PyPI 🤔

**Comment by kngwyu** [comment]
Ah, but I confirmed that `twine` uses classifiers... https://github.com/pypa/twine/blob/3.3.0/twine/package.py#L134
