### ISSUE TITLE
setup.py installs python module to wrong location when `--root` is provided

### ISSUE THREAD

**Issue by ahesford** [PyO3/maturin#408]
The `PostInstallCommand` procedure for [installing the Python module](https://github.com/PyO3/maturin/blob/master/setup.py#L86) is incorrect. Invoking, for example,
```bash
python setup.py install --root=${DESTDIR}
```
to install to an alternative root (or even `--root=/` to be explicit), as often happens in distribution packaging scripts, will put the package directory at `/maturin` rather than `$PYTHON_SITE_PACKAGES/maturin` for whatever `$PYTHON_SITE_PACKAGES` path is appropriate.

Dropping `self.root or ` and relying only on `self.install_lib` may be sufficient, but that requires additional testing.

**Comment by konstin** [comment]
Do you have any documentation that explains how to properly use copy_tree or some major project as reference? Otherwise it's hard to confirm that change this won't break something else that is currently working

**Comment by ahesford** [comment]
It's not about `copy_tree`, it's how the variables are defined. To test, I replaced `PostInstallCommand.run` with
```python
def run(self):
    print('ROOT:', self.root)
    print('INSTALL_LIB:', self.install_lib)
    sys.exit(1)
```
and ran with a few different combinations
```bash
% python setup.py install --prefix=/my/fake/prefix --root=/alternate/root/directory
running install
ROOT: /alternate/root/directory
INSTALL_LIB: /alternate/root/directory/my/fake/prefix/lib/python3.9/site-packages/

% python setup.py install --root=/alternate/root/directory
running install
ROOT: /alternate/root/directory
INSTALL_LIB: /alternate/root/directory/usr/lib/python3.9/site-packages/

% python setup.py install --install-lib=library/installation/path --root=/alternate/root/directory
running install
ROOT: /alternate/root/directory
INSTALL_LIB: /alternate/root/directory/library/installation/path/

% python setup.py install --prefix=/my/fake/prefix
running install
ROOT: None
INSTALL_LIB: /my/fake/prefix/lib/python3.9/site-packages/

% python setup.py install --prefix=/my/fake/prefix --root=/alternate/root/directory --install-lib=/library/installation/path
running install
ROOT: /alternate/root/directory
INSTALL_LIB: /alternate/root/directory/library/installation/path/

% python setup.py install --install-lib=library/installation/path
running install
ROOT: None
INSTALL_LIB: library/installation/path/

% python setup.py install --install-lib= --root=/alternate/root/directory
running install
ROOT: /alternate/root/directory
INSTALL_LIB: /alternate/root/directory/
```
These tests confirm that, within the script, `self.install_lib` is *always* defined, even when not specified on the command line, and it is *always* prefixed with the value of `--root` provided by the user (if any). The value of `--prefix` is ignored if `--install-lib` is provided, otherwise `--install-lib` has a default value of
```python
f'{prefix}/lib/python{python_version}/site-packages'
```

The right thing to do in your `copy-tree` is just
```python
self.copy_tree(
    os.path.join(source_dir, "maturin"),
    os.path.join(self.install_lib, "maturin")
)
```

If some user actually *wants* the maturin package installed at `/some/root/directory`, the right way to achieve it is to call
```bash
setup.py install --root=/some/root/directory --install_lib=
```

**Comment by konstin** [comment]
Thank you for the detailed analysis!
