### ISSUE TITLE
Support published ffi crate

### ISSUE THREAD

**Issue by soulmachine** [PyO3/maturin#409]
This is a feature request rather than an issue.

The example <https://github.com/PyO3/maturin/tree/master/test-crates/cffi-mixed> builds a higher-lever python wrapper on top of a ffi crate, which is a local crate.

Is is possible to build a higher-lever python wrapper on top of a published ffi crate, for example, [https://crates.io/crates/battery-ffi](battery-ffi)? Because people usually will publish a lower-level ffi crate and then build higher-level wrappers in many other languages such as Python and JavaScript. It is better to split the ffi crate and the python wrapper crate completely.

Or is it possible to support soft link to an existing ffi crate? For example, I can git clone the source code of battery-ffi to my local computer, then create a soft link to it from my maturin project.

**Comment by konstin** [comment]
That could be solved with reexporting once https://github.com/rust-lang/rfcs/issues/2771 is solved (see https://github.com/rust-lang/rfcs/issues/2771#issuecomment-362269890 for a workaround), but adding a workaround for that to maturin is unfortunately out of scope.
