### ISSUE TITLE
Basic pip3 install with pyproject.toml fails

### ISSUE THREAD

**Issue by jzrake** [PyO3/maturin#410]
When trying to install a Python package locally with `pip3 install .` and the default `pyproject.toml` file, I get the following error:

```
  Running `maturin pep517 build-wheel -i python`
  Traceback (most recent call last):
    File "<string>", line 19, in <module>
  AttributeError: 'module' object has no attribute 'base_prefix'
  💥 maturin failed
    Caused by: The given list of python interpreters is invalid
    Caused by: python is not a valid python interpreter
    Caused by: Trying to get metadata from the python interpreter 'python' failed
  🔗 Found pyo3 bindings
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'python'] returned non-zero exit status 1
```

This succeeds if the wheel is built instead manually with `maturin pep517 build-wheel -i python3` (note Python3), so this is hopefully an easy fix!

My project builds correctly with `maturin build` and also `maturin develop`.

 * Your python version: `3.9.1`
 * Your pip version: `pip3 21.0.1`
 * The version of the bindings you're using: `pyo3 0.13.1`
 * Does `cargo build` work? Yes

**Comment by messense** [comment]
Can you try running `import sys; print(sys.base_prefix)` with your Python interpreter?

**Comment by messense** [comment]
I guess the easiest fix would be just removing the `VIRTUAL_ENV` special case

https://github.com/PyO3/maturin/blob/6099945a281f45943172d295718cb2ee52bdddcb/src/target.rs#L305-L313

 @konstin  what do you think?

**Comment by jzrake** [comment]
Thanks for the reply! For `sys.base_prefix` I get

/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9

**Comment by messense** [comment]
> This succeeds if the wheel is built instead manually with maturin pep517 build-wheel -i python3 (note Python3),

@jzrake  Does `maturin pep517 build-wheel -i python` work?

**Comment by messense** [comment]
Maybe just use `sys.executable` would avoid the issue?

https://github.com/PyO3/maturin/blob/6099945a281f45943172d295718cb2ee52bdddcb/maturin/__init__.py#L57-L58

like in 

https://github.com/PyO3/maturin/blob/6099945a281f45943172d295718cb2ee52bdddcb/maturin/__init__.py#L136-L139

**Comment by messense** [comment]
@jzrake Can you try:

1. `pip3 install https://github.com/messense/maturin/archive/sys-executable.zip` to install modified maturin
2. `pip3 install --no-build-isolation .` to test if it fixes your issue?

**Comment by jzrake** [comment]
Yes, that does work.

I also happen to be affected by #330, but I was able to force a working build with the above, and using a remote crate location.
