### ISSUE TITLE
maturin develop does not install dependencies

### ISSUE THREAD

**Issue by cassiersg** [PyO3/maturin#414]
When adding a section
```
 [package.metadata.maturin]
requires-dist = ["flask~=1.1.0", "toml==0.10.0"]
```
in Cargo.toml, the dependencies are not installed in the current virtualenv when running `maturin develop`.
Is this the expected behavior ?

If so, it is a bit annoying: the simplest way I found for installing the python dependencies specified in Cargo.toml is to build the wheel and install it. Is there a better solution ? I believe this could be mentioned in the README.

Please provide the following information: 
 * Your python version (`python -V`): 3.7.3
 * Your pip version (`pip -V`): 21.0.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version? This is the latest pip version
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3=0.13
 * Does `cargo build` work? yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? N/A (on linux)

**Comment by konstin** [comment]
Currently, this is missing from develop. If anyone want to implement this, this should be the right location: 

https://github.com/PyO3/maturin/blob/7c43487b188c0b14d20b7e78ddf7075e21b95cc2/src/develop.rs#L44-L49

Check whether `build_context.metadata21.requires_dist` has any entries and if so, call `python -m pip` on all of them (at once, invoking pip is slow). For the test, pick a dependency-less, pure-python package from pypi as test requirement, extend an existing test with that package as requirement and check that the requirement is installed in `check_installed.py`.
