### ISSUE TITLE
Support .pypirc file for uploading

### ISSUE THREAD

**Issue by kngwyu** [PyO3/maturin#415]
It can be helpful to support [twine's pypirc file](https://twine.readthedocs.io/en/latest/#configuration).

**Comment by konstin** [comment]
There is actually already some code to support it, but it [has a bug](https://github.com/PyO3/maturin/pull/374#discussion_r556127780)

**Comment by kngwyu** [comment]
Thank you for pointing it out! I'll dig the problem later.
