### ISSUE TITLE
Missing wheel for manylinux x86_64 in PyPi

### ISSUE THREAD

**Issue by retrry** [PyO3/maturin#428]
Please provide the following information: 
 * Your python version (`python -V`):
 Python 3.9.1
 * Your pip version (`pip -V`):
 pip 20.2.2
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`):
pyo3
 * Does `cargo build` work?

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

For whatever reason manylinux x86_64 version of this package wheel is not published to pypi. For Linux I can only see aarch64 manylinux wheel.

https://pypi.org/project/maturin/#files

**Comment by konstin** [comment]
Fixed now
