### ISSUE TITLE
Cross compilation ignores PYO3_CROSS_PYTHON_VERSION

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#446]
Please provide the following information: 
 * Your python version (`python -V`): host Python 3.9, cross target Python 3.6
 * Your pip version (`pip -V`): -
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? -

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

https://github.com/messense/manylinux2014-cross-arm/runs/1975989661?check_suite_focus=true

Set`PYO3_CROSS_PYTHON_VERSION =3.6` and `PYO3_CROSS_LIB_DIR ` according to https://pyo3.rs/v0.13.2/building_and_distribution.html#cross-compiling , maturin builds fine but produces `cp39-cp39` wheels instead of `cp36-cp36m`.

**Comment by messense** [comment]
It'd be nice if maturin can detect cross target Python version like pyo3 does https://github.com/PyO3/pyo3/blob/c02b71fc09017078034394c1f7d7011bddb5fd03/build.rs#L316

**Comment by messense** [comment]
I guess this is essentially the same issue as https://github.com/PyO3/maturin/issues/375 because of its poor cross compilation support.

**Comment by konstin** [comment]
Unless we require passing extra data, this will require copying (or extracting in a shared crate) of https://github.com/PyO3/pyo3/blob/master/build.rs#L311-L510

For future reference, that part could be used for parsing the version:

```rust
    if let Some(cross_python_version) = env::var_os("PYO3_CROSS_PYTHON_VERSION") {
        if bridge == BridgeModel::Bin {
            bail!("You can't use PYO3_CROSS_PYTHON_VERSION with bin bindings");
        }

        let expr = Regex::new(r"(\d+).(\d+)").unwrap();
        let capture = expr
            .captures(&cross_python_version.to_string_lossy())
            .context(format!(
                "Invalid PYO3_CROSS_PYTHON_VERSION value (should be a version like 3.10): '{}'",
                cross_python_version.to_string_lossy()
            ));
        let context = "Expected a digit";
        let major = capture
            .get(1)
            .unwrap()
            .as_str()
            .parse::<usize>()
            .context(context)?;
        let minor = capture
            .get(2)
            .unwrap()
            .as_str()
            .parse::<usize>()
            .context(context)?;
    }
```

**Comment by messense** [comment]
I have found that you can workaround it by using the same major & minor version of Python for build and target. Eg: https://github.com/messense/manylinux2014-cross-arm/commit/ef575f98be8215ff13200c20c13973fcc561577c
