### ISSUE TITLE
Allow building for non-abi3 pypy wheels when the abi3 feature is enabled

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#460]
Currently, activating the abi3 feature means that you can't build wheels for pypy, as abi3 wheel are incompatible with pypy and the abi3 causes `-i` to be ignored. There should be a solution that both builds for abi3 by defaults and allows building for pypy if requested.

**Comment by kngwyu** [comment]
But doesn't it require upstream support? https://foss.heptapod.net/pypy/pypy/-/issues/3397

**Comment by davidhewitt** [comment]
FYI for PyO3 0.14 we're going to make `abi3` + PyPy a hard error: https://github.com/PyO3/pyo3/pull/1469

**Comment by konstin** [comment]
Sorry, I misphrased that: It should be possible to build a non-abi3 pypy wheels even when the abi3 feature is enabled.

Once pypy also has a stable abi, there should be switch to build for both, but that's something to figure out once we know the details about pypy's abi3
