### ISSUE TITLE
Additional non-path-dep crates are being packaged in workspaces, causing file not found errors

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#462]
> If there are still cases missing, please open an issue!

It does not miss any path dependencies but instead includes crates which are not path dependencies of the root crate being packaged (the Python package crate). Iterating over `resolver.nodes` does not trace the dependencies of the actual crate being packaged but instead includes all *path crates* of the Cargo workspace (https://github.com/PyO3/maturin/commit/3f2a9c532e7cc223636f256e91c033dc79e67a12 does not solve this):

https://github.com/PyO3/maturin/blob/929dbcd2dea3debdad1c34bac2e0f21107633c77/src/source_distribution.rs#L171-L177

I might be able to provide a test case for this issue. I have something like this in mind
```
workspace/python-crate
workspace/generic-library-crate
workspace/helper-tool
```
where `python-crate` depends on `generic-library-crate` but not on `helper-tool`. The current approach seems to unnecessarily include `helper-tool` in the source distribution. In my case `helper-tool` is a binary crate while `generic-library-crate` is a pure library crate. Packaging does then trigger #449 because it tries to package `Cargo.lock` for `helper-binary` rooted in the fact that `cargo package --list` does list `Cargo.lock` for binary crates despite the fact that this file does not exist.

_Originally posted by @koehlma in https://github.com/PyO3/maturin/issues/453#issuecomment-788652178_

**Comment by konstin** [comment]
@koehlma Could you check with v0.10.0-beta.6 whether this is still an issue? I haven't changed the packaging of workspace crates, but now a missing Cargo.lock shouldn't cause errors anymore.

**Comment by koehlma** [comment]
It does no longer complain about the missing `Cargo.lock`, however, it still includes unnecessary crates into the distribution.
