### ISSUE TITLE
PEP 621: Read metadata from project table in pyproject.toml

### ISSUE THREAD

**Issue by konstin** [PyO3/maturin#465]
Currently, metadata is read from Cargo.toml's `[package]` and `[package.metadata.maturin]`. Now with [PEP 621](https://www.python.org/dev/peps/pep-0621/), this should be moved to the standardized pyproject.toml `[project]` instead.

For the implementation, it should still be checked whether `[package.metadata.maturin]` exists and users should be told that this is deprecated and that they should switch to `[project]` in pyproject.toml instead.

**Comment by messense** [comment]
I tried to implement this but not sure how to deal with the overlapping fields between `pyproject.toml` and `Cargo.toml` for example `version`/`readme`/`license` etc.

**Comment by konstin** [comment]
pyproject.toml should take precedence over Cargo.toml (I think that also the case with the current implementation)
