### ISSUE TITLE
Using lib name as package name for publishing

### ISSUE THREAD

**Issue by jafioti** [PyO3/maturin#467]
I have a rust crate that I use natively in rust, and a python wrapper crate using PyO3, named the same as the native crate, but with _py at the end. In the cargo.toml file of the python wrapper crate, I have set the lib name to the name of the native library, because that is what I want it to be imported as. Since this is the python wrapper library,  I need to use the _py name as the package name. This causes problems when I want to publish, as maturin wants to use the package name instead of the lib name. 

Is it possible to use the lib name instead of the package name? I cannot change the package name or else I will have a name collision with the native library.

**Comment by messense** [comment]
Try set `package.metadata.maturin.name` to the lib name. For example https://github.com/messense/fat-macho-rs/blob/0a00fc299988484f4574e6842382e230e2586497/python/Cargo.toml#L23-L24

**Comment by jafioti** [comment]
Thanks for the response. When I add that in, I now get maturin failed Caused by: Username and/or password are wrong even though they are correct. Can the package.metadata.maturin.name be interfering with the username?

**Comment by jafioti** [comment]
Nevermind, the problem was the name was taken on PyPi. Thanks for the help!
