### ISSUE TITLE
maturin build --cargo-extra-args="--locked" ignores --locked option

### ISSUE THREAD

**Issue by nfwvogt** [PyO3/maturin#472]
Thanks for providing maturin and pyo3 they are great packages and so easy to use compared to the standard python packaging process! I just noticed this behaviour that makes dependency pinning in an automated build environment a little trickier: 

Please provide the following information: 
 * Your python version (`python -V`): Python 3.9.1
 * Your pip version (`pip -V`): pip 21.0.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? Yes cargo build --locked fails when Cargo.lock is absent

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

maturin build --cargo-extra-args="--locked" runs successfully even when Cargo.lock is absent.

To reproduce take for example the qoqo_calculator_pyo3 repository (see  also HQSquantumsimulations/qoqo_calculator_pyo3#24 ).

When removing Cargo.lock, maturin build with the --locked option runs without a problem

```shell
rm Cargo.lock
maturin build  --cargo-extra-args="--locked"
```
Output:
> 🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at python3.9
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.60
   Compiling autocfg v1.0.1
   Compiling libc v0.2.85
   Compiling serde_derive v1.0.123
   Compiling cfg-if v1.0.0
   Compiling smallvec v1.6.1
   Compiling serde v1.0.123
   Compiling inventory v0.1.10
   Compiling scopeguard v1.1.0
   Compiling pyo3 v0.13.1
   Compiling unindent v0.1.7
   Compiling paste v1.0.4
   Compiling instant v0.1.9
   Compiling lock_api v0.4.2
   Compiling num-traits v0.2.14
   Compiling indoc v1.0.3
   Compiling quote v1.0.8
   Compiling parking_lot_core v0.8.3
   Compiling parking_lot v0.11.1
   Compiling num-complex v0.3.1
   Compiling pyo3-macros-backend v0.13.1
   Compiling thiserror-impl v1.0.23
   Compiling ctor v0.1.19
   Compiling ghost v0.1.2
   Compiling inventory-impl v0.1.10
   Compiling pyo3-macros v0.13.1
   Compiling thiserror v1.0.23
   Compiling qoqo_calculator v0.1.0
   Compiling qoqo_calculator_pyo3 v0.1.5 (***/qoqo_calculator_pyo3)
    Finished dev [unoptimized + debuginfo] target(s) in 12.13s
📦 Built wheel for CPython 3.9 to ***/qoqo_calculator_pyo3/target/wheels/qoqo_calculator_pyo3-0.1.5-cp39-cp39-macosx_11_0_arm64.whl

Using cargo build or cargo rustc with the --locked option the expected error is produced

```shell
rm Cargo.lock
cargo build --locked
```
Output:

> Updating crates.io index
error: the lock file ***/qoqo_calculator_pyo3/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.

**Comment by konstin** [comment]
You found an interesting edge case there! maturin runs `cargo metadata` before running `cargo build`, but only the feature options were also passed to `cargo metadata`. This should get fixed by #474
