### ISSUE TITLE
How to create a mixed rust/python project with support of python's namespaces?

### ISSUE THREAD

**Issue by Cykooz** [PyO3/maturin#475]
I need to create mixed rust/python project with python's namespace, named as `cykooz.resizer`. 

But `maturin` doesn't seem to support it. I has trying to set `lib.name` in `Cargo.toml` as `"cykooz.resizer.rust_lib"` but this hasn't worked. The command `maturin develop` has returned an error `"invalid character '.' in crate name: 'cykooz.resizer.rust_lib'"`.

Example of the layout I would like to get:

```
cykooz.resizer
├── Cargo.toml
├── cykooz
│   ├── __init__.py
│   └── resizer
│       ├── __init__.py
│       ├── bar.py
│       └── rust_lib.cpython-38-x86_64-linux-gnu.so
├── Readme.md
└── src
    └── lib.rs
```

**Comment by messense** [comment]
I think we can resolve this by supporting dot in `package.metadata.maturin.name`, @konstin what do you think?

**Comment by messense** [comment]
@Cykooz Can you try #489 ? You can install the prerelease with `pip install -U --pre maturin`.
