### ISSUE TITLE
Importing mixed Rust/Python project fails when structured as recommended

### ISSUE THREAD

**Issue by ArniDagur** [PyO3/maturin#490]
The README of this project says the following:
> 
> ## Mixed rust/python projects
> 
> To create a mixed rust/python project, create a folder with your module name (i.e. `lib.name` in Cargo.toml) next to your Cargo.toml and add your python sources there:
> 
> ```
> my-project
> ├── Cargo.toml
> ├── my_project
> │   ├── __init__.py
> │   └── bar.py
> ├── Readme.md
> └── src
>     └── lib.rs
> ```
> 
> maturin will add the native extension as a module in your python folder. When using develop, maturin will copy the native library and for cffi also the glue code to your python folder. You should add those files to your gitignore.
> 
> With cffi you can do `from .my_project import lib` and then use `lib.my_native_function`, with pyo3/rust-cpython you can directly `from .my_project import my_native_function`.
> 
> Example layout with pyo3 after `maturin develop`:
> 
> ```
> my-project
> ├── Cargo.toml
> ├── my_project
> │   ├── __init__.py
> │   ├── bar.py
> │   └── my_project.cpython-36m-x86_64-linux-gnu.so
> ├── Readme.md
> └── src
>     └── lib.rs
> ```
> 
This is the structure I'm using for [`python-adblock`](https://github.com/ArniDagur/python-adblock). The project is written entirely in Rust, but I'm using a mixed Rust/Python project in order to include Python type stubs. I have an `__init__.py` which imports the neccesary symbols from the native module.

However, some of my users have reported that the imports inside `__init__.py` fail as follows:
```
>>> import adblock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/adblock/__init__.py", line 1, in <module>
    from .adblock import __version__, Engine, FilterSet, BlockerResult, UrlSpecificResources
ModuleNotFoundError: No module named 'adblock.adblock'
```
or
```
>>> import adblock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/adblock/__init__.py", line 1, in <module>
    from adblock.adblock import __version__, Engine, FilterSet, BlockerResult, UrlSpecificResources
ModuleNotFoundError: No module named 'adblock.adblock'
```
See https://github.com/ArniDagur/python-adblock/issues/17. As you can see, the result is the same whether I use `from .adblock import ...` or `from adblock.adblock import ...`. I have only managed to reproduce this when the package is installed system wide (`pip3 install .`) and the current working directory is the root of my project (git repository).

Does anyone know what is going on? Am I doing something different from what is described in the `README.md`, or is the advice in the `README.md` wrong in some way?

**Comment by omnivagant** [comment]
I get the same kind of messages when trying to enable tests while upgrading the maturin aport itself  https://gitlab.alpinelinux.org/omni/aports/-/jobs/368096#L691

**Comment by omnivagant** [comment]
I get this when trying to fix and enable tests for the maturin package itself, when trying to upgrade the aport for Alpine Linux https://gitlab.alpinelinux.org/omni/aports/-/jobs/368096#L697

**Comment by messense** [comment]
> I get the same kind of messages when trying to enable tests while upgrading the maturin aport itself https://gitlab.alpinelinux.org/omni/aports/-/jobs/368096#L691

I'm not able to reproduce this with `alpine:edge` aarch64 container locally because alpine uses `aarch64-alpine-linux-musl` target which is not supported by maturin. Is the `alpinelinux/alpine-gitlab-ci` container doing something different than `alpine:edge`?

**Comment by messense** [comment]
> I get the same kind of messages when trying to enable tests while upgrading the maturin aport itself https://gitlab.alpinelinux.org/omni/aports/-/jobs/368096#L691

I was able to reproduce with [the target triple patch](https://gitlab.alpinelinux.org/omni/aports/-/blob/upgrade-maturin/community/maturin/target_triple.patch) applied.

The problem is that maturin didn't take `target_env` into account in `Target::get_shared_platform_tag()`: 
https://github.com/PyO3/maturin/blob/ef37ef2a753557a17798a492d8b2f53920763fbd/src/target.rs#L171-L184 

I was testing on aarch64 platform, it incorrectly named the `.so` file to `aarch64-linux-gnu` which should be `aarch64-linux-musl` according to `imp.get_suffixes()`

```python
/io # ls /io/test-crates/venvs/pyo3-mixed-develop/lib/python3.9/site-packages/pyo3_mixed/
__init__.py                                  __pycache__                                  pyo3_mixed.cpython-39-aarch64-linux-gnu.so  python_module
/io # python
Python 3.9.4 (default, Apr  5 2021, 18:19:42)
[GCC 10.2.1 20210328] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imp
<stdin>:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>>> imp.get_suffixes()
[('.cpython-39-aarch64-linux-musl.so', 'rb', 3), ('.abi3.so', 'rb', 3), ('.so', 'rb', 3), ('.py', 'r', 1), ('.pyc', 'rb', 2)]
```

**Comment by omnivagant** [comment]
Thanks! I'll try!

**Comment by omnivagant** [comment]
I added a [target-musl.patch](https://gitlab.alpinelinux.org/omni/aports/-/blob/upgrade-maturin/community/maturin/target-musl.patch) with your suggestions and similar for the archs we support (or at least want to support, `ppc64le` is limited by the `ring` crate and we currently don't have rust at all for `s390x`), with success for `x86_64` and `aarch64`!

But I'm still having issues with [`x86`](https://gitlab.alpinelinux.org/omni/aports/-/jobs/369483#L1375) (as well [`armv7`](https://gitlab.alpinelinux.org/omni/aports/-/jobs/369487#L1355), but that currently seem to be of another character).

**Comment by messense** [comment]
@omnivagant Can you try this patch instead? https://github.com/messense/maturin/commit/5ad4f178e5176891adedfdb7d6b7da351faaabdc

I was able to get tests passing with it on x86_64 macOS using a `alpine:edge` linux/386 docker container.

**Comment by messense** [comment]
I'm having trouble testing in armv7 `alpine:edge` docker container so I can't look into it.

```bash
/io # cargo build
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
warning: spurious network error (1 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
error: failed to get `anyhow` as a dependency of package `maturin v0.10.2 (/io)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to mmap. Could not write data: Out of memory; class=Os (2)
```

**Comment by messense** [comment]
> ERROR: cffi_mixed-0.1.0-py3-none-linux_armv7l.whl is not a supported wheel on this platform.
> ERROR: cffi_pure-0.1.0-py3-none-linux_armv7l.whl is not a supported wheel on this platform.
> ERROR: pyo3_mixed-2.1.3-cp39-cp39-linux_armv7l.whl is not a supported wheel on this platform.

The error message is a little confusing, `pip` should support them according to `pip debug --verbose`

```bash
# pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
sys.version: 3.9.4 (default, Apr  5 2021, 18:19:42)
[GCC 10.2.1 20210328]
sys.executable: /usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /etc/ssl/certs/ca-certificates.crt
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.4
  CacheControl==0.12.6
  colorama==0.4.4
  contextlib2==0.6.0.post1 (Unable to locate actual module version, using vendor.txt specified version)
  distlib==0.3.1
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.1
  ipaddress==1.0.23
  msgpack==1.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==20.8
  pep517==0.9.1
  progress==1.5
  pyparsing==2.4.7
  requests==2.25.0
  certifi==2020.11.08
  chardet==3.0.4
  idna==2.10
  urllib3==1.26.2
  resolvelib==0.5.4
  retrying==1.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.15.0
  toml==0.10.2
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 33
  cp39-cp39-linux_armv7l
  cp39-abi3-linux_armv7l
  cp39-none-linux_armv7l
  cp38-abi3-linux_armv7l
  cp37-abi3-linux_armv7l
  cp36-abi3-linux_armv7l
  cp35-abi3-linux_armv7l
  cp34-abi3-linux_armv7l
  cp33-abi3-linux_armv7l
  cp32-abi3-linux_armv7l
  py39-none-linux_armv7l
  py3-none-linux_armv7l
  py38-none-linux_armv7l
  py37-none-linux_armv7l
  py36-none-linux_armv7l
  py35-none-linux_armv7l
  py34-none-linux_armv7l
  py33-none-linux_armv7l
  py32-none-linux_armv7l
  py31-none-linux_armv7l
  py30-none-linux_armv7l
  cp39-none-any
  py39-none-any
  py3-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

**Comment by konstin** [comment]
I haven't followed this thread closely (thanks @messense for handling this), but it would be great if those patches could eventually be upstreamed in a way that maturin works on both glibc based linux and on alpine. 

* target_triple.patch: If you could write a comment about what's going on with `.replace("alpine", "unknown")` I'm happy to appliy it.
* disable-no_extensions_module-test.patch: Could you explain why this test fails on alpine?
* use-sysconfig-ext_suffix.patch: @messense upstreamed this in #498
* tests-common-errors.patch: Do you a CI run where a different error happens? That we don't get the lockfile error reliably sounds like either a problem with cargo or with the testuite.

Re powerpc: It works, you just need to [deactivate default features](https://github.com/PyO3/maturin/blob/07a9c064e92f1e106314ef4c7e92af6b5ecd31f7/setup.py#L65-L68).

**Comment by omnivagant** [comment]
Hi!

* target_triple.patch: This is because of how Rust is [downstream-patched](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/rust/alpine-target.patch) by Alpine Linux and that `$arch-alpine-linux-musl` isn't known by the platforms crate. Alpine and musl developers are working together with upstream Rust to get the musl situation sorted but it could take a while.

* disable-no_extensions_module-test.patch: I disabled this test since we seem to get a warning rather than an error, here's the full output for that test
```
---- pyo3_no_extension_module stdout ----
⚠  Warning: You're building a library without activating pyo3's `extension-module` feature. See https://pyo3.rs/v0.13.2/building_and_distribution.html#linking
🔗 Found pyo3 bindings
🐍 Found CPython 3.9 at python
⚠  Warning: Couldn't find the symbol `PyInit_pyo3_no_extension_module` in the native library. Python will fail to import this module. If you're using pyo3, check that `#[pymodule]` uses `pyo3_no_extension_module` as module name
⚠  Warning: No compatible manylinux tag found, using the linux tag instead. You won't be able to upload those wheels to pypi.
📦 Built wheel for CPython 3.9 to /builds/omni/aports/community/maturin/src/maturin-0.10.2/test-crates/pyo3-no-extension-module/target/wheels/pyo3_no_extension_module-2.1.0-cp39-cp39-linux_x86_64.whl
Should have errored
thread 'pyo3_no_extension_module' panicked at 'Should have errored', tests/common/mod.rs:90:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* use-sysconfig-ext_suffix.patch: I'll drop this as soon as there's a new release with it to upgrade to.

* test-common-errors.patch: Sometimes we will get an error, similar to the one that you want to catch, that looks like this
```
"`cargo metadata` exited with an error:     Blocking waiting for file lock on package cache\n    Updating crates.io index\nerror: the lock file /builds/omni/aports/community/maturin/src/maturin-0.10.2/test-crates/lib_with_path_dep/Cargo.lock needs to be updated but --locked was passed to prevent this\nIf you want to try to generate the lock file without accessing the network, use the --offline flag."
thread 'locked_doesnt_build_without_cargo_lock' panicked at '"`cargo metadata` exited with an error:     Blocking waiting for file lock on package cache\n    Updating crates.io index\nerror: the lock file /builds/omni/aports/community/maturin/src/maturin-0.10.2/test-crates/lib_with_path_dep/Cargo.lock needs to be updated but --locked was passed to prevent this\nIf you want to try to generate the lock file without accessing the network, use the --offline flag."', tests/common/mod.rs:90:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

WRT `ppc64le`, cool! I'll give it a try!

**Comment by omnivagant** [comment]
I tried to enable for `ppc64le` and got
```
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/builds/omni/aports/community/maturin/src/maturin-0.10.2/target/release/build/ring-e05f73076e6d300b/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/buildozer/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But I feel more and more that I've hijacked this issue with things that aren't part of the original one. :upside_down_face: The ring crate has an [issue](https://github.com/briansmith/ring/issues/389) for this.

**Comment by messense** [comment]
I've done an armv7 test on Raspberry Pi 3B+ using a `alpine:edge` armv7 docker container, the current set of patches works great and `cargo test` passed. So I'm not sure what's going on with alpine's CI since we don't know what hardware it is running on, is it running with virtualization or emulation.

**Comment by messense** [comment]
> I'm having trouble testing in armv7 `alpine:edge` docker container so I can't look into it.
> 
> ```shell
> /io # cargo build
>     Updating crates.io index
> warning: spurious network error (2 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
> warning: spurious network error (1 tries remaining): failed to mmap. Could not write data: Out of memory; class=Os (2)
> error: failed to get `anyhow` as a dependency of package `maturin v0.10.2 (/io)`
> 
> Caused by:
>   failed to fetch `https://github.com/rust-lang/crates.io-index`
> 
> Caused by:
>   failed to mmap. Could not write data: Out of memory; class=Os (2)
> ```

So I've workaround the issue by manually clone a `crates.io-index` in the container:

```bash
cd ~/.cargo/registry/index
git clone --bare https://github.com/rust-lang/crates.io-index.git github.com-1285ae84e5963aae
```

and `cargo test` passed without any issue. 😂

**Comment by omnivagant** [comment]
Alpine CI builders and package builders are hardware, not sure on the specifics but some server grade. Recently an `armhf` builder was added to CI.

**Comment by omnivagant** [comment]
I haven't dug into it (again) yet but recently enabled `armv7` and `armhf` in an MR over at our gitlab, here are the logs for the jobs failing on these two archs:

https://gitlab.alpinelinux.org/omni/aports/-/jobs/391373

https://gitlab.alpinelinux.org/omni/aports/-/jobs/391374

**Comment by messense** [comment]
> I haven't dug into it (again) yet but recently enabled `armv7` and `armhf` in an MR over at our gitlab, here are the logs for the jobs failing on these two archs:
> 
> https://gitlab.alpinelinux.org/omni/aports/-/jobs/391373
> 
> https://gitlab.alpinelinux.org/omni/aports/-/jobs/391374

Try `pip debug --verbose`

**Comment by omnivagant** [comment]
`pip` isn't used, but I've added `python3 -m sysconfig` for these archs.

https://gitlab.alpinelinux.org/omni/aports/-/jobs/391397

https://gitlab.alpinelinux.org/omni/aports/-/jobs/391398

**Comment by messense** [comment]
@omnivagant pip is used in maturin's tests: https://github.com/PyO3/maturin/blob/5b7efcc7683ee233388e8d6f6e52347ebc85a588/tests/common/integration.rs#L85-L105

**Comment by messense** [comment]
> `pip` isn't used, but I've added `python3 -m sysconfig` for these archs.
> 
> https://gitlab.alpinelinux.org/omni/aports/-/jobs/391397
> 
> https://gitlab.alpinelinux.org/omni/aports/-/jobs/391398

armv7: `Platform: "linux-armv8l"`
armhf: `Platform: "linux-armv8l"`

Interesting. I think we are expecting `Platform: "linux-armv7l"`

**Comment by messense** [comment]
@omnivagant Can you try this patch? https://github.com/messense/maturin/commit/e518086b0927af1dd64b5639d8b60084b792ffe5

**Comment by omnivagant** [comment]
Oh, I didn't think `pip` was available since it isn't in `makedepends` or `checkdepends` or as a dependency of anything there (I think).

Builds are running with your patch now.

**Comment by omnivagant** [comment]
But failed. I'll try to dive into this soon.

**Comment by messense** [comment]
> But failed. I'll try to dive into this soon.

It should be easy to fix. Just need to `pip install cffi` before installing generated wheel.

**Comment by messense** [comment]
> > But failed. I'll try to dive into this soon.
> 
> It should be easy to fix. Just need to `pip install cffi` before installing generated wheel.

@omnivagant New patch: https://github.com/messense/maturin/commit/c024c62f37f65029e6756e415127885c87078a41 Please give it a try.

**Comment by omnivagant** [comment]
Cool! I've been too occupied with other things lately, sorry.

**Comment by stusmall** [comment]
I'm running into this same issue, but I might have a shorter path to reproducing it.  I'm including as much detail as possible because I might be doing something weird in here.  I'm not an experienced python dev and I'm kinda winging it as I go.

1.  Check out maturin @ revision d531e49e6b4d106ac2fa5bac2f4a282570da3731 (head of main when I pulled)
2. Install with `cargo install -f --path .`
3. Goto the cffi-mixed test crate with `cd test-crates/cffi-mixed`
4. Create and activate a venv.  `python3 -m venv venv; source venv/bin/activate`
5. Install tox `pip install tox`
6. Run tox `tox --skip-missing-interpreters` (I'm just using the system interpreter to simply things):
```
(venv) ➜  cffi-mixed git:(main) tox --skip-missing-interpreters
.package create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/.package
.package installdeps: maturin>=0.12,<0.13
py36 create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py38 create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py38
py38 installdeps: pytest
py38 inst: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/.tmp/package/1/cffi_mixed-0.1.0.tar.gz
py38 installed: attrs==21.4.0,cffi==1.15.0,cffi-mixed @ file:///home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/.tmp/package/1/cffi_mixed-0.1.0.tar.gz,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pyparsing==3.0.7,pytest==7.0.1,tomli==2.0.1
py38 run-test-pre: PYTHONHASHSEED='1058416854'
py38 run-test: commands[0] | pytest
================================= test session starts ==================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-1.0.0
cachedir: test-crates/cffi-mixed/.tox/py38/.pytest_cache
rootdir: /home/stusmall/Workspace/maturin
collected 0 items / 1 error

======================================== ERRORS ========================================
______________ ERROR collecting test-crates/cffi-mixed/test_cffi_mixed.py ______________
ImportError while importing test module '/home/stusmall/Workspace/maturin/test-crates/cffi-mixed/test_cffi_mixed.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_cffi_mixed.py:3: in <module>
    import cffi_mixed
cffi_mixed/__init__.py:1: in <module>
    from .cffi_mixed import ffi, lib
E   ModuleNotFoundError: No module named 'cffi_mixed.cffi_mixed'
=============================== short test summary info ================================
ERROR test_cffi_mixed.py
!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!
=================================== 1 error in 0.08s ===================================
ERROR: InvocationError for command /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py38/bin/pytest (exited with code 2)
_______________________________________ summary ________________________________________
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
ERROR:   py38: commands failed
```

For some extra version info:
```
(venv) ➜  cffi-mixed git:(main) python3 --version
Python 3.8.12
(venv) ➜  cffi-mixed git:(main) pip --version
pip 21.1.1 from /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/venv/lib/python3.8/site-packages/pip (python 3.8)
(venv) ➜  cffi-mixed git:(main) tox --version
3.24.5 imported from /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/venv/lib/python3.8/site-packages/tox/__init__.py
```

What is interesting is that if I run `maturin develop` before running `tox --skip-missing-interpreters` then the test works.
```
env) ➜  cffi-mixed git:(main) maturin develop
🍹 Building a mixed python/rust project
🐍 Using CPython 3.8 at /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/venv/bin/python to generate the cffi bindings
📡 Using build options bindings from pyproject.toml
Collecting cffi
  Using cached cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, cffi
Successfully installed cffi-1.15.0 pycparser-2.21
WARNING: You are using pip version 21.1.1; however, version 22.0.3 is available.
You should consider upgrading via the '/home/stusmall/Workspace/maturin/test-crates/cffi-mixed/venv/bin/python -m pip install --upgrade pip' command.
   Compiling cffi-mixed v0.1.0 (/home/stusmall/Workspace/maturin/test-crates/cffi-mixed)
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
📦 Built wheel to /tmp/.tmpsizYQW/cffi_mixed-0.1.0-py3-none-linux_x86_64.whl
🛠  Installed cffi-mixed-0.1.0
(venv) ➜  cffi-mixed git:(main) tox --skip-missing-interpreters
py36 create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py36
SKIPPED: InterpreterNotFound: python3.6
py37 create: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/py37
SKIPPED: InterpreterNotFound: python3.7
py38 inst-nodeps: /home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/.tmp/package/1/cffi_mixed-0.1.0.tar.gz
py38 installed: attrs==21.4.0,cffi==1.15.0,cffi-mixed @ file:///home/stusmall/Workspace/maturin/test-crates/cffi-mixed/.tox/.tmp/package/1/cffi_mixed-0.1.0.tar.gz,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pyparsing==3.0.7,pytest==7.0.1,tomli==2.0.1
py38 run-test-pre: PYTHONHASHSEED='2429669310'
py38 run-test: commands[0] | pytest
================================================================================================ test session starts ================================================================================================
platform linux -- Python 3.8.12, pytest-7.0.1, pluggy-1.0.0
cachedir: test-crates/cffi-mixed/.tox/py38/.pytest_cache
rootdir: /home/stusmall/Workspace/maturin
collected 3 items

test_cffi_mixed.py ...                                                                                                                                                                                        [100%]

================================================================================================= 3 passed in 0.02s =================================================================================================
______________________________________________________________________________________________________ summary ______________________________________________________________________________________________________
SKIPPED:  py36: InterpreterNotFound: python3.6
SKIPPED:  py37: InterpreterNotFound: python3.7
  py38: commands succeeded
  congratulations :)
```


So before I go further, I want to repeat, I'm not a python dev.  So this might be missing the point of the initial bug or misunderstanding how modules work.  But it looks to me that when `from .cffi_mixed import ffi, lib` is run instead of importing from cffi_mixed the wheel it is opening the directory on disk cff_mixed.  When this happens before maturin develop is run, it doesn't have native.so in place, but it does afterwards and so the tests pass

**Comment by messense** [comment]
@stusmall Sorry for the late reply, I think your hypothesis is correct. We've changed the default project template to include a `python` folder in #855 to avoid such issue.

**Comment by oyvindln** [comment]
In case anyone else ends up here like me and have a project in transition where it's not practical to move the python source into a subfolder yet - adding the python packages into ```pyproject.toml``` like so seems to help make them actually be included in the wheel and thus be accessible.

 ```[tool.maturin]
python-packages = ["package1", "package2"] ```
