### ISSUE TITLE
Cannot install maturin version 0.10 on powerPC

### ISSUE THREAD

**Issue by hombit** [PyO3/maturin#502]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.7.6
 * Your pip version (`pip -V`): 21.0.1

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

`pip install maturin` is failed with
```
error: Package `maturin v0.10.2 (/tmp/pip-install-uczp8uih/maturin_059665dad9b0406193ef7a734ea0559b)`
does not have the feature `auditwheel`
```

Probably the problem is with this line which asks for `auditwheel` feature, but there is no such a feature in `Cargo.toml`:
https://github.com/PyO3/maturin/blob/17b6bfa55c867f899a68d384af2252ab12b28fe4/setup.py#L67

**Comment by messense** [comment]
@hombit Can you give #503 a try?

```bash
pip install https://github.com/messense/maturin/archive/refs/heads/ppc-features.zip
```

**Comment by hombit** [comment]
@messense it works! And thank you to return `publish` sub-command
