### ISSUE TITLE
Question regarding rustc override

### ISSUE THREAD

**Issue by ritchie46** [PyO3/maturin#540]
Hi, I am using `maturin` to build a library. Now there has been a change in the `nightly` compiler. 

https://github.com/rust-lang/packed_simd/pull/321

The CI of other projects can fix this by setting a nightly version from before `2021-03-24`. However, if with `maturin==0.9.4` this doesn't help and it keeps failing on the feature gate introduced in a recent feature of `nightly`.

This is the failing [pipeline](https://github.com/pola-rs/polars/runs/2565636604?check_suite_focus=true). Could this be related to anything maturin does? Could I see which `rustc` version maturin gets?

**Comment by messense** [comment]
Can you try `cd py-polars && rustup override set nightly-2021-03-05 && ./tasks.sh test && cd ..` ?

**Comment by ritchie46** [comment]
That did the trick, I assumed that all subdirectories also were included. Thank you.
