### ISSUE TITLE
Support pure python packages

### ISSUE THREAD

**Issue by hombit** [PyO3/maturin#549]
A feature request: support pure python packages along side with pure Rust and/or mixed Python-Rust packages as a part of a single project. It could be useful if we need to have a single project including multiple packages, one of which is a Rust or mixed package, and other are pure Python packages.

**Comment by messense** [comment]
Can you give an example project layout for this feature?

**Comment by hombit** [comment]
Yes, for example we have a project with two packages: 1) package `mixed` which is standard maturin Rust-Python mixed package, and 2) package `pure` which is a plain Python package

```
├── Cargo.toml
├── pyproject.toml
├── mixed           <— Python part of the mixed package
│   ├── __init__.py
├── pure            <— Plain Python package
│   ├── __init__.py
├── src             <— Rust part of the mixed package
│   ├── lib.rs
```

**Comment by messense** [comment]
So you want maturin to build one wheel to contain both the mixed package and the pure Python package?

**Comment by hombit** [comment]
Yes, it would be great

**Comment by messense** [comment]
It's kinda error prone. 

[pymongo does this](https://github.com/mongodb/mongo-python-driver/blob/209d5009e602e84b0b94dd5efd1764c1f2e2460e/setup.py#L300) by combining `bson`, `gridfs` and `pymongo` into `pymongo` distribution, people gets weird errors when they also install [the other bson package from PyPI](https://pypi.org/project/bson/).

**Comment by konstin** [comment]
For multiple top level modules, please build multiple wheels, otherwise you'll get nasty bugs for the reason @messense explained.
