### ISSUE TITLE
Publishing README to PyPI

### ISSUE THREAD

**Issue by djc** [PyO3/maturin#552]
Please provide the following information: 
 * Your python version (`python -V`): 3.9.2
 * Your pip version (`pip -V`): 21.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? N/A

Not sure if this a bug or feature request, but I would like to publish a README to my PyPI project. I tried adding a `pyproject.toml` file with, among other things, a `project.readme` key, but this did not seem to have any effect (neither did any of the other fields I set in `pyproject.toml`, so maybe I'm doing something wrong).

**Comment by messense** [comment]
#465 PEP 621 support is not implemented yet, but you can specific readme in Cargo.toml.

**Comment by djc** [comment]
Maybe "maturin supports building through pyproject.toml" in the README should be rephrased then? It gave me the impression that `pyproject.toml` was supported.

**Comment by messense** [comment]
I think that was talking about [PEP 517](https://www.python.org/dev/peps/pep-0517/).

**Comment by djc** [comment]
Sure, but it's likely still going to be unclear to some part of the audience.

**Comment by konstin** [comment]
Yeah it was clear until pypa changed the meaning of pyproject.toml, now it can mean two different things with varying levels of support by various tools. I mean I'm happy about PEP 621, but we really lack good terms to describe parts of python packaging. We don't even have a name for the modern build system other than `pep517`, which isn't understandable for most users. For that reason I avoided mentioning PEP 517 in the readme, but wouldn't mind clarifying this now that PEP 621 exists.

**Comment by messense** [comment]
@djc I'm working on PEP 621 support in https://github.com/PyO3/maturin/pull/555
