### ISSUE TITLE
whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by spl0i7** [PyO3/maturin#556]
Please provide the following information: 
 * Your python version (`python -V`):
 Python 3.7.3
 * Your pip version (`pip -V`):
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`):
 pyo3

 * Does `cargo build` work? 
 
yes

Using the example from here : https://github.com/PyO3/pyo3/tree/main/examples/maturin-starter

Build completes successfully with this command `maturin build`  which generates `target/wheels/maturin_starter-0.1.0-cp37-cp37m-manylinux_2_24_x86_64.whl`, However I am unable to install this, I get `maturin_starter-0.1.0-cp37-cp37m-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.` I used
`pip3 install target/wheels/maturin_starter-0.1.0-cp37-cp37m-manylinux_2_24_x86_64.whl`

**Comment by messense** [comment]
The pip version is too low. Run `pip install -U pip` to upgrade it.

You can also just build linux wheel with `maturin build --manylinux off`.

**Comment by messense** [comment]
To build wheels for PyPI distribution, you should use a manylinux docker container, see https://github.com/PyO3/maturin#manylinux-and-auditwheel

**Comment by spl0i7** [comment]
That worked, cheers !

**Comment by messense** [comment]
@konstin The manylinux version selection strategy in https://github.com/PyO3/maturin/pull/461 didn't consider that user might have an old pip which doesn't support the best matching manylinux version, maybe we should emit a warning about outdated pip version or fallback to plain linux wheel.

**Comment by konstin** [comment]
If we do that, than warn about the outdated pip version. This could be done in parallel to the cargo invocation, though I'm not sure the benefit justifies the additional complexity. pip already loudly complains if you're using an old version:

```
$ pip install test-crates/pyo3-pure/target/wheels/pyo3_pure-2.1.2-cp36-abi3-manylinux_2_24_x86_64.whl
pyo3_pure-2.1.2-cp36-abi3-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.
You are using pip version 18.1, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
