### ISSUE TITLE
Allow `nightly`

### ISSUE THREAD

**Issue by j-a-m-l** [PyO3/maturin#557]
Please provide the following information: 
 * Your python version (`python -V`): 3.8.5
 * Your pip version (`pip -V`): 20.0.2
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version? No
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`):  PyO3 0.13.2
 * Does `cargo build` work? No
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? Not on Windows

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

Currently there isn't an explicit way to building projects using nightly.
A configuration option on `pyproject.toml` would be a good way to do it. Or, even better, using `rust-toolchain.toml` to choose the toolchain.

There are other ways to do that (https://rust-lang.github.io/rustup/overrides.html). I've already tried successfully setting nightly as the default toolchain before running the commands:
```
rustup default nightly
maturin build
```

Other possible solution is as simple as documenting how to use with nightly as the default toolchain or specify it for a directory.

**Comment by konstin** [comment]
maturin simply runs the `cargo` you have in path, so except for `cargo +nightly`, all other ways from the docs you linked work. Using `rust-toolchain.toml` also works, which is imho better than a pyproject.toml option. From maturin's side we also can't add something like an explicit flag since there are other ways to install rust than rustup.

**Comment by j-a-m-l** [comment]
Yes, `rust-toolchain` works. I'm not sure why on my first attempts it didn't. Thanks for your feedback.
