### ISSUE TITLE
Maturin sdists fails on Windows when using local dependencies

### ISSUE THREAD

**Issue by andfoy** [PyO3/maturin#579]
Please provide the following information: 
 * Your python version (`python -V`): 3.x
 * Your pip version (`pip -V`): 
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): 0.13.2
 * Does `cargo build` work? Yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? Yes

Hi,

I've been trying to provide a source distribution for pywinpty (https://github.com/spyder-ide/pywinpty), which only works for Windows. This package depends on pywinpty_findlib, which is a local dependency that is specified in the Cargo.toml as follows:

```toml
[build-dependencies]
cxx-build = {version = "1.0.45", features = ["parallel"]}
pywinpty_findlib = { version = "=0.3.0", path = "findlib" }
which = "4.1.0"
```

When I try to invoke `maturin sdist`, it fails with the following message:

```
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Failed to add local dependency pywinpty_findlib at /C:/Users/quansight/pywinpty/findlib to the source distribution
  Caused by: Failed to query file list from cargo: exit code: 101
--- Stdout:

--- Stderr:
error: manifest path `/C:/Users/quansight/pywinpty/findlib\Cargo.toml` does not exist
``` 

My guess is that for some reason, forward and backward slashes are getting mixed up, which is preventing the correct localization of the local dependency `Cargo.toml`. This also occurs when calling `maturin build`, but not when calling `maturin develop`

**Comment by messense** [comment]
It seems that on Windows  cargo prints `"pywinpty_findlib 0.3.0 (path+file:///Y:/Downloads/pywinpty/findlib)"`, so the regex here https://github.com/PyO3/maturin/blob/3e2b8b0a0706cdabfbec6b6c7841ffd3c1e63822/src/source_distribution.rs#L175
extracts ` /Y:/Downloads/pywinpty/findlib` with a leading slash which caused the error.

Change the offending line to `let matcher = Regex::new(r"^(.*) .* \(path\+file:///?(.*)\)$").unwrap(); ` could fix this, but then I hit https://github.com/alexcrichton/tar-rs/issues/251 in maturin debug build.

**Comment by messense** [comment]
BTW, your [`pyproject.toml`](https://github.com/spyder-ide/pywinpty/blob/master/pyproject.toml#L1) is missing the `project.name` field which is required by [PEP 621](https://www.python.org/dev/peps/pep-0621/#name).

**Comment by andfoy** [comment]
Hi @messense, thanks for the heads up! I've just updated pywinpty accordingly

**Comment by messense** [comment]
@andfoy Please try [v0.11.0-beta.5](https://github.com/PyO3/maturin/releases/tag/v0.11.0-beta.5): `pip install --pre -U maturin`
