### ISSUE TITLE
Re-import of module causes issues

### ISSUE THREAD

**Issue by aviramha** [PyO3/maturin#591]
* Your python version (`python -V`):  3.8.10
 * Your pip version (`pip -V`): 21.1.2
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): PyO3

The new behavior of maturin is to create `__init__.py` that imports from `.module_name` but in case the module exports `__version__` str - that object isn't exported in the `__init__.py`
This affects both ormsgpack and orjson (pretty much same code base) and probably other libraries that provide `__version__`.
I'm thinking maybe maturin should create `__version__` on it's own. Would such PR be acceptable?

**Comment by messense** [comment]
I think it’s ok.

**Comment by messense** [comment]
I tried with https://github.com/messense/rjsonnet-py, it looks fine?

```python
In [1]: import rjsonnet

In [2]: rjsonnet
Out[2]: <module 'rjsonnet' from '/Users/messense/.pyenv/versions/3.9.2/envs/test/lib/python3.9/site-packages/rjsonnet/__init__.py'>

In [3]: rjsonnet.__version__
Out[3]: '0.4.3'

In [4]: exit
```

**Comment by aviramha** [comment]
That's odd. It does work on older maturin version.. I'm starting to think that's because PyO3 defines __all__

**Comment by aviramha** [comment]
Okay, this is because rjsonnet-py uses pyo3 functions for creating module, which defines `__all__` whilst orjson/ormsgpack doesn't. Python import * doesn't import objects starting with `_` unless `__all__` is defined..
