### ISSUE TITLE
Clarify interaction of Cargo.toml and pyproject.toml metadata

### ISSUE THREAD

**Issue by ethanhs** [PyO3/maturin#593]
I was reading through the readme about PEP 621 support in the [Python metadata section](https://github.com/PyO3/maturin#python-metadata) and I realized that it isn't clear how it interacts with metadata listed in `Cargo.toml`. Which values are sourced from where and what if they disagree?

It appears that they are merged, but it would be nice to have this written down somewhere so it is clear.

EDIT: it seems that these values are merged, and that pyproject.toml takes precedence

**Comment by messense** [comment]
`pyproject.toml` take precedence over `Cargo.toml`. https://github.com/PyO3/maturin/issues/465#issuecomment-823370878

I'll update `README.md` for this later.

**Comment by ethanhs** [comment]
Thank you!
