### ISSUE TITLE
Can't install wheels generated using maturin

### ISSUE THREAD

**Issue by vitalije** [PyO3/maturin#600]
Ubuntu linux 20.04 
Python 3.9.6
pip 21.2.1
I am using pyo3 0.14.1  bindings.

I can easily build my python extension module using `cargo build --release`. And I can import resulting binary module.
I've tried to create wheel package from my project using `maturin build --strip --release` and everything seems to work ok. I can see in `target/wheels/` folder newly created wheel package. However when I try to install that package in the new virtual environment using `pip install .../_minileo-0.1.0-...manylinux_2_24_x86_64.whl`, I am getting an error:
```
ERROR: Invalid requirement: '-minileo==0.1.0'
```
My python extension module name is `_minileo` and its current version is 0.1.0.

I've tried also to unzip the resulting wheel and I can import my extension module from the unpacked files, and it seems to work without any problem. Just installing using `pip install` fails with the above error.

**Comment by messense** [comment]
Do you have a public repository for reproduction of the issue?

**Comment by vitalije** [comment]
Never mind. While preparing to publish my library, to allow you to reproduce the issue, I've found out that building using docker image solved my issue. Sorry for making noise.

**Comment by vitalije** [comment]
Now, I can install resulting wheel on Linux, but I can't install it on Windows.

I've published this morning library under new name [leocore](https://repo.computingart.net/leocore/)

I've also published the resulting wheels that I've got using `maturin build` inside docker and directly on linux, as well as directly on Windows.

Linux wheels can be installed, but wheel for windows won't install.
When I unzip wheel for windows and extract `leocore/leocore.pyd`, I can successfully import that module in both Python3.6 and Python3.7. 

There must be something wrong with the wheels, because library works fine when imported directly.

**Comment by messense** [comment]
> Linux wheels can be installed, but wheel for windows won't install.

Can you please provide more information for example pip error messages on this?

**Comment by vitalije** [comment]
```
C:\Users\vital>cd c:\work\leocore\

c:\work\leocore>maturin build --release
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.6
🐍 Using CPython 3.7 at python.exe to generate to link bindings (With abi3, an interpreter is only required on windows)
   Compiling leocore v0.1.0 (C:\work\leocore)
    Finished release [optimized] target(s) in 57.07s
📦 Built wheel for abi3 Python ≥ 3.6 to c:\work\leocore\target\wheels\leocore-0.1.0-cp36-abi3-win_amd64.whl

c:\work\leocore>
c:\work\leocore>python -m venv example

c:\work\leocore>example\Scripts\activate

(example) c:\work\leocore>pip install target\wheels\leocore-0.1.0-cp36-abi3-win_amd64.whl
leocore-0.1.0-cp36-abi3-win_amd64.whl is not a supported wheel on this platform.
You are using pip version 19.0.3, however version 21.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(example) c:\work\leocore>
```

As I said before, if I manually unpack content of the generated wheel package, I can import  `leocore.pyd` module and it works just fine.

**Comment by messense** [comment]
@vitalije Could you please run `pip debug --verbose` and paste the output here?

**Comment by vitalije** [comment]
```
(example) c:\work\leocore>pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 21.2.3 from c:\work\leocore\example\lib\site-packages\pip (python 3.7)
sys.version: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
sys.executable: c:\work\leocore\example\scripts\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): c:\work\leocore\example\lib\site-packages\pip\_vendor\certifi\cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  appdirs==1.4.4
  CacheControl==0.12.6
  colorama==0.4.4
  distlib==0.3.2
  distro==1.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  html5lib==1.1
  msgpack==1.0.2 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==21.0
  pep517==0.11.0
  progress==1.5
  pyparsing==2.4.7
  requests==2.26.0
  certifi==2021.05.30
  chardet==4.0.0
  idna==3.2
  urllib3==1.26.6
  resolvelib==0.7.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==1.0.3
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 27
  cp37-cp37m-win_amd64
  cp37-abi3-win_amd64
  cp37-none-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  py37-none-win_amd64
  py3-none-win_amd64
  py36-none-win_amd64
  py35-none-win_amd64
  py34-none-win_amd64
  py33-none-win_amd64
  py32-none-win_amd64
  py31-none-win_amd64
  py30-none-win_amd64
  cp37-none-any
  py37-none-any
  py3-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

(example) c:\work\leocore>
```

**Comment by vitalije** [comment]
Hm, I had to upgrade pip in order to perform `pip debug --verbose`, and when I did, now I can install generated wheel.
It seems that generated wheels are not compatibile with earlier versions of pip.

**Comment by messense** [comment]
It could be that the old version of pip doesn't support abi3 wheels.

Closing as resolved.

**Comment by wasuaje** [comment]
> @vitalije Could you please run `pip debug --verbose` and paste the output here?
> 
> Please also try to upgrade pip to latest version: `pip install -U pip`.

This solved the issue for me!
