### ISSUE TITLE
Documentation for "abi3" usage

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin#603]
The PyO3 guide currently just links users to the PR which implemented abi3 support in maturin: https://pyo3.rs/v0.14.1/building_and_distribution.html#py_limited_apiabi3

It would be nice if the maturin README had a section on abi3 so that the guide could link to it.

(Looks like it should be quite simple, maturin automatically detects the feature and enables abi3 as a result?)

**Comment by aganders3** [comment]
> @aganders3 Thanks, we're writing a guide in #619, feel free to comment or send PRs to that branch.

Thanks - the mdbook guide seems like a good idea. I created a PR to that branch with some suggestions/drafts and I will work on this as I find time.

**Comment by messense** [comment]
https://maturin-guide.netlify.app/bindings.html#py_limited_apiabi3
