### ISSUE TITLE
`pyproject.toml` missing `build-backend` crashes maturin

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin#607]
I ran `maturin develop` in PyO3's `word-count` example, and got this crash:

```
$ maturin develop
💥 maturin failed
  Caused by: Failed to parse Cargo.toml into python metadata
  Caused by: pyproject.toml is invalid
  Caused by: pyproject.toml is not PEP 517 compliant: missing field `build-backend` at line 1 column 1
```

This is incorrect. Quoting PEP 517:

> If the pyproject.toml file is absent, or the build-backend key is missing, the source tree is not using this specification, and tools should revert to the legacy behaviour of running setup.py (either directly, or by implicitly invoking the `setuptools.build_meta:__legacy__` backend).

I guess there's an open question what to do in projects that have a `setup.py` file. `maturin` could raise a different error which is more correct, or it could give a warning that it's ignoring the missing `build-backend` key and building anyway?

**Comment by messense** [comment]
Thanks for reporting, I think we could allow missing `build-backend` and print a warning instead if `setup.py` isn't found.

**Comment by konstin** [comment]
I think we should warn independent of setup.py, because a build-backend that isn't maturin leads to confusing behaviour (`maturin develop` works, but `pip install .` and tox do something totally different)

**Comment by messense** [comment]
@davidhewitt Please give maturin v0.11.3-beta.3 a try, it should allow missing `build-backend`. Will add the warning later in a dedicated PR.

**Comment by davidhewitt** [comment]
Can confirm it works nicely - many thanks :+1:
