### ISSUE TITLE
Contribution guidelines and documentation related to development environment setup

### ISSUE THREAD

**Issue by Smurphy000** [PyO3/maturin#610]
### Issue
I am currently trying to setup a local environment to build and run tests for the project so that I may contribute. In order for me to get some tests running, I had to take a look at the yml file to realize I needed my own virtualenv for running the tests with `cargo test`. I am still getting one more failure with  `error: could not compile pyo3-no-extension-module` and I have not yet figured out how to resolve this.

Using wsl2, Ubuntu 20.04, python 3.8.10

I was reading through this [doc](https://pyo3.rs/v0.14.2/building_and_distribution.html#linking) but I am still not sure what I may need to do

### Suggestion
A document containing information related to setting up a dev environment for the project

Thanks

**Comment by messense** [comment]
Documentation is sparse currently, a contributing guide is definitely needed. Meanwhile, this readme section have some information about maturin development setup: https://github.com/PyO3/maturin#code

**Comment by messense** [comment]
https://maturin-guide.netlify.app/contributing.html
