### ISSUE TITLE
Cannot upload pypy wheel to PyPI

### ISSUE THREAD

**Issue by matusf** [PyO3/maturin#611]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.8
 * Your pip version (`pip -V`): pip 20.0.2 
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): `cffi`
 * Does `cargo build` work?: yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?: n/a
 * maturin version: 0.11.2

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

---
I tried to build & publish wheels for [`z-base-32`](https://github.com/matusf/z-base-32/) package. However, uploading pypy wheel to PyPI fails with 502 status code - Bad Gateway. Upload the wheels with `twine` [worked fine](https://pypi.org/simple/z-base-32/).

```
$ maturin publish
🐍 Using CPython 3.8 at python3 to generate the cffi bindings
    Finished release [optimized] target(s) in 0.01s
📦 Built wheel to /home/matus/code/gh/matusf/z-base-32/target/wheels/z_base_32-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Please enter your username:
Please enter your password: 
🚀 Uploading 1 packages
💥 maturin failed
  Caused by: 💥 Failed to upload "z_base_32-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl" (5.0 KB)
  Caused by: Failed to upload the wheel with status 502 Bad Gateway: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.9</center>
</body>
</html>
```
EDIT:
Or maybe ths is not pypy wheel. I'm now confused. It does not look like [pypy wheel name](https://www.python.org/dev/peps/pep-0427/#file-name-convention) :confused:

**Comment by messense** [comment]
I don't think `502 Bad Gateway` is maturin's fault, even if maturin did done something wrong, PyPI should respond with 4xx instead of 5xx.

Anyway, can you upload the wheel as an attachment here so I can take a look?

**Comment by matusf** [comment]
Sure, here it is: [z_base_32-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.zip](https://github.com/PyO3/maturin/files/7027798/z_base_32-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.zip)

**Comment by messense** [comment]
I've tried upload it with `maturin upload` command to test.pypi.org and [it works fine](https://test.pypi.org/simple/z-base-32/). `maturin publish` uses the same code to upload.

```bash
maturin upload -r https://test.pypi.org/legacy/ ~/Downloads/z_base_32-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl
Please enter your username:
messense
Please enter your password:
🚀 Uploading 1 packages
✨ Packages uploaded successfully
```

I think it was a temporary failure of PyPI service.
