### ISSUE TITLE
Maturin seems to make PyPI failed to render Unicode meta data

### ISSUE THREAD

**Issue by hongquan** [PyO3/maturin#612]
Please provide the following information: 
 * Your python version (`python -V`): 3.9.5
 * Your pip version (`pip -V`): 21.2.4
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3
 * Does `cargo build` work? Yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

- Use Docker maturin to build and publish my lib to:  https://pypi.org/project/defity/0.1.3/
- What wrong is that, PyPI has encoding error when showing Vietnamese in metadata (my name).

  
![image](https://user-images.githubusercontent.com/314607/130846193-6a5101e5-1dc8-4917-bc9b-f22cc5d844fe.png)

- Other my pure Python libs, packaged by Poetry, don't have this problem: https://pypi.org/project/vietnam-provinces/

**Comment by messense** [comment]
Seems like it's caused by https://github.com/PyO3/python-pkginfo-rs/blob/17523fac9af6c50080f9e087b9fd271c49bd2ec8/src/metadata.rs#L84

**Comment by messense** [comment]
Please give v0.11.5-beta.4 a try, you can install it with `pip install -U --pre maturin`.
