### ISSUE TITLE
Maturin is not able to auto-discover Python 3.10 on Windows

### ISSUE THREAD

**Issue by bernardelli** [PyO3/maturin#614]
Auto-discover can't find Python 3.10 on Windows.

I believe that the regex expression `Regex::new(r" -(\d).(\d)-(\d+)(?: .*)?")` at [this line](https://github.com/PyO3/maturin/blob/8e3edd6d3988e4111b86c986f853a106594c2b34/src/python_interpreter.rs#L96) is responsible for that.
Shouldn't it be `Regex::new(r" -(\d).(\d+)-(\d+)(?: .*)?")`?.

For context, see the script below:

```powershell
choco install -y rust-ms --no-progress
# install stable python versions
foreach ($PyVersion in @("3.6.8", "3.7.9", "3.8.10", "3.9.6"))
      { choco install -my python --version=${PyVersion} --no-progress }
# install python previews
foreach ($PyVersion in @("3.10.0-rc1"))
      { choco install -my python --version=${PyVersion}  --pre --no-progress }
pip install --no-cache-dir maturin
maturin publish [...]
```

I don't thing this is relevant, but I'm using pip version 21.1.3 and pyo3 bindings.

By the way, thanks for the amazing work!

**Comment by messense** [comment]
Would you like send a PR to fix it?

**Comment by bernardelli** [comment]
Sure, I am going to do it in the next few days.
