### ISSUE TITLE
Ability to provide type hints?

### ISSUE THREAD

**Issue by DavidVentura** [PyO3/maturin#618]
Hi!
Is it possible to provide type hints (either automatically or manually generated) within the wheels?
This is currently not working for my simple project using rust-cpython

**Comment by messense** [comment]
Currently only manually provided type stub files are supported. You can take a look at this example project  https://github.com/PyO3/maturin/tree/main/test-crates/pyo3-pure, all you need to provide is a `<project_name>.pyi` file for pure Rust layout project.

**Comment by DavidVentura** [comment]
Fantastic!!! thank you
