### ISSUE TITLE
Issue with wheel on armv7l device

### ISSUE THREAD

**Issue by DavidVentura** [PyO3/maturin#620]
Please provide the following information: 
 * Your python version (`python -V`): 3.5.2
 * Your pip version (`pip -V`): 20.3.4
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?: can't use anything newer than 20.3.4 on py3.5
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): rust-cpython
 * Does `cargo build` work? yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? not applicable

Hi

I am not sure if this is an issue on maturin or on my device. The wheel builds and installs fine, but I can't import it:
```bash
pip3 install --platform manylinux2014_armv7l --only-binary=:all: pykeepass-rs==0.1.9  --target vvv
```
importing with `-v`
```python
>>> import pykeepass_rs
# code object from '/home/phablet/vvv/pykeepass_rs/__pycache__/__init__.cpython-35.pyc'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/phablet/vvv/pykeepass_rs/__init__.py", line 2, in <module>
    from .pykeepass_rs import *
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'pykeepass_rs.pykeepass_rs'
```

system info:
```bash
phablet@ubuntu-phablet:~/vvv$ uname -a
Linux ubuntu-phablet 3.4.0-cyanogenmod-g2b465f7f #8 SMP PREEMPT Thu Jul 22 14:22:48 CEST 2021 armv7l armv7l armv7l GNU/Linux

phablet@ubuntu-phablet:~/vvv$ ldd pykeepass_rs/pykeepass_rs.cpython-35m-x86_64-linux-gnu.so 
        libtls-padding.so => /usr/lib/arm-linux-gnueabihf/libtls-padding.so (0xb6e42000)
        libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb6e1a000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6d2e000)
        /lib/ld-linux-armhf.so.3 (0xb6f33000)

phablet@ubuntu-phablet:~/vvv$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23
```

same ~wheel~ code and build process on different architectures is fine.

Do you have any hints for me? in general or on how to debug further

**Comment by messense** [comment]
Looks like the wheel name is wrong: `pykeepass_rs/pykeepass_rs.cpython-35m-x86_64-linux-gnu.so` it should be `ldd pykeepass_rs/pykeepass_rs.cpython-35m-arm-linux-gnueabihf.so `.

Can you describe how did you compile that wheel? Natively or cross compiled?

**Comment by DavidVentura** [comment]
wow! good eye

1- i forked your manylinux-cross and added 3.5 support [here](https://github.com/DavidVentura/pykeepass-rs/blob/master/Dockerfile_arm)
2- in that container, i run:
```
docker run --env RUSTFLAGS='-C target-feature=+v7,+neon -C linker=armv7-unknown-linux-gnueabihf-gcc' -v ~/git/pykeepass-rs:/io arm build --release --strip -i python3.5 --target armv7-unknown-linux-musleabihf
```

**Comment by messense** [comment]
Can you paste the full maturin build log here or somewhere? FYI, maturin currently only have decent cross compilation support for pyo3 because cross compilation requires some coordination between maturin and the Python binding crate. I haven't tried do cross compilation with rust-cpython yet.

**Comment by DavidVentura** [comment]
full log looks happy:
```
$  docker run --env RUSTFLAGS='-C target-feature=+v7,+neon -C linker=armv7-unknown-linux-gnueabihf-gcc' -v ~/git/pykeepass-rs:/io arm build --release --strip -i python3.5 --target armv7-unknown-linux-musleabihf 
🔗 Found rust-cpython bindings
🐍 Found CPython 3.5m at python3.5
   Compiling typenum v1.13.0
   Compiling version_check v0.9.3
   Compiling autocfg v1.0.1
   Compiling memchr v2.4.1
   Compiling libc v0.2.101
   Compiling cfg-if v1.0.0
   Compiling regex-syntax v0.6.25
   Compiling crossbeam-utils v0.8.5
   Compiling crc32fast v1.2.1
   Compiling opaque-debug v0.3.0
   Compiling adler v1.0.2
   Compiling constant_time_eq v0.1.5
   Compiling arrayvec v0.5.2
   Compiling lazy_static v1.4.0
   Compiling arrayref v0.3.6
   Compiling subtle v2.4.1
   Compiling block-padding v0.2.1
   Compiling cpython v0.6.0
   Compiling base64 v0.13.0
   Compiling byteorder v1.4.3
   Compiling paste v1.0.5
   Compiling xml-rs v0.8.4
   Compiling hex-literal v0.3.3
   Compiling generic-array v0.14.4
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling miniz_oxide v0.4.4
   Compiling blake2b_simd v0.5.11
   Compiling rust-argon2 v0.8.3
   Compiling aho-corasick v0.7.18
   Compiling time v0.1.44
   Compiling secstr v0.4.0
   Compiling regex v1.5.4
   Compiling cipher v0.3.0
   Compiling digest v0.9.0
   Compiling crypto-mac v0.11.1
   Compiling block-buffer v0.9.0
   Compiling flate2 v1.0.20
   Compiling aes v0.7.5
   Compiling chacha20 v0.7.2
   Compiling twofish v0.6.0
   Compiling salsa20 v0.8.1
   Compiling block-modes v0.8.1
   Compiling hmac v0.11.0
   Compiling sha2 v0.9.5
   Compiling chrono v0.4.19
   Compiling keepass v0.4.9 (https://github.com/davidventura/keepass-rs?branch=next#260f5eea)
   Compiling python3-sys v0.6.0
   Compiling pykeepass-rs v0.1.9 (/io)
    Finished release [optimized] target(s) in 15.97s
📖 Found type stub file at pykeepass_rs.pyi
📦 Built wheel for CPython 3.5m to /io/target/wheels/pykeepass_rs-0.1.9-cp35-cp35m-manylinux_2_17_armv7l.manylinux2014_armv7l.whl
```

but as you saw the wheel contains a file named x86_64

```
$ unzip -v target/wheels/pykeepass_rs-0.1.9-cp35-cp35m-manylinux_2_17_armv7l.manylinux2014_armv7l.whl 
Archive:  target/wheels/pykeepass_rs-0.1.9-cp35-cp35m-manylinux_2_17_armv7l.manylinux2014_armv7l.whl
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     144  Defl:N       98  32% 2021-09-06 12:07 a9d4cd5b  pykeepass_rs-0.1.9.dist-info/METADATA
     129  Defl:N      114  12% 2021-09-06 12:07 b3c39fb3  pykeepass_rs-0.1.9.dist-info/WHEEL
      28  Defl:N       30  -7% 2021-09-06 12:07 1dcfcb62  pykeepass_rs/__init__.py
     351  Defl:N      192  45% 2021-09-06 12:07 abf52bc1  pykeepass_rs/__init__.pyi
       0  Defl:N        2   0% 2021-09-06 12:07 00000000  pykeepass_rs/py.typed
  764336  Defl:N   381646  50% 2021-09-06 12:07 4def4a0e  pykeepass_rs/pykeepass_rs.cpython-35m-x86_64-linux-gnu.so
     572  Defl:N      368  36% 2021-09-06 12:07 806525af  pykeepass_rs-0.1.9.dist-info/RECORD
--------          -------  ---                            -------

```

i'd love to use pyo3 but it is 3.6 only (

**Comment by messense** [comment]
So the `-i python3.5` argument actually uses the host Python 3.5 which is x86_64 so maturin gets x86_64 so name here https://github.com/PyO3/maturin/blob/58e2381b3267e37dc585258fff3d9cd380801d23/src/python_interpreter.rs#L384-L407

In pyo3 we use a `PYO3_CROSS_LIB_DIR` to specify cross compile target Python library directory to read the target Python's so name conversion. https://pyo3.rs/v0.14.5/building_and_distribution.html#cross-compiling

**Comment by messense** [comment]
Maybe you can try the workaround mention here: https://github.com/PyO3/maturin/issues/375#issuecomment-758642486

**Comment by messense** [comment]
[crossenv](https://crossenv.readthedocs.io/en/latest/) may also be useful for you.

**Comment by DavidVentura** [comment]
you mean that i could try running `maturin` in `crossenv` inside docker? i'll give that a shot.
for an immediate solution i will manually unpack the file and repack it with the correct name (this works fine) and will evaluate the 2 options in a bit

do you think the limitations of the cross-support can be more clearly labeled somewhere? maybe a wiki page with a collection of these links ? it'd be super useful

**Comment by messense** [comment]
> do you think the limitations of the cross-support can be more clearly labeled somewhere? maybe a wiki page with a collection of these links ? it'd be super useful

I'll write something in https://github.com/PyO3/maturin/pull/619
