### ISSUE TITLE
Support token from CLI

### ISSUE THREAD

**Issue by AleCandido** [PyO3/maturin#621]
I was looking for a way to authenticate on PyPI (`publish` and `upload` subcommands) through a token, instead of username/password.

Looks like maturin supports token (from #374) but only as environment variable:

https://github.com/PyO3/maturin/blob/58e2381b3267e37dc585258fff3d9cd380801d23/src/main.rs#L101

Furthermore it is undocumented on README.md .

Is it possible to have a `--token` option for `publish` and `upload` to provide the token to maturin?

**Comment by messense** [comment]
I think you can just do it with `maturin publish -u __token__ -p YOUR_PYPI_TOKEN`?

**Comment by AleCandido** [comment]
I will try, if it's going to work it's perfect :D

**Comment by AleCandido** [comment]
> I think you can just do it with `maturin publish -u __token__ -p YOUR_PYPI_TOKEN`?

It's actually working, my bad.
