### ISSUE TITLE
Unknown variant `2010` for `manylinux`

### ISSUE THREAD

**Issue by arturomf94** [PyO3/maturin#636]
* Python 3.7
 * Latest pip
 * cffi==1.14.6
 * Does `cargo build` work? yes

Using something like the following in the `pyproject.toml`:

```
[tool.maturin]
bindings = "cffi"
manylinux = "2010"
```

Returns:

```
Caused by: pyproject.toml is not PEP 517 compliant: unknown variant `2010`, expected one of `Manylinux`, `Musllinux`, `Linux` for key `tool.maturin.manylinux` at line 9 column 1
```

Shouldn't this be parsed into `Ok(PlatformTag::manylinux2010())` [here](https://github.com/PyO3/maturin/blob/b1a57a62209bd61d1865329fe727dfb939b9a2d2/src/auditwheel/platform_tag.rs#L77)?

**Comment by messense** [comment]
Thanks for reporting, fixed in #637

**Comment by arturomf94** [comment]
> Thanks for reporting, fixed in #637

Thanks! :)

**Comment by messense** [comment]
@arturomf94  to make sure it works for you, I'm releasing a new pre-release: https://github.com/PyO3/maturin/actions/runs/1277002862

Please give it a try when it's published to PyPI, then you can install it with `pip install -U --pre maturin`.

**Comment by arturomf94** [comment]
Thank you so much. It worked perfectly! :tada:
