### ISSUE TITLE
No automatic musllinux compliance

### ISSUE THREAD

**Issue by tmtenbrink** [PyO3/maturin#649]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.9.5
 * Your pip version (`pip -V`): Pip 21.3
 * The version of the bindings you're using, if any: PyO3 0.14.5

I'm running the latest version of maturin (0.11.5) and saw that recently maturin should be able to auto-detect musl (#642). However, when I try to build [my project](https://github.com/tmtenbrink/rustfrc) using maturin:

```
poetry run maturin build --release --compatibility musllinux_1_2
```

I still seem to get the same issue as in #642 even though I think the fix is supposed to be in the most recent version.

```
💥 maturin failed
  Caused by: Error ensuring musllinux_1_2 compliance
  Caused by: Your library is not musllinux_1_2 compliant because it links the following forbidden libraries: ["libgcc_s.so.1"]
```

I am running the rust:alpine docker image, with default apk python3, etc.

I am able to fix the problem using auditwheel manually (below the output of auditwheel show, auditwheel repair then fixes it):
```
rustfrc-1.0.2-cp39-cp39-linux_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_4.2.0', 'GCC_3.0', 'GCC_3.3'}

The following external shared libraries are required by the wheel:
{
    "libc.musl-x86_64.so.1": "/lib/ld-musl-x86_64.so.1",
    "libgcc_s.so.1": "/usr/lib/libgcc_s.so.1"
}

In order to achieve the tag platform tag "musllinux_1_2_x86_64" the
following shared library dependencies will need to be eliminated:

libgcc_s.so.1
```

**Comment by messense** [comment]
See https://github.com/PyO3/maturin/issues/642#issuecomment-938534308

maturin haven't implemented the repairment part of auditwheel yet, so it can't bundle `libgcc_s.so.1` in built wheel to make it musllinux compliant.

**Comment by messense** [comment]
> Somewhat related question, is there a reason the musllinux wheels for maturin itself are not published to PyPI?

I've opened https://github.com/PyO3/maturin/issues/650 to track this.

**Comment by messense** [comment]
musllinux_1_1 wheels for maturin is now available in v0.11.6-beta.1: https://pypi.org/project/maturin/0.11.6_beta.1/#files

**Comment by tmtenbrink** [comment]
> maturin haven't implemented the repairment part of auditwhAeel yet, so it can't bundle `libgcc_s.so.1` into built wheel to make it musllinux compliant.

Ah my apologies I misinterpreted the problem in that issue, anyways thanks for the quick reply and your work on this library, it makes building Rust/Python libraries (which imo are going to be used a lot for scientific purposes in the future) a blast! You can close this if you want because if I understand you correctly it is not actually intended that maturin fixes the wheels itself?

**Comment by messense** [comment]
> You can close this if you want because if I understand you correctly it is not actually intended that maturin fixes the wheels itself?

It will great if we implement wheel repair eventually in maturin, so let's keep it open to track the process.

**Comment by jnicholls** [comment]
Thanks for tracking this issue, I too am running into the issue of libgcc being linked. I'm just skipping auditwheel for now, but looking forward to seeing the auto-repair functionality!
