### ISSUE TITLE
Using PyClasses from common dependencies

### ISSUE THREAD

**Issue by dennybritz** [PyO3/maturin#654]
I'm not sure if this is a `maturin` or `pyo3` issue but since it's related to compilation I figured it fits better here. I have the following setup for a project:

- A - Rust library the exposes types tagged with `pyclass`
- B - cdylib that depends on A and exposes a `pymodule`
- C - cdylib that depends on A and exposes a `pymodule`

So, the types from `A`  a shared across `B` and `C` and I want to pass an output from a function in `B` as an input to a function in `C`. But Python complains:

```
argument 'arg1': '"ClassA' object cannot be converted to 'ClassA'"
```

This seems to happen because compiling B with `maturin develop` and then C with `maturin develop` it seems to recompile dependency A. How exactly is class equivalency determined?

I am compiling the projects separately as follows, but they are all in the same cargo workspace and refer to each other with `path=...`

```bash
cd b
maturin develop --release

cd c
maturin develop --release
```

Is there a way to somehow compile them together and use the same class types?

**Comment by messense** [comment]
I don't know if pyo3 supports sharing common `pyclass` this way. cc @davidhewitt

**Comment by dennybritz** [comment]
Thanks, I didn't come across https://github.com/PyO3/pyo3/issues/1444 when I searched. This seems to cover the issue so feel free to close this one. Looks like this isn't easily possible for now and I need to aggregate everything in a single crate.
