### ISSUE TITLE
maturin build doesn't generate the package

### ISSUE THREAD

**Issue by Dylan-Kerler** [PyO3/maturin#659]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.8.0
 * Your pip version (`pip -V`): pip 21.3.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): py03
 * Does `cargo build` work? yes

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:

```
$ maturin develop
```

This works. When i do:

```
import simlib
help(simlib)
```

i get the correct output:

![screenshot_942](https://user-images.githubusercontent.com/37438950/139832090-bb0fd987-31f3-4ac3-be97-8d5919631bf9.png)

However, when I do `maturin build` everything seems to break.

```
$ deactivate
$ rm -rf ./simlib/simlib.cpython-38-x86_64-linux-gnu.so
$ maturin build --release
$ pip install target/wheels/simlib-0.1.0-cp38-cp38-manylinux_2_24_x86_64.whl --force-reinstall
```

Then in python

```
import simlib
help(simlib)
```

Now it says that there is nothing in the simlib package and it's now empty:

![screenshot_943](https://user-images.githubusercontent.com/37438950/139834009-c3680611-37e7-4789-b998-acb1bd442024.png)

**Comment by messense** [comment]
Does using `simlib.IndicatorConfig` work? I think it's because maturin build generated a `__init__.py` while `develop` doesn't. See https://github.com/PyO3/maturin/pull/558

**Comment by Dylan-Kerler** [comment]
It says that doesn't exist:

```
AttributeError: module 'simlib' has no attribute 'IndicatorConfig'
```

**Comment by messense** [comment]
Can you share your project layout? We need a way to reproduce the issue, is there a public source code repository?

**Comment by Dylan-Kerler** [comment]
Managed to fix it by changing to:

```
from simlib import simlib
```

Thanks for your help!
