### ISSUE TITLE
pyo3-log depends on v0.1.14, after updating crate pyo3 to 0.1.15, results in 'Expected exactly one pyo3 dependency, found 2'

### ISSUE THREAD

**Issue by Congyuwang** [PyO3/maturin#662]
Seems that `pyo3-log` crate dependency of my project depends on v0.14, and I updated my crate to depend on v0.15.

![截屏2021-11-04 上午9 39 08](https://user-images.githubusercontent.com/52687642/140243189-c1218af6-3248-40a1-8b45-fd7e6059fecf.png)

This gives me two versions of pyo3 in Cargo.lock, and causes Maturin failed to build and 'Expected exactly one pyo3 dependency, found 2'.

Can this two-pyo3 issue be addressed by Maturin, or does it mean that all dependencies involving pyo3 must rely on the same version of pyo3 to work together?

```
❯ maturin develop --release    
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Expected exactly one pyo3 dependency, found 2
```

**Comment by Congyuwang** [comment]
Seems to me for now, different version of pyo3 indeed cannot be mixed together. cargo build successfully, but importing the library gives me
```
Fatal Python error: PyThreadState_Get: no current thread

[1]    57813 abort      python
```

**Comment by messense** [comment]
So I guess this is working as expected.
