### ISSUE TITLE
authors and license fields in pyproject.toml not accepted

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [PyO3/maturin#685]
Hey,

Just got started using maturin, so maybe this is a noob/dumb question but I had to remove the `license` and the `authors` field from my `pyproject.toml` file to run `maturing build`. E.g. with the authors field it would otherwise complain with:
```
❯ maturin build
💥 maturin failed
  Caused by: pyproject.toml is invalid
  Caused by: pyproject.toml is not PEP 517 compliant: invalid type: string "Marius Kriegerowski <marius.kriegerowski@gmail.com>", expected struct People at line 29 column 1
```

This is what the first few lines looked like before:

```
[project]
name = "konnoohmachi"
version = "0.1.4"
description = "Spectral smoothing in rust/python"
authors = [
    "Marius Kriegerowski <marius.kriegerowski@gmail.com>",
]
license = "MIT"
```

If the fields have to be removed from pyproject toml I find the error message very misleading.

**Comment by messense** [comment]
[PEP 621](https://www.python.org/dev/peps/pep-0621/#authors-maintainers) requires the `authors` field to be an array of tables with 2 keys: `name` and `email`.

Agreed the error message could be better.

**Comment by messense** [comment]
https://www.python.org/dev/peps/pep-0621/#license license field requires to be a table.

> A practical string value for the license key has been purposefully left out to allow for a future PEP to specify support for SPDX expressions (the same logic applies to any sort of "type" field specifying what license the file or text represents).

**Comment by messense** [comment]
Added a paragraph about SPDX license expressions in user guide: https://maturin.rs/metadata.html#add-spdx-license-expressions

**Comment by DimitriPapadopoulos** [comment]
See #2700 for a documentation update after adding PEP 639 support.
