### ISSUE TITLE
Is it possible to use a manifest-path to a file not named "Cargo.toml"

### ISSUE THREAD

**Issue by AmitPr** [PyO3/maturin#686]
Hi,
I'm working on a project that needs bindings both for python and for WASM. Because of this, I believe the easiest way to have the two different build systems work is to have two `Cargo.toml` files, one for bindings using `PyO3` (`py_Cargo.toml`) and one using `wasm-pack`(`wasm_Cargo.toml`). 

I was wondering whether it's possible then, to have `maturin` use this `py_Cargo.toml` file instead of looking for a `Cargo.toml`. I've tried:  

```
maturin develop -m py_Cargo.toml 
    💥 maturin failed
      Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
      Caused by: `cargo metadata` exited with an error: error: the manifest-path must be a path to a Cargo.toml file
```

Am I missing something?

**Comment by messense** [comment]
Can you make `cargo build --manifest-path py_Cargo.toml` work? (AFAIK it's not working) If not maturin also can't do it.

**Comment by messense** [comment]
https://github.com/rust-lang/cargo/issues/6690

**Comment by AmitPr** [comment]
I see, not super familiar with rust yet :)
Thanks for the info!
