### ISSUE TITLE
maturin 0.12.0 — broken on macOS

### ISSUE THREAD

**Issue by jnicholls** [PyO3/maturin#689]
Please provide the following information: 
 * Your python version (`python -V`): Python 3.9.8
 * Your pip version (`pip -V`): 21.3.1
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): pyo3 0.14.x
 * Does `cargo build` work? Yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

Please list the exact steps required to reproduce your error with all command output and if possible with a repository:
Just a simple build:

```
❯ maturin develop
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
🐍 Not using a specific python interpreter (With abi3, an interpreter is only required on windows)
💥 maturin failed
  Caused by: Invalid platform string from `sysconfig.get_platform()`
```

0.12.0 [introduced this `get_platform` inspection code](https://github.com/PyO3/maturin/commit/c5a122d4b6fdee1aafc4bc555f27fe747e365d93), which is not parsing correctly it would seem. 0.11.x works fine.

My sysconfig.get_platform() value is `macosx-11-arm64` on my M1 and `macosx-11-x86_64` on my Intel. Neither are working with 0.12.0.

Thanks in advance!

**Comment by jnicholls** [comment]
I've determined it is the `base_version.split_once('.)` call. That returns `None` because there is no dot-separated version in my platform string, it is simply `11`. This is the case on both Big Sur 11.5.2, as well as Monterey 12.0.1, interestingly enough.

Hope this helps. Thanks!

**Comment by messense** [comment]
Thanks for the report, please give 0.12.1-beta.1 a try when it‘s [released to PyPI](https://github.com/PyO3/maturin/actions/runs/1483468990). You can install it by using `pip install -U --pre maturin`.

**Comment by messense** [comment]
maturin v0.12.1 released.
