### ISSUE TITLE
maturin fails if [project] is specified in pyproject.toml

### ISSUE THREAD

**Issue by droundy** [PyO3/maturin#730]
### Bug Description

When I include 
```
[project]
```
in my `pyproject.toml`, maturin fails with
```
💥 maturin failed
  Caused by: pyproject.toml is invalid
  Caused by: pyproject.toml is not PEP 517 compliant: missing field `name` at line 9 column 1
```
This is confusing, because the `Readme.md` states that this is how to specify dependencies of the python code.

### Your Python version (`python -V`)

Python 3.9.2

### Your pip version (`pip -V`)

pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)

### What bindings you're using

cffi

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

git clone https://github.com/droundy/latex_snippet
cd latex_snippet/
maturin build -b cffi # confirm that it builds without this
echo [project] >> pyproject.toml 
maturin build -b cffi

**Comment by droundy** [comment]
I'll mention that perhaps the bug is in the documentation.  I have no knowledge of what the proper format of pyproject.toml is, I'm just trying to address the deprecation warning that says I should specify a `cffi` dependency.

**Comment by messense** [comment]
PEP 621 requires `name` to be statically defined in `pyproject.toml` if `package` field appears: https://www.python.org/dev/peps/pep-0621/#name
