### ISSUE TITLE
Running `maturin develop` can trigger SIGSEV in running process

### ISSUE THREAD

**Issue by cswinter** [PyO3/maturin#758]
### Bug Description

I ran `maturin develop` while a PyO3/maturin package was being used by another Python process, and the Python process died with
`terminated by signal SIGSEGV (Address boundary error)`.

### Your Python version (`python -V`)

Python 3.8.10

### Your pip version (`pip -V`)

pip 21.3.1

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Install a Rust/Python package with maturin develop
2. Start a Python process that imports and calls into the Rust library
3. Run maturin develop again while Python process is still running
4. Segfault

**Comment by cswinter** [comment]
This could still be a coincidence, but the timing was very suspicious and the program was running fine before many times and doesn't use any unsafe code.

**Comment by davidhewitt** [comment]
This sounds completely expected, although it may be worth pointing out in the docs. 

As far as I'm aware, in Linux it's completely expected that if you replace a shared library while a process has loaded part of it into memory, then when the process needs to load more of the shared library you're almost certain to get crashes like this.

**Comment by davidhewitt** [comment]
Oh, actually it _might_ be possible for us to change something? https://stackoverflow.com/questions/3855004/overwriting-library-file-causes-segmentation-fault

**Comment by messense** [comment]
@cswinter Can you try to remove the existing so file first here:

https://github.com/PyO3/maturin/blob/133b3f9f2fbea4ab4348d54ae582c0de1f7ee81c/src/module_writer.rs#L630
