### ISSUE TITLE
Need to either update docs or update installer to ensure users have patchelf

### ISSUE THREAD

**Issue by Peddle** [PyO3/maturin#766]
Not sure the right way to go (documentation or automation) but looks like as of this PR: #742, we need to have patchelf installed otherwise I get this error when running `maturin build --release`

```
💥 maturin failed
  Caused by: Failed to execute 'patchelf', did you install it?
  Caused by: No such file or directory (os error 2)
```

(tested on 0.12.6)

**Comment by messense** [comment]
Just need to document it. Without #742 maturin build will fail with auditwheel error since you have external shard library dependencies.
