### ISSUE TITLE
Better error message when Rust version is too low

### ISSUE THREAD

**Issue by messense** [PyO3/maturin#787]
crates can specify their rustc version requirement: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field, but currently the error message isn't good when Rust version it too low, for example https://github.com/datafusion-contrib/datafusion-python/issues/18

**Comment by konstin** [comment]
To me datafusion-contrib/datafusion-python#18 looks like cargo bug as `cargo metadata` fails to report that it can't match a version because of a rust-version requirement

**Comment by messense** [comment]
I agree it's cargo bug, but old versions of cargo won't get fixed. It'd be nice to make the error message less confusing.
