### ISSUE TITLE
Auto-detect Python Installs from Microsoft Store

### ISSUE THREAD

**Issue by yodaldevoid** [PyO3/maturin#788]
On Windows, maturin supports python installed from python.org installers through `py.exe` and python installed from Conda through, well, `conda`. Neither of these methods support installs from the Microsoft Store.

I believe the Unix-style method of finding all installed versions of python would work for installs from the Microsoft Store as it does create the required `python3.x.exe` executables.

**Comment by messense** [comment]
Taking a note here:

https://docs.microsoft.com/en-us/windows/python/faqs#what-is-py-exe-

> HOWEVER, the py.exe launcher will only work if you are using a version of Python installed from [python.org](https://www.python.org/downloads/windows/). When you install Python from the Microsoft Store, the py command is not included.

**Comment by yodaldevoid** [comment]
I have not found #944 to fix this issue.

```
> maturin list-python
🐍 0 python interpreter found:

> python3.10 --version
Python 3.10.4

> python3.9 --version
Python 3.9.13

> python3.8 --version
Python 3.8.10

> python3.7 --version
Python 3.7.9

>
```
