### ISSUE TITLE
Maturin breaks when you have a directory of stub files instead of a single stub file

### ISSUE THREAD

**Issue by kevinheavey** [PyO3/maturin#792]
### Bug Description

When you run `maturin develop` on a pure Rust project containing a directory of stub files, you get the error message `Found a directory with the module name (solders) next to Cargo.toml, which indicates a mixed python/rust project, but the directory didn't contain an __init__.py file.`

From looking at the maturin code, it looks like it thinks you have a mixed python/rust project when it sees a subdirectory with the same name as the library. If you change the stubs directory name then the type hints don't actually work.

### Your Python version (`python -V`)

Python 3.9

### Your pip version (`pip -V`)

21.2.4

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [x] Yes

### Steps to Reproduce

I've made an example repo here https://github.com/kevinheavey/maturin-stub-package-error

This is what I did:

1. Create a new project with `maturin init`.
2. Make a directory of stub files where the directory name matches the library name.
3. Run `maturin develop` and get the error `Found a directory with the module name (solders) next to Cargo.toml, which indicates a mixed python/rust project, but the directory didn't contain an __init__.py file.`

**Comment by messense** [comment]
Maturin doesn't support pure stub packages right now, so labelling this as a feature request.

**Comment by messense** [comment]
I think [stub only package from PEP 561](https://peps.python.org/pep-0561/#stub-only-packages) is suitable for this? That is you provide a `maturin-stub-package-error-stubs` package for `maturin-stub-package-error`.

**Comment by kevinheavey** [comment]
> I think [stub only package from PEP 561](https://peps.python.org/pep-0561/#stub-only-packages) is suitable for this? That is you provide a `maturin-stub-package-error-stubs` package for `maturin-stub-package-error`.

Does this mean the stub package gets published as a separate package on PyPI?

**Comment by messense** [comment]
> Does this mean the stub package gets published as a separate package on PyPI?

Yes, it needs to be published separately.
