### ISSUE TITLE
v0.12.7 broke maturin-action build in CI.yml

### ISSUE THREAD

**Issue by jeertmans** [PyO3/maturin#803]
### Bug Description

Hello,
It seems like the latest version of `maturin` broke the `maturin-actions`

### Your Python version (`python -V`)

/

### Your pip version (`pip -V`)

/

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. `maturin new maturin-tests`
2. Push `maturin-tests` to GitHub
3. Wait and see how it fails to build:

See example repo here: https://github.com/jeertmans/maturin-tests.
![image](https://user-images.githubusercontent.com/27275099/153000887-36ca8c8d-1045-4dae-b086-86e3133da3fe.png)

**Comment by messense** [comment]
Fixed in

1. https://github.com/PyO3/maturin/commit/e29deccd4e41348b535196868e879acdef8d1f3b
2. https://github.com/messense/maturin-action/commit/73c6889c691c9f69a93c5bf4a173e90668dc31bc
