### ISSUE TITLE
maturin breaks with version 0.12.7 and 0.12.8 due to inexistent pyproject.toml

### ISSUE THREAD

**Issue by tropxy** [PyO3/maturin#805]
### Bug Description

maturin breaks, because expects a pyproject.toml

```sh
	  maturin build \
	  -i /tmp/python3/bin/python3 \
	  --target=armv7-unknown-linux-gnueabihf"
💥 maturin failed
  Caused by: pyproject.toml is invalid
  Caused by: Couldn't find pyproject.toml at /project/pyproject.toml
  Caused by: No such file or directory (os error 2)
make: *** [build] Error 1
```

If maturin v0.12.6 is used, the problem does not occur 

### Your Python version (`python -V`)

Tested with Python 3.8.2 and Python 3.10

### Your pip version (`pip -V`)

pip 21.1.3

### What bindings you're using

pyo3

### Does `cargo build` work?

- [ ] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. install maturin 0.12.8
2. run maturin build

**Comment by messense** [comment]
Do you have a reproducible project?

**Comment by tropxy** [comment]
> Do you have a reproducible project?

Sorry, just saw this now. And I also see you have already merged a solution, thanks ;)
