### ISSUE TITLE
Documented sdist building method isn't working

### ISSUE THREAD

**Issue by itamarst** [PyO3/maturin#810]
### Bug Description

In previous versions, e.g. 0.12.6, and as documented (https://maturin.rs/distribution.html), one could run `maturin build --intepreter` with no additional argument and it would create an sdist tarball.

With 0.12.9, however, I get an error:

```
$ maturin build --interpreter
error: The argument '--interpreter <INTERPRETER>' requires a value but none was supplied
```

### Your Python version (`python -V`)

3.9.7

### Your pip version (`pip -V`)

21.2.4

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

Add appropriate sdist metadata to `pyproject.toml`, then run `maturin build --interpreter`. With 0.12.6 it works, with 0.12.9 it doesn't.

**Comment by messense** [comment]
Thanks for reporting, looks like a regression from the clap 3.0 upgrade.

But I think using `maturin build -i` to build only sdist is kinda odd, and there is also a `maturin sdist` command. The problem with `maturin build -i` is that it assumes Python extension while maturin also supports building bin bindings which doesn't require Python at all.

**Comment by itamarst** [comment]
AH, so this is a documentation issue, then. Specifically https://github.com/PyO3/maturin/blob/main/guide/src/distribution.md?plain=1#L14 should mention `maturin sdist` instead of what it says now.

**Comment by konstin** [comment]
I have no strong opinions, except that I think that the docs should point to `maturin sdist`
