### ISSUE TITLE
allow to include license text file in the wheel metadata

### ISSUE THREAD

**Issue by anthrotype** [PyO3/maturin#829]
the official `wheel` package (used by setuptools' bdist_wheel) has a handy `license_files` option (defined in setup.cfg `[metadata]` section) that allows one to list the license file paths to be included in the generated wheel.

https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=license_files#including-license-files-in-the-generated-wheel-file

Some OSS licenses require one to include the license text along with distributed binaries.

I couldn't find a way to achive this when using maturin. Is it possible to add support for this?

thank you for considering.

**Comment by messense** [comment]
I think you can use the `license` field defined in [PEP 621](https://www.python.org/dev/peps/pep-0621/#license): https://maturin.rs/metadata.html

**Comment by anthrotype** [comment]
oh I didn't know that, thanks! Will that copy the full text of the license file to the wheel .dist-info?

**Comment by anthrotype** [comment]
ok I just tried, I see it copied the full LICENSE text to the METADATA file, not as a separate LICENSE file. That's fine by me. Thank you!

**Comment by anthrotype** [comment]
actually I'm having issues embedding the full text of the LICENSE file when running on Windows.
When I use `license = {file = LICENSE.txt}`, the LICENSE.txt full text is copied to the METADATA file as a [multi-line RFC5322](https://datatracker.ietf.org/doc/html/rfc5322#section-2.2.3) string separated by CRLF, but on Windows I get CRLF twice and that breaks parsing the following README section.

E.g. download the dist.zip file from [here](https://github.com/anthrotype/pngquant-wheels/suites/5545641015/artifacts/178621811), and try to run `twine check pngquant_cli-2.17.0.post2-py3-none-win32.whl`. I get this FAIL error:

```
Checking /Users/clupo/Downloads/dist (8)/pngquant_cli-2.17.0.post2-py3-none-win32.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 1335: Warning: Block quote ends without a blank line; unexpected unindent.
```

If I do the same for the other non-Windows wheels (e.g. the mac or linux ones in the same archive), it works. They differ only by their line endings.

**Comment by messense** [comment]
@anthrotype Thanks for the report, I'll look into it soon.

**Comment by anthrotype** [comment]
thanks! The windows wheels now pass twine check.
However, I noticed that when I upload it to PyPI, it shows the full text of the license under the section named "Meta" at the lower left corner, but it loses all line breaks and formatting, it's like it's on a single very long line of uninterrupted text: e.g.
https://pypi.org/project/pngquant-cli/2.17.1b1/

What the `wheel` module does (when building a wheel with setup.py bdist_wheel command) is adding the license file as it's own separate text file inside .dist-info directory. The _name_ of the license is what the setup.py's `license` keyword contains, then the LICENSE.txt file contains the actual license full text and is automatically included in the sdist manifest. Then `bdst_wheel` can be configured (via setup.cfg's `license_files`) to include the license files in the distribution.

Would it be possible for maturin to distinguish between the `license` parameter (being the name or short line describing a license) and the `license_files` pointing to the paths of the files to be added to the wheel dist-info?

**Comment by messense** [comment]
Notes:

1. https://peps.python.org/pep-0639/#license-file-multiple-use
2. https://github.com/pypa/setuptools/pull/2645

**Comment by messense** [comment]
@anthrotype Opened https://github.com/PyO3/maturin/pull/837 .
