### ISSUE TITLE
Wheel is rebuilt every time, even if there are no changes to the binary

### ISSUE THREAD

**Issue by kaimast** [PyO3/maturin#884]
### Bug Description

`maturin develop` seems to rebuild the wheel every time even if there were no code changes.

Like with regular `cargo build` and `cargo install`, nothing should happen if the code has not been changed and no actual compilation happened. Instead, maturin takes 5-10 seconds to rebuild the wheel.

### Your Python version (`python -V`)

3.10.4

### Your pip version (`pip -V`)

22.0.4 

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [ ] Yes

### Steps to Reproduce

1. Set up a crate that uses pyo3
2. Run `maturing develop`
3. Without changing any code or deleting the target directory, run `maturin develop` again.

**Comment by messense** [comment]
I think this is already tracked in https://github.com/PyO3/pyo3/issues/1708, so closing for now, feel free to reopen if it's a different problem.

**Comment by kaimast** [comment]
> I think this is already tracked in [PyO3/pyo3#1708](https://github.com/PyO3/pyo3/issues/1708), so closing for now, feel free to reopen if it's a different problem.

That's not the same issue. The linked one can be fixed by keeping a dedicated target directory for the python build. 

My issue is that the cargo does not perform any compilation but the wheel is still being rebuild.  In the case below this increase the build time 50 fold.
```
env CARGO_TARGET_DIR=./pytarget time maturin develop -m pyclient/Cargo.toml --cargo-extra-args="--no-default-features "
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /home/kai/dev/pyenv/bin/python
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
📦 Built wheel for CPython 3.10 to /tmp/.tmpu8EOab/datastore_pyclient-0.1.0-cp310-cp310-linux_x86_64.whl
🛠  Installed datastore-pyclient-0.1.0

________________________________________________________
Executed in    4.74 secs    fish           external
   usr time    4.38 secs  364.00 micros    4.38 secs
   sys time    0.34 secs  123.00 micros    0.34 secs
```

**Comment by messense** [comment]
We have switched to [PEP 660 – Editable installs for pyproject.toml based builds (wheel based)](https://peps.python.org/pep-0660/) for `maturin develop` command, thus it needs to build a wheel even if Rust code doesn't change for `pip install -e xxx`.

That said, **you don't need to run `maturin develop`** if there aren't any Rust code changes and Python code changes will be reflected automatically. The only time you need to run it is when there are Rust code changes.

**Comment by TheZoq2** [comment]
I'm also encountering this, or a similar error with `maturin build`

Despite the cargo build being up to date, and me making no changes to the python side of the project, maturin updates the wheel file

```
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
📡 Using build options features from pyproject.toml
    Finished release [optimized] target(s) in 0.01s
📦 Built wheel for abi3 Python ≥ 3.7 to /home/frans/Documents/rust/maturin_test/target/wheels/maturin_test-0.1.0-cp37-abi3-manylinux_2_34_x86_64.whl
```

This in turn means that I have no way to detect if I need to re-install the wheel

For reference, I'm running `maturin build --release -b pyo3`
