### ISSUE TITLE
Cannot cross compile with windows. x86_64-w64-mingw32/bin/ld: cannot find -lpython3: No such file or directory

### ISSUE THREAD

**Issue by ReggieMarr** [PyO3/maturin#924]
### Bug Description

When trying to cross compile for windows the build fails with the following
x86_64-w64-mingw32/bin/ld: cannot find -lpython3: No such file or directory.

I'm building using manjaro with.

### Your Python version (`python -V`)

Python 3.8

### Your pip version (`pip -V`)

pip 22.1 

### What bindings you're using

pyo3

### Does `cargo build` work?

- [X] Yes, it works

### If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)?

- [X] Yes

### Steps to Reproduce

1. ❯ cargo build --target x86_64-pc-windows-gnu works
2. ❯ maturin build --target x86_64-pc-windows-gnu fails

**Comment by messense** [comment]
`maturin build --target x86_64-pc-windows-gnu` [works on CI](https://github.com/PyO3/maturin/blob/1e5d31713de88c76b595f71806ad24664b7a82a3/.github/workflows/test.yml#L128-L129) so you need to provide more information.

1. What version of maturin are you using?
2. What version of pyo3 are you using and what features are activated?
3. Did you set `PYO3_CROSS_LIB_DIR` or other related environment variables?

It'd be great if you can provide a minimal reproduction project.

**Comment by ReggieMarr** [comment]
So oddly enough this issue seems to resolve itself. The only reason I can think of is due to updating the rust toolchain (which happened when I switched defaults so I don't know what it was before).
I'll close this for now and reopen if need be. 

For reference I was using

maturin 0.12.15 and pyo3 0.16.5. I did not set PYO3_CROSS_LIB_DIR
