### ISSUE TITLE
Describe that `repository-url` parameter may be used to pass `.pypirc` repository name

### ISSUE THREAD

**Issue by pwlodarczyk92** [PyO3/maturin#985]
It took me quite some time to find out how to publish a package to a private repository with credentials passed via `.pypirc` file. The most obvious thing was to pass the repository url via command line parameter, but the script was still asking me for a username and a password. I needed to take a look at the sources to find out that this parameter can be also used to pass repository name, and only then the `.pypirc` file is used.

This behaviour was a bit difficult for me to discover because:
- parameter name and description suggest that there's nothing else than a url that can be passed via this parameter
- in case of `upload.pypi.org` registry url, the registry name is inferred automatically and `.pypirc` file is used as intended
- the `.pypirc` file was configured automatically by the aws codeartifact cli, so I didn't even know that there is a repository name distinct from the url that I can use to identify it.

Thanks for working on this package!

**Comment by messense** [comment]
I think we should follow `twine` and split the current `repository-url` option to `repository` and `repository-url`.

https://twine.readthedocs.io/en/stable/#twine-upload
